### ISSUE TITLE
Confusing exception when using SqlUpdate instead of SqlQuery

### ISSUE THREAD

**Issue by electrum** [jdbi/jdbi#102]
If you accidentally use `@SqlUpdate` instead of `@SqlQuery`, you get a confusing `ClassCastException`:

```
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.List
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$f05b82e8.getViews(<generated>)
```

Example incorrect usage:

```
@SqlUpdate("select name from something")
List<String> getNames();

**Comment by magnusr** [comment]
The same problem occurs with @SqlBatch methods returning scalars.

**Comment by stevenschlansker** [comment]
Closed via #124

**Comment by michael-newsrx** [comment]
Here's one that does this most confusion exception also:

@SqlBatch("delete from " + table_historical_exchanges + " where market_id not in (<id>)")
public int _deleteOldHistoricalExchanges(@BindIn("id") Iterable<String> marketIds);

**Comment by stevenschlansker** [comment]
Hi @michael-newsrx, what is the exception?  What version are you reporting against?  Maybe this deserves a new issue, this one is already closed, unless you think the problem you see is precisely the same one as outlined in this issue.

**Comment by michael-newsrx** [comment]
version 2.71 via Maven/Gradle

Method Signature:

`@SqlBatch("delete from " + table_historical_exchanges + " where market_id not in (<ids>)")
public int[] _deleteOldHistoricalExchanges(@BindIn("ids") Iterable<String> marketIds);`

Exception:

`java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Iterable
	at org.skife.jdbi.v2.unstable.BindIn$BindingFactory$1.bind(BindIn.java:104)
	at org.skife.jdbi.v2.sqlobject.Bindifier.bind(Bindifier.java:35)
	at org.skife.jdbi.v2.sqlobject.CustomizingStatementHandler.applyBinders(CustomizingStatementHandler.java:127)
	at org.skife.jdbi.v2.sqlobject.BatchHandler.invoke(BatchHandler.java:150)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:212)
	at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:109)
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$3f576dca._deleteOldHistoricalExchanges(<generated>)
	at com.newsrx.xignite.dao.DaoXignite.addOrUpdateHistoricalExchanges(DaoXignite.java:140)
	at com.newsrx.xignite.scraper.App.getExchanges(App.java:420)
	at com.newsrx.xignite.scraper.App._run(App.java:82)
	at com.newsrx.xignite.scraper.App.run(App.java:63)
`

**Comment by stevenschlansker** [comment]
@michael-newsrx Are you sure you want `@BindIn` annotation on your `marketIds`?  Does it work with a plain `@Bind`?  My understanding is that binding an `IN` like statement would not combine well with `@SqlBatch` at all -- at least I doubt anyone has ever tested it, and I think it's redundant for your use case.

If you want to file a separate issue for the confusing error, please open a new ticket -- this is not the same issue.
