### ISSUE TITLE
Jdbi3 produces ORA-01000 for @SqlBatch

### ISSUE THREAD

**Issue by mseele** [jdbi/jdbi#1043]
Jdbi v3 produces an ORA-01000 for @SqlBatch where jdbi v2 does not (which seems to be correct). 
There seems to be a problem on closing the batch statement.

Please see the attached files to reproduce the bug. 

[BatchBugJdbi2.txt](https://github.com/jdbi/jdbi/files/1825288/BatchBugJdbi2.txt) runs against jdbi v2 and works as expected.

[BatchBugJdbi3.txt](https://github.com/jdbi/jdbi/files/1825289/BatchBugJdbi3.txt) runs against jdbi v3 and fails.

This is the stack trace:

```
org.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.BatchUpdateException: ORA-01000: Maximale Anzahl offener Cursor überschritten
 [statement:"INSERT INTO test_tablespace.<link_table> (		<id>, 		change_id,         <value_id> ) VALUES (		:id,         :change_id,         :value_id )", rewritten:"INSERT INTO test_tablespace.test_batch (		id, 		change_id,         value_id ) VALUES (		:id,         :change_id,         :value_id )", parsed:"ParsedSql{sql='INSERT INTO test_tablespace.test_batch (		id, 		change_id,         value_id ) VALUES (		?,         ?,         ? )', parameters=ParsedParameters{positional=false, parameterNames=[id, change_id, value_id]}}", arguments:{ positional:{3:299,4:1,5:19}, named:{change_id:1,id:299,value_id:19}, finder:[]}]
	at org.jdbi.v3.core.statement.PreparedBatch.internalBatchExecute(PreparedBatch.java:198)
	at org.jdbi.v3.core.statement.PreparedBatch.execute(PreparedBatch.java:71)
	at org.jdbi.v3.core.statement.PreparedBatch.executeAndGetModCount(PreparedBatch.java:76)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.executeBatch(SqlBatchHandler.java:318)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.access$000(SqlBatchHandler.java:46)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler$2.hasNext(SqlBatchHandler.java:214)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler$2.<init>(SqlBatchHandler.java:188)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.invoke(SqlBatchHandler.java:183)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:162)
	at org.jdbi.v3.core.ConstantHandleSupplier.invokeInContext(ConstantHandleSupplier.java:52)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:161)
	at com.sun.proxy.$Proxy9.insert(Unknown Source)
	at BatchBugJdbi3.lambda$0(BatchBugJdbi3.java:45)
	at org.jdbi.v3.core.Handle.lambda$useTransaction$1(Handle.java:391)
	at org.jdbi.v3.core.transaction.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:150)
	at org.jdbi.v3.core.Handle.useTransaction(Handle.java:390)
	at BatchBugJdbi3.main(BatchBugJdbi3.java:36)
Caused by: java.sql.BatchUpdateException: ORA-01000: Maximale Anzahl offener Cursor überschritten

	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeBatch(OraclePreparedStatement.java:10032)
	at oracle.jdbc.driver.T4CPreparedStatement.executeLargeBatch(T4CPreparedStatement.java:1364)
	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9839)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:234)
	at org.jdbi.v3.core.statement.PreparedBatch.internalBatchExecute(PreparedBatch.java:186)
	... 16 more
	Suppressed: java.sql.SQLException: ORA-01000: Maximale Anzahl offener Cursor überschritten

		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
		at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
		at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
		at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
		at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
		at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226)
		at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59)
		at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:910)
		at oracle.jdbc.driver.OraclePreparedStatement.executeForRowsWithTimeout(OraclePreparedStatement.java:9804)
		at oracle.jdbc.driver.OraclePreparedStatement.executeLargeBatch(OraclePreparedStatement.java:9904)
		... 20 more
	Caused by: Error : 1000, Position : 0, Sql = INSERT INTO test_tablespace.test_batch (		id, 		change_id,         value_id ) VALUES (		:1 ,         :2 ,         :3  ), OriginalSql = INSERT INTO test_tablespace.test_batch (		id, 		change_id,         value_id ) VALUES (		?,         ?,         ? ), Error Msg = ORA-01000: Maximale Anzahl offener Cursor überschritten

		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
		... 30 more

```

**Comment by arteam** [comment]
A couple of observations:
* It seems that you attach `Dao` to the handle outside of the transaction. This is not a standard way to use transactions with the SqlObject API. Usually it's done via a default method on the interface with a `@Transactional` annotation or via the `getHandle` method of the `SqlObject` mixin.
* Does your test fail if you use `PreparedBatch` directly without the SqlObject API?
* Can you try to use `PreparedBatch` directly, close it after an execution, and see whether it makes any difference?
* Would be it possible to remove the inner loop by ids by preparing a list of ids beforehand, creating n copies of the list of value ids, and then executing one batch request without any explicit transactions?

**Comment by mseele** [comment]
@arteam, thank you for looking into this. 
Here are my test results:

- It seems that you attach `Dao` to the handle outside of the transaction. This is not a standard way to use transactions with the SqlObject API. Usually it's done via a default method on the interface with a `@Transactional` annotation or via the `getHandle` method of the `SqlObject` mixin.

[BatchBugJdbi3_mixins.txt](https://github.com/jdbi/jdbi/files/1828400/BatchBugJdbi3_mixins.txt) there is no difference in using a mixin (we still get the error)
[BatchBugJdbi3_default_method.txt](https://github.com/jdbi/jdbi/files/1828402/BatchBugJdbi3_default_method.txt) there is no difference in using a default method with transactional (we still get the error)

- Does your test fail if you use `PreparedBatch` directly without the SqlObject API?

[BatchBugJdbi3_prepared_batch_inside.txt](https://github.com/jdbi/jdbi/files/1828409/BatchBugJdbi3_prepared_batch_inside.txt) it fails if i execute the PreparedBatch inside the loop
[BatchBugJdbi3_prepared_batch.txt](https://github.com/jdbi/jdbi/files/1828408/BatchBugJdbi3_prepared_batch.txt) it works when i do a "big" prepared batch and execute it outside the loop

- Can you try to use `PreparedBatch` directly, close it after an execution, and see whether it makes any difference?

[BatchBugJdbi3_prepared_batch_inside_and_close.txt](https://github.com/jdbi/jdbi/files/1828416/BatchBugJdbi3_prepared_batch_inside_and_close.txt) it works when i use a PreparedBatch inside the loop, execute and close is directly (this is how i thought @SqlBatch will work)

- Would be it possible to remove the inner loop by ids by preparing a list of ids beforehand, creating n copies of the list of value ids, and then executing one batch request without any explicit transactions?

In the demo yes, but in our application this is not possible. What i wonder ist why the same code worked under jdbi2 and now fails under jdbi3 (we just migrated our code from jdbi2 to jdbi3 and now get this error).

One more thing, when i do it without the transaction, i have the same results (It has nothing to do with the transaction). 

The problem seems to be that the `@SqlBatch` does not close directly after the execute....

**Comment by mseele** [comment]
After a deeper investigation, it looks like something fails in `org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler`

**Comment by mseele** [comment]
I striped the whole thing down to something more simple. I know it makes no sense to do a batch like this, i only want to show the bug. I think `successBatch` and `errorBatch` should both work.
Here is the code:

```
import java.util.Arrays;
import java.util.List;

import org.jdbi.v3.core.Handle;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.core.statement.PreparedBatch;
import org.jdbi.v3.sqlobject.SqlObject;
import org.jdbi.v3.sqlobject.SqlObjectPlugin;
import org.jdbi.v3.sqlobject.customizer.Bind;
import org.jdbi.v3.sqlobject.statement.SqlBatch;
import org.jdbi.v3.sqlobject.statement.SqlUpdate;

public class BatchBugJdbi3 {

	public static void main(String[] args) {
		Jdbi jdbi = Jdbi.create("jdbc:oracle:thin:@ghlx08:1521:guh2", "username", "password");
		jdbi.installPlugin(new SqlObjectPlugin());
		
		// create table
		try (Handle handle = jdbi.open()) {
			handle.attach(DAO.class).create();
		}
		
		try {
			// run batch
			try (Handle handle = jdbi.open()) {
				DAO dao = handle.attach(DAO.class);
				
				// success
				int index = 0;
				for (; index < 2000; index++) {
					dao.successBatch(Arrays.asList(Long.valueOf(index)));
				}
				
				System.err.println("successBatch done");
				
				// error
				for (; index < 4000; index++) {
					dao.errorBatch(Arrays.asList(Long.valueOf(index)));
				}
				
				System.err.println("errorBatch done");
			}
		} catch (Throwable t) {
			System.err.println("ORA-01000 happened :(");
			t.printStackTrace();
		} finally {
			// create table
			try (Handle handle = jdbi.open()) {
				handle.attach(DAO.class).delete();
			}
		}
	}

	public interface DAO extends SqlObject {

		@SqlUpdate("create table test_batch (id	NUMBER NOT NULL) TABLESPACE test_tablespace")
		void create();

		default void successBatch(List<Long> ids) {
			try (PreparedBatch batch = getHandle().prepareBatch("INSERT INTO test_tablespace.test_batch (id) VALUES (:id)")) { //$NON-NLS-1$
				ids.forEach(id -> batch.bind("id", id).add()); //$NON-NLS-1$
				batch.execute();
			}
		}
		
		@SqlBatch("INSERT INTO test_tablespace.test_batch (id) VALUES (:id)")
		void errorBatch(@Bind("id") List<Long> ids);

		@SqlUpdate("DROP TABLE test_tablespace.test_batch")
		void delete();

	}
	
}

```

**Comment by mseele** [comment]
If executeAndGetModCount is used in org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler:67, the statement is never closed. pr #1084 fixes that.
