### ISSUE TITLE
use jdbi-jpa error

### ISSUE THREAD

**Issue by kkrgwbj** [jdbi/jdbi#1047]
### Expected behavior and actual behavior:

public class BeanTest {
    @Column(name = "PHONE_NUM")
    private String phone;
}
 @Test
    public void test2() {
        List<BeanTest> strings = jdbi.withHandle(handle ->
                handle.createQuery(PagingUtil.getPageSql("select * from t_group_detection_customers t where t.phone_num = ?", new Pageable()))
                        .bind(0, "13733150273")
                        .mapToBean(BeanTest.class).list());
        System.out.println(strings);
    }

### Steps to reproduce the problem:
java.lang.IllegalArgumentException: Mapping bean type class BeanTest didn't find any matching columns in result set

	at org.jdbi.v3.core.mapper.reflect.BeanMapper.specialize0(BeanMapper.java:185)
	at org.jdbi.v3.core.mapper.reflect.BeanMapper.specialize(BeanMapper.java:128)
	at org.jdbi.v3.core.result.ResultSetResultIterator.<init>(ResultSetResultIterator.java:38)
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:53)
	at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:141)
	at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:197)
	at org.jdbi.v3.core.result.ResultIterable.list(ResultIterable.java:186)
	at TestHnmccServer.lambda$test2$0(TestHnmccServer.java:38)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:340)
	at TestHnmccServer.test2(TestHnmccServer.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

### Versions:

- jdbi3:
- Java:jdk1.8
- Database (include vendor):oracle
- OS:windows10

**Comment by kkrgwbj** [comment]
@qualidafial @stevenschlansker

**Comment by kkrgwbj** [comment]
The same code, I use JOOQ is no problem.

**Comment by qualidafial** [comment]
If you are using `BeanMapper` (implied by `mapToBean(Class)` call), then you should use the `@ColumnName` annotation instead of JPA's `@Column`.

If you want to use JPA annotations (of which we support only a minimal amount), you need to:

* Install the JPA plugin: http://jdbi.org/#_jpa
* Use `mapTo(Class)` instead of `mapToBean()` so it will use the JPA mapper.

**Comment by kkrgwbj** [comment]
I have installed the jdbi-jpa plugin and retry the mapTo(T) according to your requirements. There is still something error.
```java

    @Bean(name = "jdbi")
    public JdbiFactoryBean jdbiFactoryBean() {
        return new JdbiFactoryBean(dataSource).setPlugins(Arrays.asList(new JpaPlugin()));
    }
 @Test
    public void test2() {
        List<BeanTest> strings = jdbi.withHandle(handle ->
                handle.createQuery(PagingUtil.getPageSql("select * from t_group_detection_customers t where t.phone_num = ?", new Pageable()))
                        .bind(0, "13733150273")
                        .mapTo(BeanTest.class).list());
        System.out.println(strings);
    }

org.jdbi.v3.core.mapper.NoSuchMapperException: No mapper registered for type class BeanTest

**Comment by kkrgwbj** [comment]
```java
@Data
public class BeanTest {
    @Column(name = "PHONE_NUM")
    private String phone;
}

**Comment by stevenschlansker** [comment]
It's a fair point that `mapToBean` doesn't use the same strategy lookup as `mapTo`.  But the behavior is intentional, and I don't think we could change it -- `mapToBean` means to use the `BeanMapper` over any other available mapper.
