### ISSUE TITLE
[bug?] templating makes Lexer trip over query

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#1071]
I'm trying to execute the statement `backup database to ?` with ? bound to a file path as string (e.g. `'db/backup/'`). This command is an hsqldb feature.

It does not work with jdbi: no matter how I try to execute the statement or in what form I bind the parameter, I always get `java.sql.SQLSyntaxErrorException: unexpected token: ? in statement [backup database to ?]`

Is this a known limitation of the binding code? That it can only handle "standard" sql and not foreign commands like this? Or should I go further into details?

**Comment by qualidafial** [comment]
Are you using an `Update` or something else?

**Comment by TheRealMarnes** [comment]
@qualidafial I've tried handle.execute, handle.createUpdate, handle.createCall, handle.prepareBatch, ...

`backup database to ?` keeps failing with
> java.sql.SQLSyntaxErrorException: unexpected token: ? in statement [backup database to ?]
no matter how I try to execute it. Seems to be a parser limitation.

Worse, if I prepare the statement myself and just pass the final string to jdbi to execute without binding/parsing, it works, but only if I leave out the `as files` clause. `backup database to 'foo' as files` fails no matter what, with
>UnableToCreateStatementException: Error rendering SQL template: 'backup database to 'db\backup\backup_2018-04-09_19-35-50\' as files' [statement:"backup database to 'db\backup\backup_2018-04-09_19-35-50\' as files", rewritten:"null", parsed:"null", arguments:{ positional:{}, named:{}, finder:[]}]
>Caused by: org.antlr.runtime.MismatchedTokenException: null
	at org.antlr.runtime.Lexer.match(Lexer.java:197)

**Comment by stevenschlansker** [comment]
Often non-DDL statements do not take parameters at all -- for example you cannot parameterize `DROP TABLE ?`.

Instead, you have to `DROP TABLE <name>`, `.define("name", tableName)`, and use one of the template engines to substitute it textually.

I'm not positive for this `backup` case, but it could easily be the same problem.

**Comment by stevenschlansker** [comment]
The latter `UnableToCreateStatementException` does look like a parser limitation, we should probably treat separate to the initial `backup database to ?` problem.

**Comment by TheRealMarnes** [comment]
Hmm, I guess using templating is the answer in this case. I didn't realize parameterizing a statement is handled in the database, not jdbi/jdbc.

Sorry if I seem confused, I'm just juggling a dozen variations of the same code around and the stacktraces are very similar yet subtly different...

**Comment by TheRealMarnes** [comment]
Ok, so using the `?` placeholder is out of the question because parameterizing is handled in the database itself, not above it.

That leaves the problem with the `as files` clause. I just tried to reproduce it, leaving parameterization out of the picture entirely... and it just works. I can't reproduce that Lexer error anymore.

Sorry guys, looks like I'm just screwing up today... Everything seems to be working correctly, except my brain...

**Comment by qualidafial** [comment]
No problem. Which database vendor are you using? It's helpful to get a mental model of which databases are picky about what.

**Comment by TheRealMarnes** [comment]
Hsqldb

It has some custom syntax like `create cached table` and the backup command, and it's got a surprising number of bugs in the jdbc driver (being unable to handle datatypes that are specifically mentioned as directly supported), but I find it a pleasant no-nonsense no-magic db to work with...

**Comment by TheRealMarnes** [comment]
Say, reading the templating docs on jdbi.org, might I suggest a MessageFormat TemplateEngine impl?

**Comment by TheRealMarnes** [comment]
Oh man 😁 I found a way to reproduce that Lexer error again... and win the prize for most horrific one-liner solution at the same time.

```java
jdbi.useHandle(handle -> handle.createCall("backup database to ''{0}{1}'' as files").setTemplateEngine((template, ctx) -> MessageFormat.format(template, ctx.getAttributes().entrySet().stream().sorted(Comparator.comparingInt(o -> Integer.valueOf(o.getKey()))).map(Map.Entry::getValue).toArray(Object[]::new))).define("0", path).define("1", File.separator).invoke());
```

>org.jdbi.v3.core.statement.UnableToCreateStatementException: Exception parsing for named parameter replacement [statement:"backup database to ''{0}{1}'' as files", rewritten:"backup database to 'db\backup\backup_2018-04-09_20-24-29\' as files", parsed:"null", arguments:{ positional:{}, named:{}, finder:[]}]
	at org.jdbi.v3.core.statement.ColonPrefixSqlParser.parse(ColonPrefixSqlParser.java:41)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1420)
	at org.jdbi.v3.core.statement.Call.invoke(Call.java:93)
	at net.leaumar.samstock.integration.db.BackupService.lambda$backup$3(BackupService.java:30)
	at org.jdbi.v3.core.Jdbi.lambda$useHandle$4(Jdbi.java:355)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:340)
	at org.jdbi.v3.core.Jdbi.useHandle(Jdbi.java:355)
	at net.leaumar.samstock.integration.db.BackupService.backup(BackupService.java:29)
	at net.leaumar.samstock.web.rest.BackupController.backup(BackupController.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: MismatchedTokenException(-1!=39)
	at org.jdbi.v3.core.internal.lexer.ColonStatementLexer.reportError(ColonStatementLexer.java:31)
	at org.antlr.runtime.Lexer.nextToken(Lexer.java:103)
	at org.jdbi.v3.core.statement.ColonPrefixSqlParser.internalParse(ColonPrefixSqlParser.java:74)
	at java.util.Map.computeIfAbsent(Map.java:957)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)
	at org.jdbi.v3.core.statement.ColonPrefixSqlParser.parse(ColonPrefixSqlParser.java:39)
	... 62 common frames omitted
Caused by: org.antlr.runtime.MismatchedTokenException: null
	at org.antlr.runtime.Lexer.match(Lexer.java:197)
	at org.jdbi.v3.core.internal.lexer.ColonStatementLexer.mQUOTE(ColonStatementLexer.java:56)
	at org.jdbi.v3.core.internal.lexer.ColonStatementLexer.mQUOTED_TEXT(ColonStatementLexer.java:338)
	at org.jdbi.v3.core.internal.lexer.ColonStatementLexer.mTokens(ColonStatementLexer.java:1043)
	at org.antlr.runtime.Lexer.nextToken(Lexer.java:89)
	... 66 common frames omitted

**Comment by TheRealMarnes** [comment]
Well, here's my take on a TemplateEngine with my favorite templater, MessageFormat

```java
public enum MessageFormatTemplateEngine implements TemplateEngine {
	INSTANCE;
	
	@Override
	public String render(String template, StatementContext ctx) {
		Object[] args = ctx.getAttributes()
			.entrySet()
			.stream()
			.map(x -> Pair.of(Integer.valueOf(x.getKey()), x.getValue()))
			.sorted(Comparator.comparingInt(Pair::getKey))
			.map(Pair::getValue)
			.toArray(Object[]::new);

		return MessageFormat.format(template, args);
	}
}
```

Maybe include it in jdbi for people who like to roll that way? :p

**Comment by TheRealMarnes** [comment]
For comparison, this works just fine:
```java
jdbi.useHandle(handle -> handle.createCall("backup database to 'db/backup/' as files")
	//.setTemplateEngine(MessageFormatTemplateEngine.INSTANCE)
	//.define("0", path)
	//.define("1", File.separator)
	.invoke());
```

So it really is templating not playing nice with whatever's going on further down the hood.

**Comment by TheRealMarnes** [comment]
Aha, the issue is actually the last character in my string. The windows path separator is \ and the lexer interprets it as an escape character on the closing single quote. This works just fine:

```java
jdbi.useHandle(handle -> handle.createCall("backup database to ''{0}{1}'' as files")
	.setTemplateEngine(MessageFormatTemplateEngine.INSTANCE)
	.define("0", configService.get().getBackupFolder())
	.define("1", "/")
	.invoke());
```

Nasty pitfall but not exactly a bug in jdbi or anything. Sorry to be a bother guys, looks like all is well after all, and we know a new "gotcha" to look out for.

**Comment by stevenschlansker** [comment]
If you find the MessageFormatTemplteEngine useful, it looks simple and innocuous enough to include.  Feel free to file a PR.

**Comment by TheRealMarnes** [comment]
Are you guys fans of using enum for singleton purposes or rather a public static final field?

**Comment by stevenschlansker** [comment]
It's a fine pattern for something like this.  I think it's a little weird but it's the most direct and foolproof way to get a true singleton that I'm aware of.
