### ISSUE TITLE
SQL Object does not resolve generic return type when invoking methods through reference of parent type.

### ISSUE THREAD

**Issue by dcrn** [jdbi/jdbi#1082]
I made a test case for this:
```java
public class GenericDaoUsageTest {
    @Rule
    public H2DatabaseRule dbRule = new H2DatabaseRule().withPlugin(new SqlObjectPlugin());

    @Before
    public void setUp() {
        Handle handle = dbRule.getSharedHandle();
        handle.execute("CREATE TABLE usermodel (id identity primary key, name VARCHAR)");
        handle.attach(UserDao.class).insert(new UserModel(1));
    }

    @Test
    public <D extends Dao<T, PK>, T extends Model<PK>, PK> void testSqlObject_useGenericDaoInterface() {
        UserDao userDao = dbRule.getJdbi().onDemand(UserDao.class);
        T entity = ((D) userDao).getById((PK) (Object) 1);
    }

    @Test
    public void testSqlObject_useConcreteDaoInterface() {
        UserDao userDao = dbRule.getJdbi().onDemand(UserDao.class);
        UserModel entity = userDao.getById(1);
    }

    public interface Dao<T extends Model<PK>, PK> extends SqlObject {
        T getById(PK id);

        Integer insert(T entity);
    }

    public interface Model<PK> {
        PK getId();

        void setId(PK id);
    }

    @RegisterBeanMapper(UserModel.class)
    public interface UserDao extends Dao<UserModel, Integer> {
        @Override
        @SqlQuery("SELECT * FROM UserModel WHERE id = :id")
        UserModel getById(Integer id);

        @Override
        @SqlUpdate("INSERT INTO UserModel (id) VALUES(:id)")
        @GetGeneratedKeys
        Integer insert(@BindBean UserModel user);
    }

    public static class UserModel implements Model<Integer> {
        private int id;

        public UserModel() {
        }

        public UserModel(int id) {
            this.id = id;
        }

        @Override
        public Integer getId() {
            return id;
        }

        @Override
        public void setId(Integer id) {
            this.id = id;
        }
    }
}

```

**Comment by stevenschlansker** [comment]
Can you include the exception you see, especially the full message and stacktrace through jdbi leading to the failure?  Thanks for reporting.

**Comment by qualidafial** [comment]
Stack trace from running the provided test:

```
org.jdbi.v3.core.mapper.NoSuchMapperException: No mapper registered for type interface org.jdbi.v3.sqlobject.GenericDaoUsageTest$Model

	at org.jdbi.v3.core.result.ResultBearing.lambda$null$0(ResultBearing.java:118)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.jdbi.v3.core.result.ResultBearing.lambda$mapTo$1(ResultBearing.java:118)
	at org.jdbi.v3.core.result.ResultBearing$1.scanResultSet(ResultBearing.java:56)
	at org.jdbi.v3.core.statement.Query.scanResultSet(Query.java:59)
	at org.jdbi.v3.core.result.ResultBearing.mapTo(ResultBearing.java:116)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:52)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:157)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:26)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:157)
	at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:23)
	at org.jdbi.v3.core.LazyHandleSupplier.lambda$invokeInContext$1(LazyHandleSupplier.java:68)
	at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:23)
	at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:67)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:156)
	at org.jdbi.v3.core.OnDemandExtensions.invoke(OnDemandExtensions.java:72)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$null$0(OnDemandExtensions.java:60)
	at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:23)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$null$1(OnDemandExtensions.java:59)
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:462)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$create$2(OnDemandExtensions.java:58)
	at com.sun.proxy.$Proxy15.getById(Unknown Source)
	at org.jdbi.v3.sqlobject.GenericDaoUsageTest.testSqlObject_useGenericDaoInterface(GenericDaoUsageTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)```

This is weird.

When we call `getGenericReturnType()` on `UserDao.getById()` method object, we get `UserModel.class` as the method return type.

However when we call `getGenericReturnType()` on `Dao.getById()`, it returns simply `Model.class` instead of a wildcard e.g. `T extends Model<PK>` as you would expect.

**Comment by qualidafial** [comment]
Ok, the method being passed to the invocation handler in the failing test is a bridge method. All the type information is erased on that method, so SQL Object has nothing with which to resolve the return type. That makes sense now.

Probably what we want to do is try to find out which method the bridge method delegates to and just use that handler.

Spring has a BridgeMethodResolver class to guess at the right method but the implementation looks pretty sketchy. https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/BridgeMethodResolver.java
