### ISSUE TITLE
Cannot handle certain SQL (nested) statements

### ISSUE THREAD

**Issue by a1anw2** [jdbi/jdbi#1083]
Was loving JDBI up until I hit this rather interesting bug.

Bottom line:  certain SQL statements fail to either subs :Property or Property

Here is the SQL statement that fails to do anything, either as a property or as defined block.

```
SELECT 
	* 
FROM 
	event e
WHERE
	e.eventId = ifnull((
		select eventId 
		from event 
		where eventType='session' 
		and eventState IN ('planned','scheduled','started','completed') 
		and startDt<now() 
		and tutorId = :tutorId
		and userAttendeeId = :userAttendeeId
		limit 1
		),0)
    or e.eventId = ifnull((
    	select eventId 
    	from event 
    	where eventType='session' 
    	and eventState IN ('planned','scheduled','started') 
    	and startDt>now() 
    	and tutorId = :tutorId
    	and userAttendeeId = :userAttendeeId
    	limit 1
    	),0)
ORDER BY
	e.startDt asc
```

The error message:

org.jdbi.v3.core.statement.UnableToCreateStatementException: Error rendering SQL template: 'SELECT  	*  FROM  	event e WHERE 	e.eventId = ifnull(( 		select eventId  		from event  		where eventType='session'  		and eventState IN ('planned','scheduled','started','completed')  		and startDt<now()  		and tutorId = :tutorId 		and userAttendeeId = :userAttendeeId 		limit 1 		),0)     or e.eventId = ifnull((     	select eventId      	from event      	where eventType='session'      	and eventState IN ('planned','scheduled','started')      	and startDt>now()      	and tutorId = :tutorId     	and userAttendeeId = :userAttendeeId     	limit 1     	),0) ORDER BY 	e.startDt asc' [statement:"SELECT  	*  FROM  	event e WHERE 	e.eventId = ifnull(( 		select eventId  		from event  		where eventType='session'  		and eventState IN ('planned','scheduled','started','completed')  		and startDt<now()  		and tutorId = :tutorId 		and userAttendeeId = :userAttendeeId 		limit 1 		),0)     or e.eventId = ifnull((     	select eventId      	from event      	where eventType='session'      	and eventState IN ('planned','scheduled','started')      	and startDt>now()      	and tutorId = :tutorId     	and userAttendeeId = :userAttendeeId     	limit 1     	),0) ORDER BY 	e.startDt asc", rewritten:"null", parsed:"null", arguments:{ positional:{0:1wfmT6,1:11NdCd}, named:{tutorId:1wfmT6,userAttendeeId:11NdCd}, finder:[]}]

What is my workaround here?

**Comment by a1anw2** [comment]
Okay ... another error related to this ... if i attempt to unwrap the SQL statement and just pass it into handle.createQuery() i get this:

```
org.jdbi.v3.core.statement.UnableToCreateStatementException: Error rendering SQL template: 'SELECT 
	* 
FROM 
	event e
WHERE
(
	e.eventId = ifnull((
		select eventId 
		from event 
		where eventType='session' 
		and eventState IN ('planned','scheduled','started','completed') 
		and startDt<now() 
		and tutorId = '1wfmT6'
		and userAttendeeId = '11NdCd'
		limit 1
		),0)
    or e.eventId = ifnull((
    	select eventId 
    	from event 
    	where eventType='session' 
    	and eventState IN ('planned','scheduled','started') 
    	and startDt>now() 
    	and tutorId = '1wfmT6'
    	and userAttendeeId = '11NdCd'
    	limit 1
    	),0)
)
ORDER BY
	e.startDt asc' [statement:"SELECT 
	* 
FROM 
	event e
WHERE
(
	e.eventId = ifnull((
		select eventId 
		from event 
		where eventType='session' 
		and eventState IN ('planned','scheduled','started','completed') 
		and startDt<now() 
		and tutorId = '1wfmT6'
		and userAttendeeId = '11NdCd'
		limit 1
		),0)
    or e.eventId = ifnull((
    	select eventId 
    	from event 
    	where eventType='session' 
    	and eventState IN ('planned','scheduled','started') 
    	and startDt>now() 
    	and tutorId = '1wfmT6'
    	and userAttendeeId = '11NdCd'
    	limit 1
    	),0)
)
ORDER BY
	e.startDt asc", rewritten:"null", parsed:"null", arguments:{ positional:{}, named:{}, finder:[]}]
```

So my workaround isn't even working; how do I stop JDBI from even attempting to parse the SQL statement?   This is a legal statement incidentally for MySQL

**Comment by a1anw2** [comment]
Found the problem.

The parser is not liking the shortened "startDt<now()".   If I change it to "startDt < now()" then all is well in the world.

I am going to leave this bug open as it is a parsing error and the very least should help others that may hit upon this.

**Comment by stevenschlansker** [comment]
Was there any further output?  The exception you shared ought to have a cause which I think is not included in the bug report.

**Comment by a1anw2** [comment]
there was nothing that would have helped.   Though, it should be easy to recreate now that we know the parser is sensitive to whitespace

**Comment by stevenschlansker** [comment]
I am able to reproduce this in a test case.  The cause nested in the exception is in fact useful to understanding what's going on:

```
Caused by: MismatchedTokenException(40!=62)
	at org.antlr.runtime.Lexer.match(Lexer.java:197)
	at org.jdbi.v3.core.internal.lexer.DefineStatementLexer.mGT(DefineStatementLexer.java:149)
	at org.jdbi.v3.core.internal.lexer.DefineStatementLexer.mDEFINE(DefineStatementLexer.java:543)
	at org.jdbi.v3.core.internal.lexer.DefineStatementLexer.mTokens(DefineStatementLexer.java:1116)
	at org.antlr.runtime.Lexer.nextToken(Lexer.java:89)
	... 33 more
```

It looks like the DefineStatement `lexer grammar` is interpreting `startDt<now()` as the start of a `<now()>` define, and then fails to match a closing `>`.  Classic `antlr3` bug :/
