### ISSUE TITLE
Incorrect handling of @UseStringTemplateSqlLocator

### ISSUE THREAD

**Issue by alexcase52** [jdbi/jdbi#1085]
jdbi 3.1.1

Hello, i have:

```
@UseStringTemplateSqlLocator`
interface ADao {
    @CreateSqlObject
    BDao internal();

    default void method() {
       internal().someMethod();
    }
}

interface BDao {
    @SqlQuery("...")
    List<String> someMethod();
}
```

I'm calling `ADao.method()` and get:

```
java.lang.RuntimeException: Unable to read StringTemplate group file at BDao.sql.stg on classpath
	at org.jdbi.v3.stringtemplate4.StringTemplateSqlLocator.readStringTemplateGroup(StringTemplateSqlLocator.java:145) ~[jdbi3-stringtemplate4-3.1.1.jar:3.1.1]
	at org.jdbi.v3.stringtemplate4.StringTemplateSqlLocator.lambda$findStringTemplateGroup$0(StringTemplateSqlLocator.java:134) ~[jdbi3-stringtemplate4-3.1.1.jar:3.1.1]
	at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324) ~[na:1.8.0_112]
	at org.jdbi.v3.stringtemplate4.StringTemplateSqlLocator.findStringTemplateGroup(StringTemplateSqlLocator.java:134) ~[jdbi3-stringtemplate4-3.1.1.jar:3.1.1]
	at org.jdbi.v3.stringtemplate4.StringTemplateSqlLocator.findStringTemplateGroup(StringTemplateSqlLocator.java:113) ~[jdbi3-stringtemplate4-3.1.1.jar:3.1.1]
	at org.jdbi.v3.stringtemplate4.internal.UseStringTemplateSqlLocatorImpl.lambda$configureForType$0(UseStringTemplateSqlLocatorImpl.java:35) ~[jdbi3-stringtemplate4-3.1.1.jar:3.1.1]
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.locateSql(CustomizingStatementHandler.java:175) ~[jdbi3-sqlobject-3.1.1.jar:3.1.1]
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:151) ~[jdbi3-sqlobject-3.1.1.jar:3.1.1]
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:26) ~[jdbi3-sqlobject-3.1.1.jar:3.1.1]
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:157) ~[jdbi3-sqlobject-3.1.1.jar:3.1.1]
	at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:23) ~[jdbi3-core-3.1.1.jar:3.1.1]
	at org.jdbi.v3.core.LazyHandleSupplier.lambda$invokeInContext$1(LazyHandleSupplier.java:68) ~[jdbi3-core-3.1.1.jar:3.1.1]
	at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:23) ~[jdbi3-core-3.1.1.jar:3.1.1]
	at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:67) ~[jdbi3-core-3.1.1.jar:3.1.1]
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:156) ~[jdbi3-sqlobject-3.1.1.jar:3.1.1]
```

My understanding is that for `BDao` `@UseStringTemplateSqlLocator` shouldn't have any affect.

**Comment by alexcase52** [comment]
Found workaround - annotate `BDao` with
```
@UseAnnotationSqlLocator
@UseTemplateEngine(DefinedAttributeTemplateEngine.class)
```

**Comment by alexcase52** [comment]
Also if `interface BDao` is not `public interface BDao` I have
```
java.lang.IllegalAccessError: tried to access class BDao from class com.sun.proxy.$Proxy42
	at com.sun.proxy.$Proxy42.internal(Unknown Source) ~[na:na]
```

**Comment by alexcase52** [comment]
If BDao mixes methods with StringTemplate (.stg) and methods with `@SqlQuery("select...")` you have to put annotations `@UseStringTemplateSqlLocator` on methods.
```
@UseStringTemplateSqlLocator
@SqlQuery
List<Strting> some();
```

BTW - all this stuff was working fine in 2.6.

**Comment by qualidafial** [comment]
Everything you've posted is expected behavior in 3.x.

If you annotate a SQL Object _type_ with a configuring annotation like `@UseStringTemplateSqlLocator`, then every action through SQL Objects of that type (including `@CreateSqlObject` methods) will inherit that configuration. If your annotation does not strictly apply to every method, then the recommended usage is to apply that annotation only to those methods that need it.

Non-private SQL Object interfaces are not supported from 3.0.0. When we release 3.2.0 this restriction will be lifted.

**Comment by alexcase52** [comment]
> If you annotate a SQL Object type with a configuring annotation like @UseStringTemplateSqlLocator, then every action through SQL Objects of that type (including @CreateSqlObject methods) will inherit that configuration

This looks strange to me - why __composed__ internal DAO __inherits__ external object settings instead of sticking with its own defaults? That's counterintutive and violates the previous behavior.   Previous behaviour looks more logical. What is the benefit of that?

**Comment by stevenschlansker** [comment]
The jdib3 model is a stacked set of configurations.  Since you get a `BDao` as a child of the `ADao` context (that's what you explicitly asked for with `@CreateSqlObject`) you also get class-level `ADao` configuration.

If you don't want `ADao`'s configuration, then you shouldn't ask for a `BDao` instance through it -- just get it from the `Handle` directly.

**Comment by stevenschlansker** [comment]
In theory, we could add a value to `@CreateSqlObject(inherits=false)` to make this choice explicit.
I hesitate to do this because I see `@CreateSqlObject` as a bit of a wart, personally.  Why do you use it in the first place?  Is there something that you don't get by asking for your `BDao` from the `Handle` directly?

**Comment by alexcase52** [comment]
I bet - two primary use cases for me:

1. organizing complex transaction - when external DAO starts `@Transaction` and calls internal ones to perform several different tasks within single transaction. E.g. first I call "insert something" - one DAO, then I call another DAO which inserts another related object or e.g. logs insert operation, so these internal DAO-classes have different responsibilities. That was the recommended way in 2.6 I think;
2. wrapper DAO as DAO layer facade - I have low-level methods in DAO which I'd like to protect from accidental calls be mistake. In jdbi 2.6 I had DAO-classes and protection was simple via private/package-local methods. In 3.0 cause my DAO become interfaces and I use java 8, I'm using internal DAOs with `@CreateSqlObject` to protect this low-level methods.

These two approaches combine with each other very well.

I rarely use `Handle`s directly. To use `Handle` I will have to pass it into DAO method externally which looks not so elegant to me and I will have to explicitly care about closing them - which is potentially error prone. I look on `@CreateSqlObject` as a flavor of `@Inject` to compose DAO services whith each other. This behavior was in 2.6 - when `@CreateSqlObject` was independent entity - and it is more of expected kind, I think.

**Comment by alexcase52** [comment]
> The jdib3 model is a stacked set of configurations. Since you get a BDao as a child of the ADao context (that's what you explicitly asked for with `@CreateSqlObject`) you also get class-level ADao configuration.

I understand it is as a stacked and I expected to have another entry in the stack with each `@CreateSqlObject` :)

**Comment by qualidafial** [comment]
> I understand it as a stacked and I expected to have another entry in the stack with each @CreateSqlObject :)

You do get another entry in the stack--on top of the SQL Object that created it.

**Comment by qualidafial** [comment]
I understand the pain this causes but I don't think we can realistically change this behavior without breaking other folks' code.

I'd be +1 to add some clarification to the docs so people know what to expect when they use `@CreateSqlObject`, but I'm -1 to modifying existing behavior.

I also don't think `inherits = false` will work--at least not without some redesign of the internals of SQL Object. The `HandleSupplier` sent to `CreateSqlObjectHandler` will always have the config registry of the enclosing call.

**Comment by hgschmie** [comment]
Closing this issue. The annotation inheritance system now properly handles configuration propagation for `@CreateSqlObject` children, and the behavior of `@UseStringTemplateSqlLocator` is documented in the developer guide.

[Generated by AI]
