### ISSUE TITLE
Null enum field is not working in Derby (Types.OTHER)

### ISSUE THREAD

**Issue by dcrn** [jdbi/jdbi#1120]
I'm using a bound bean with an enum value on it. Setting that enum value to null causes the exception below. This seems to be an issue with Derby (10.14.2.0), as I had no problems after trying it with H2.

```
org.jdbi.v3.core.statement.UnableToCreateStatementException: Exception while binding named parameter ...
	at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:67)
	at org.jdbi.v3.core.statement.ArgumentBinder.bind(ArgumentBinder.java:31)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1375)
	at org.jdbi.v3.core.result.ResultProducers.lambda$getGeneratedKeys$4(ResultProducers.java:108)
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:53)
	at org.jdbi.v3.core.result.ResultIterable.findFirst(ResultIterable.java:116)
	at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.mappedResult(ResultReturner.java:276)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$new$0(SqlUpdateHandler.java:56)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$configureReturner$3(SqlUpdateHandler.java:74)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:155)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.invoke(SqlUpdateHandler.java:30)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:158)
	at org.jdbi.v3.core.ConstantHandleSupplier.invokeInContext(ConstantHandleSupplier.java:52)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:157)
	at com.sun.proxy.$Proxy50.insert(Unknown Source)
	... <snip>
Caused by: java.sql.SQLFeatureNotSupportedException: The data type 'OTHER' is not supported.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.checkForSupportedDataType(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.setNull(Unknown Source)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setNull(HikariProxyPreparedStatement.java)
	at org.jdbi.v3.core.argument.NullArgument.apply(NullArgument.java:37)
	at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:64)
	... 26 more
Caused by: ERROR 0A000: The data type 'OTHER' is not supported.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 35 more
```

**Comment by qualidafial** [comment]
Out of the box, Jdbi uses `Types.OTHER` as the data type for any nulls it doesn't know the type for. Not all drivers support this--some accept `Types.NULL` even though `NULL` is a value constant, not a type constant.

You can override this using the `Arguments.setUntypedNullArgument()` configuration:

```java
jdbi.getConfig(Arguments.class).setUntypedNullArgument(new NullArgument(Types.NULL));
```

Try adding the above line to your Jdbi setup code and see if it helps.

**Comment by dcrn** [comment]
Yep, that did it. Thanks.

**Comment by dcrn** [comment]
Sorry, looks like I spoke too soon. I must have made a mistake while testing the above.
Derby doesn't seem to support Types.NULL either.

```
Caused by: org.jdbi.v3.core.statement.UnableToCreateStatementException: <snip>
	at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:67)
	at org.jdbi.v3.core.statement.ArgumentBinder.bind(ArgumentBinder.java:31)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1375)
	at org.jdbi.v3.core.result.ResultProducers.lambda$getGeneratedKeys$4(ResultProducers.java:108)
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:53)
	at org.jdbi.v3.core.result.ResultIterable.findFirst(ResultIterable.java:116)
	at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.mappedResult(ResultReturner.java:276)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$new$0(SqlUpdateHandler.java:56)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$configureReturner$3(SqlUpdateHandler.java:74)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:155)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.invoke(SqlUpdateHandler.java:30)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:158)
	at org.jdbi.v3.core.ConstantHandleSupplier.invokeInContext(ConstantHandleSupplier.java:52)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:157)
	at com.sun.proxy.$Proxy50.insert(Unknown Source)
	... 28 more
Caused by: java.sql.SQLFeatureNotSupportedException: The data type '0' is not supported.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.checkForSupportedDataType(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.setNull(Unknown Source)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setNull(HikariProxyPreparedStatement.java)
	at org.jdbi.v3.core.argument.NullArgument.apply(NullArgument.java:37)
	at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:64)
	... 42 more
Caused by: ERROR 0A000: The data type '0' is not supported.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 51 more
```

**Comment by qualidafial** [comment]
What is the data type in question?

**Comment by stevenschlansker** [comment]
And, what is the right way to bind null enums in Derby?  I skimmed the documentation but didn't see any clear answer.

**Comment by dcrn** [comment]
We actually moved to h2 because of this issue, but I took a look at Derby. Looks like they just use the original column type with setNull.

https://github.com/apache/derby/blob/cc457a99b575db678e490cfb1c916100bae31dd7/java/org.apache.derby.tests/org/apache/derbyTesting/functionTests/tests/jdbcapi/PrepStmtNullTest.java

**Comment by qualidafial** [comment]
If the argument type is known, you can pass this to `SqlStatement.bindByType()` which usually avoids the untyped null problem.

**Comment by TheRealMarnes** [comment]
If I understand correctly, this problem is resolved? You can either bind your nulls dynamically any way you want for each binding, leave it to any of the argument factories, or finally leave it to the catch-all... Aside from that, I don't think we promise full out-of-the-box support derby support like we do with h2.
