### ISSUE TITLE
How to return uuid when adding records

### ISSUE THREAD

**Issue by kkrgwbj** [jdbi/jdbi#1136]
```java
public String saveOrder(Handle handle, GBOrder gbOrder) {
        return handle.
                createUpdate("INSERT INTO `order` (`order_id`,`name`, `telephone`, `car_id`, `order_time`, `update_time`, `order_status`, `pay_status`, `amount`, `pay_type`, `stage_type`, `franc_id` ) VALUES ( UUID(),:name, :telephone, :carId, now(), NULL, '1', '1', '1', '分期', :stageType, :francId )")
                .bindBean(gbOrder).executeAndReturnGeneratedKeys("order_id").mapTo(String.class).findOnly();
    }

```java
java.lang.IllegalStateException: No element found in 'only'

	at org.jdbi.v3.core.result.ResultIterable.findOnly(ResultIterable.java:99)
	at com.myc.groupbuy.core.gborder.dao.GBOrderDao.saveOrder(GBOrderDao.java:43)

**Comment by kkrgwbj** [comment]
database:mysql
this column is primary key. 
but use mybatis it works well

**Comment by stevenschlansker** [comment]
Does adding the `RETURNING` clause help, or yield a different error?

**Comment by kkrgwbj** [comment]
@stevenschlansker mysql is not support RETURNING.Have you studied the implementation of mybatis?
@qualidafial

**Comment by stevenschlansker** [comment]
No, I have not studied the implementation of mybatis.  Reading mysql docs, https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-usagenotes-last-insert-id.html, it seems that an `AUTO_INCREMENT` column should be available as a generated key.  It's possible the driver doesn't understand the column name -- you could also try omitting `"order_id"` as a parameter to `executeAndReturnGeneratedKeys` and see if that helps.
