### ISSUE TITLE
JDBI broken with Spring managed transaction

### ISSUE THREAD

**Issue by mdeinum** [jdbi/jdbi#1211]
JDBI doesn't work (anymore?) with Spring with a Spring managed transaction and thus connection. I noticed this while preparing a sample with JDBI and Spring Boot 2.0.  

```
@Override
@Transactional
public Optional<Order> findById(String id) {
    return jdbi.withHandle(handle ->
           handle.createQuery("SELECT id, amount FROM orders WHERE id=:id")
                   .bind("id", id).mapTo(Order.class).findFirst());
}
```

This will eventually fail with an 

```
Caused by: org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is java.sql.SQLException: Connection is closed
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:332) ~[spring-jdbc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:746) ~[spring-tx-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714) ~[spring-tx-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:532) ~[spring-tx-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:304) ~[spring-tx-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at biz.deinum.orders.JdbiOrderRepository$$EnhancerBySpringCGLIB$$f2d08f3a.findAll(<generated>) ~[classes/:na]
	at biz.deinum.orders.OrderJdbiApplication$1.run(OrderJdbiApplication.java:43) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	... 5 common frames omitted
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:490) ~[HikariCP-2.7.9.jar:na]
	at com.sun.proxy.$Proxy57.commit(Unknown Source) ~[na:na]
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:368) ~[HikariCP-2.7.9.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java) ~[HikariCP-2.7.9.jar:na]
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:329) ~[spring-jdbc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	... 15 common frames omitted
```

The `Handle`s ` close method will be closed and it will always either `rollback` or `close` the connection. What it should do is only close the statements etc. and leave the connection untouched as Spring will handle that. 

I did try to use the `CMTTransactionHandler` however this only handles to no rollback case. The closing of the connection is still not prohibited with this. 

This fact makes JDBI unusable in a Spring application which uses Spring managed transactions.

**Comment by alwins0n** [comment]
it does not make sense to me why this would not work. but anyway, if time permits I will finish my rework on the jdbi3-spring4 plugin which makes handle a transactional resource in spring. you can lookup the details in #989 also clone it and try your sample out with the `JdbiTemplate` class.

The plugin should fully support spring5 which is packaged in spring boot 2.0 - and hopefully resolve any issues you are currently having

**Comment by hgschmie** [comment]
we shipped spring5 a while back, closing this, please reopen if that behavior still persists. a test would be great.
