### ISSUE TITLE
Nested bean requires at least one column in all result sets

### ISSUE THREAD

**Issue by strmer15** [jdbi/jdbi#1212]
JDBI version: 3.4.0

Currently, if you add the ```@Nested``` annotation for an 'inner' bean in the 'outer' bean class, then issue a query against the outer bean that doesn't include any columns for the inner bean in the result set, the BeanMapper complains that there are no matching columns in the result set.  This seems to be because the 'columnNames' passed into the specialize0 method are expected to be empty if there are no mappers found, but the column names from the query are passed down to the nested bean mapper, even if none of them apply.

It seems like if the nested bean has no columns on the result set to map to it, the nested property should be ignored instead of having an exception thrown.  Perhaps the specialize0 method should exit early if no mappers are found for a nested bean (by providing some additional context to the method when called from an outer bean mapper)?

Example Bean:

```
public class Child {

    private Long id;
    private String comment;
    private Parent parent;

    @ColumnName("ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ColumnName("COMMENT")
    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Nested("p")
    public Parent getParent() {
        return parent;
    }

    public void setParent(Parent order) {
        this.parent = order;
    }
}
```

```
public class Parent {

    private Long id;
    private String name;
    private Set<Child> children = Sets.newLinkedHashSet();

    @ColumnName("ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ColumnName("NAME")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<Child> getChildren() {
        return children;
    }

    public void setChildren(Set<Child> children) {
        this.children = children;
    }
}
```

Query:

```SELECT ID, COMMENT FROM CHILD WHERE ID = :id```

This query throws:

```
java.lang.IllegalArgumentException: Mapping bean type class com.rw.arcus.example.model.Parent didn't find any matching columns in result set
! at org.jdbi.v3.core.mapper.reflect.BeanMapper.specialize0(BeanMapper.java:182)
! at org.jdbi.v3.core.mapper.reflect.BeanMapper.specialize0(BeanMapper.java:174)
! at org.jdbi.v3.core.mapper.reflect.BeanMapper.specialize(BeanMapper.java:125)
! at org.jdbi.v3.core.result.ResultSetResultIterator.<init>(ResultSetResultIterator.java:38)
! at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:53)
! at org.jdbi.v3.core.result.ResultIterable.findFirst(ResultIterable.java:116)
! at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.mappedResult(ResultReturner.java:276)
! at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:54)
! at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:155)
! at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:26)
! at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:158)
! at org.jdbi.v3.core.ConstantHandleSupplier.invokeInContext(ConstantHandleSupplier.java:52)
! at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:157)
! at com.sun.proxy.$Proxy150.find(Unknown Source)
```

The workaround for this seems to be that I have to specify the foreign key to the Parent class in the result set somewhere, using the prefix.  So, this query works where the other one failed:

```SELECT ID, COMMENT, PARENT as p_ID FROM CHILD WHERE ID = :id```

But this would require including all nested beans in the result set somewhere, even for larger, more complex business models, for example when a one-to-one or many-to-one relationship is defined at deeper than 1 level (e.g. child -> parent -> grandparent -> great-grandparent, etc.).  At that point, every query against Child would have to JOIN the other tables or else return dummy values as placeholders.

**Comment by qualidafial** [comment]
I think you've made a good argument to elide nested mapping if _no_ columns match the prefix for a given property.

For now: try calling `getConfig(ReflectionMappers.class).setStrictMatching(false)` as a workaround and see if that helps.

**Comment by strmer15** [comment]
@qualidafial I already have that property set, no luck there - looks like the BeanMapper will only check that config value if it finds unmatched columns after all the mapping finishes.

I'd be glad to put together a pull request to fix this - not sure what you think the best approach would be here, either to filter the list of columns to send to the nested mapper or just add in a check against the 'strictMatching' config before throwing this error, some combination of the two, or something different.

**Comment by qualidafial** [comment]
If you'd like to take a stab at a PR that would be great.

I'm not sure there's a way to say "none of the columns match the prefix", since we're using `ColumnNameMatcher` to match up result set column names to Java names. That interface only does matches with the entire name, we have no flexible way to say "no columns start with this prefix" that complies with whatever column name matches people might have configured.

Instead, I think we should make `BeanMapper.specialize0()` accept a `boolean nested` parameter.

When we get to that check for matched columns, and didn't find any mappers:
* If nested, then return `(r, c) -> null` as a mapper.
* Otherwise, throw the exception

**Comment by qualidafial** [comment]
We should make similar changes to ConstructorMapper and FieldMapper too.

**Comment by qualidafial** [comment]
@strmer15 Please take a look at #1227, and leave a comment to tell us whether it solves your problem.
