### ISSUE TITLE
Problem with jdbi and enum

### ISSUE THREAD

**Issue by szymonlipinski** [jdbi/jdbi#1218]
Hi,

For an enum like:

```
enum class UserPermission(val permission: String) {

    A("a"), 
    B("b"), 
    C("c")

}
```

and a query:

```
import org.jdbi.v3.sqlobject.statement.SqlQuery
import org.jdbi.v3.sqlobject.customizer.Bind

@SqlQuery("""
    SELECT permission::text as name
    FROM user_permission
    WHERE user_id = :user_id AND active
    ORDER BY 1
""")
fun allPermissions(@Bind("user_id") userId: String ): List<UserPermission>
```

I get this:

```
java.lang.IllegalArgumentException: Cannot reflectively create enum objects

	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at kotlin.reflect.jvm.internal.FunctionCaller$Constructor.call(FunctionCaller.kt:65)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod(KCallableImpl.kt:148)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at org.jdbi.v3.core.kotlin.KotlinMapper$specialize0$1.map(KotlinMapper.kt:100)
	at org.jdbi.v3.core.result.ResultSetResultIterator.next(ResultSetResultIterator.java:83)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at org.jdbi.v3.core.result.ResultIterator.forEachRemaining(ResultIterator.java:40)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:198)
	at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.result(ResultReturner.java:158)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:42)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:155)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:25)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:162)
	at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:73)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:161)
	at com.sun.proxy.$Proxy14.allPermissions(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$null$0(OnDemandExtensions.java:60)
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:464)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$create$1(OnDemandExtensions.java:57)
	at com.sun.proxy.$Proxy14.allPermissions(Unknown Source)
```

**Comment by FredDeschenes** [comment]
Yeah this part is a little weird and not super clear in the documentation, but JDBI only registers column mappers for enum types, not row mappers (which you would need in that case).

You can either : 
* Write your own RowMapper:
```
class UserPermissionMapper: RowMapper<UserPermission> {
    override fun map(rs: ResultSet, ctx: StatementContext): UserPermission {
        return UserPermission.valueOf(rs.getString(1))
    }
}
...
@RegisterRowMapper(UserPermissionMapper::class)
fun allPermissions(@Bind("user_id") userId: String ): List<UserPermission>
```
* Return a list of `String`s and map them yourself:
```
fun allPermissions(@Bind("user_id") userId: String ): List<String>
...
dao.allPermissions(userId).map { UserPermission.valueOf(it) }
```
* Wrap your return value so that the built-in ColumnMapper can be used:
```
data class PermissionEntry(val permission: UserPermission)
...
fun allPermissions(@Bind("user_id") userId: String ): List<PermissionEntry>
```

**Comment by qualidafial** [comment]
> Yeah this part is a little weird and not super clear in the documentation, but JDBI only registers column mappers for enum types, not row mappers (which you would need in that case).

If a row mapper is registered for a given type, that mapper will have precedence. If no row mapper is registered for a type, only then do we search for a column mapper.

The problem is that `KotlinMapperFactory` is casting too wide of a net: https://github.com/jdbi/jdbi/blob/master/kotlin/src/main/kotlin/org/jdbi/v3/core/kotlin/KotlinMapperFactory.kt#L28-L29

We should restrict that factory to return a mapper only for data and value classes, or at least explicitly exclude enum classes.

**Comment by FredDeschenes** [comment]
> If a row mapper is registered for a given type, that mapper will have precedence. If no row mapper is registered for a type, only then do we search for a column mapper.

Oh I wasn't aware of that, good to know!

I'll push a PR to just block enums from being processed by the `KotlinMapper` as I think switching it to handle only data classes will probably break for some people (although it could be done for a major release).
