### ISSUE TITLE
No row mapper registered for class java.lang.String (Kotlin typing apparently incompatible with JoinRowMapper ?)

### ISSUE THREAD

**Issue by reubenfirmin** [jdbi/jdbi#1230]
From my understanding, the following (simplistic example) should be a valid way to set up a JoinRowMapper. 

```
    fun testJoinRow(): Map<String, Int> {
        val map = HashMap<String, Int>()
        querier.testJoinRow().forEach {
            map[it[String::class.java]] = it[Int::class.java]
        }
        return map
    }

...

        @SqlQuery(""" SELECT md5(random()::text), a.* FROM (select * from generate_series(1, 10)) a; """)
        @RegisterJoinRowMapper(String::class, Int::class)
        fun testJoinRow(): Stream<JoinRow>
```

However, when I run this, I get:

```
java.lang.IllegalArgumentException: No row mapper registered for class java.lang.String

	at org.jdbi.v3.core.mapper.JoinRowMapper.lambda$specialize$0(JoinRowMapper.java:51)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.jdbi.v3.core.mapper.JoinRowMapper.specialize(JoinRowMapper.java:51)
	at org.jdbi.v3.core.result.ResultSetResultIterator.<init>(ResultSetResultIterator.java:38)
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:53)
	at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:141)
...
```

The obvious culprit seems to be `@RegisterJoinRowMapper(String::class, Int::class)` - I cannot find a way to make this consume types declared as class.java. 

However, rewriting as the following, which uses java types consistently, also fails:

```
    fun testJoinRow(): Map<String, Int> {
        val map = HashMap<String, Int>()

        this.dbi.withHandle<List<JoinRow>, RuntimeException> {
            it.registerRowMapper(JoinRowMapper.forTypes(String::class.java, Int::class.java))
            it.select("SELECT md5(random()::text), a.* FROM (select * from generate_series(1, 10)) a; ")
                    .mapTo(JoinRow::class.java)
                    .list()
        }.forEach {
            map[it[String::class.java]] = it[Int::class.java]
        }
        return map
    }
```

also fails with the same exception.

**Comment by qualidafial** [comment]
JoinRowMapper only works with row-mapped types--that is, types that come from more than one column. String and Integer are column-mapped types.

In your case, it might be simpler to use Map mapping: http://jdbi.org/#_map_k_v_results

```kotlin
@SqlQuery("""select key, value from mytable""")
@KeyColumn("key")
@ValueColumn("value")
fun testMap(): Map<String, Int>
```

**Comment by reubenfirmin** [comment]
Thanks for the map example, that's helpful.

I was simplifying slightly in my example - what we're actually producing is a guava Table structure (K1 -> K2 -> V) - "average per user per event_type". In our case, the value is an object with a strong type, but K1 and K2 are both String. Is JoinRowMapper a good fit for this or is there an alternate approach that'd work better?

**Comment by stevenschlansker** [comment]
`JoinRowMapper` operates effectively on a tuple of Java types.  So if you have a Java type for `K1` and `K2`, then it can fit your needs.  But that involves writing value types and not using `String` as you do now.

So it's probably not right for your use case.  I would suggest writing a 'result row' type that you can return from your dao, something like:
```java
class EventAverageRow {
    String k1, k2;
    double v;
}

GuavaTableBuilder<String, String, Double> resultBuilder = ...;
it.select("SELECT K1, K2, V ...")
   .mapTo(EventAverageRow.class)
   .forEach(row -> resultBuilder.add(row.k1, row.k2, row.v));
return resultBuilder.build();
```

**Comment by reubenfirmin** [comment]
Hope you don't mind my following up here, since we have a thread going on the topic. (I'll go to the mailing first on subsequent topics).

I put together a prototype along the rowreducer approach:

```
        @SqlQuery("""
        WITH users AS (SELECT md5(random()::text) as user_id, a.* FROM (select * from generate_series(1, 10)) a),
        questions AS (SELECT md5(random()::text) as question_text, a.* FROM (select * from generate_series(1, 5)) a)
        select user_id, question_text, random() as average, random()::integer as count FROM users, questions
        """)
        @UseRowReducer(UserQuestionRowReducer::class)
        fun testTable(): Map<String, LinkedList<QuestionAverage>>

        class UserQuestionRowReducer : LinkedHashMapRowReducer<String, LinkedList<QuestionAverage>> {
            override fun accumulate(container: MutableMap<String, LinkedList<QuestionAverage>>, rowView: RowView) {
                val user = rowView.getColumn("user_id", String::class.java)
                val question = rowView.getColumn("question_text", String::class.java)
                val average = rowView.getRow(Average::class.java)
                // TODO there's probably a more kotlin way of doing it
                if (!container.containsKey(user)) {
                    container[user] = LinkedList<QuestionAverage>()
                }
                container[user]!!.add(QuestionAverage(question, average))
            }
        }

        data class QuestionAverage(val question: String, val average: Average)
        data class Average(val average: Double, val count: Int)
```

When I run this I get:

```
java.lang.ClassCastException: java.util.LinkedList cannot be cast to java.util.Map$Entry

	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.reducedResult(ResultReturner.java:273)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:48)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:155)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:26)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:163)
```

Am I using it wrongly?
