### ISSUE TITLE
What is the jdbi3 eqivivalent of jdbi2 BinderFactory?

### ISSUE THREAD

**Issue by qwelyt** [jdbi/jdbi#1301]
I'm trying to move from jdbi2 to jdbi3 but I'm stumped on how to migrate our `BinderFactory` mappings.

As per http://jdbi.org/jdbi2/sql_object_api_argument_binding/ we can specify our own `BinderFactory` when we have an object that we want to bind in some specific way. As far as I can tell, `BinderFactory` has been removed from jdbi3 (and jdbi3 sqlobjects).

Given this code as an example

```java
@BindingAnnotation(BindSomething.SomethingBinderFactory.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.PARAMETER})
public @interface BindSomething { 
  public static class SomethingBinderFactory implements BinderFactory {
    public Binder build(Annotation annotation) {
      return new Binder<BindSomething, Something>()  {
        public void bind(SQLStatement q, BindSomething bind, Something arg)  {
          q.bind("id", arg.getId());
          q.bind("name", arg.getName());
        }
      };
    }
  }
}


public static interface BindSomethingExample {
  @SqlUpdate("insert into something (id, name) values (:id, :name)")
  void insert(@BindSomething Something s);
}
```

How would I go about doing this in JDBI3?

If there is a tutorial somewhere, I would gladly follow it. But I don't seem to be able to find any. http://jdbi.org/#_binding_arguments seems to be the closes, but it only deals with the "fluent" style.  
The migration "guide" ( http://jdbi.org/#_upgrading_from_v2_to_v3 ) doesn't mention the removal of `BinderFactory` either.

**Comment by TheRealMarnes** [comment]
If you look at e.g. BindBean or BindList, you can follow their trail into SqlStatementCustomizerFactory instances:
```
@Override
public SqlStatementParameterCustomizer createForParameter(Annotation annotation,
                                                          Class<?> sqlObjectType,
                                                          Method method,
                                                          Parameter param,
                                                          int index,
                                                          Type type) {
    BindBean bind = (BindBean) annotation;
    return (stmt, bean) -> {
        String prefix = bind.value();
        if (prefix.isEmpty()) {
            stmt.bindBean(bean);
        } else {
            stmt.bindBean(prefix, bean);
        }
    };
}
```

Are these the lines of code you are looking for? 👋

**Comment by TheRealMarnes** [comment]
No no, I meant to point out you can create your own custom binding annotations _like_ BindBean, BindList, etc but with a different subject datatype and whatever special binding logic you need. Keep your `@BindSomething` but move the logic you have in there to a SqlStatementCustomizerFactory instance that you refer to with an annotation on your BindSomething class.

You are using an IDE and can inspect the sourcecode of library classes in your project, right? Literally just take a look at our BindBean class in your project's artifacts and mimick what it does. You only need to create your annotation, put a SqlStatementCustomizingAnnotation on it, and use it to refer to an implementation class where you put the binding logic you've shown here.

**Comment by qwelyt** [comment]
Oh! Misunderstood you completely.

I gave it a shot but seem to fail miserably.  
I took a look at `Bind{Bean|BeanList|List|Map|Methods}` and their factories and tried to do something like them. I can't say I understood what it is they are doing though.

What I came up with was this
```java
  @Retention(RetentionPolicy.RUNTIME)
   @Target({ElementType.PARAMETER})
   @SqlStatementCustomizingAnnotation(BindEvent.BindEventFactory.class)
   @interface BindEvent {
      class BindEventFactory implements SqlStatementCustomizerFactory {
         public SqlStatementParameterCustomizer createForParameter(final Annotation annotation, final Class<?> sqlObjectType, final Method method, final Parameter param, final int index, final Type paramType) {
            return (q, arg) -> {
               final DomainEvent event = (DomainEvent) event;
               q.bind("event_id", event.id().toString());
               q.bind("aggregate_id", event.aggregateId().toString());
               // ....
            }
         }
     }
   }
```
I tried a few different alternatives, but no matter what I've tried I always get
```exception
java.lang.UnsupportedOperationException: Not supported for parameter
	at org.jdbi.v3.sqlobject.customizer.SqlStatementCustomizerFactory.createForParameter(SqlStatementCustomizerFactory.java:66)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.lambda$eachParameterCustomizers$5(CustomizingStatementHandler.java:98)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.eachParameterCustomizers(CustomizingStatementHandler.java:99)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.lambda$parameterCustomizers$4(CustomizingStatementHandler.java:89)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
```

How are you actually supposed to do it?

**Comment by TheRealMarnes** [comment]
The exception you're getting is the default impl of the interface. Somehow your override method (you should always put `@Override` on overridden methods btw) isn't being called, just the interface default body.

Try moving your BindEventFactory to an upper-level class of its own instead of a nested class. It really should work then, as far as I can see.

**Comment by qwelyt** [comment]
Now we are getting somewhere!

Sorry, the `event` variable-line should have been ` final DomainEvent event = (DomainEvent) arg;`, so casting the `arg` to the object I'm getting my data from.

I moved `BindEventFactory` out a level.
Also overrode the method, though my IDE indicated that I was already overriding the method. But your right, you should always annotate it.
```java
   @Retention(RetentionPolicy.RUNTIME)
   @Target({ElementType.PARAMETER})
   @SqlStatementCustomizingAnnotation(BindEventFactory.class)
   @interface BindEvent {
   }
   class BindEventFactory implements SqlStatementCustomizerFactory {
      @Override
      public SqlStatementParameterCustomizer createForParameter(final Annotation annotation, final Class<?> sqlObjectType, final Method method, final Parameter param, final int index, final Type paramType) {
         return (q, arg) -> {
            final DomainEvent event = (DomanEvent) arg;
            q.bind("timestamp", LocalDateTime.now().toString());
             // ....
         };
      }
   }
```

And now I get a different Exception
```
java.lang.IllegalStateException: unable to instantiate sql statement customizer factory
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.instantiateFactory(CustomizingStatementHandler.java:142)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.lambda$eachParameterCustomizers$5(CustomizingStatementHandler.java:98)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.eachParameterCustomizers(CustomizingStatementHandler.java:99)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.lambda$parameterCustomizers$4(CustomizingStatementHandler.java:89)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.<init>(CustomizingStatementHandler.java:73)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.<init>(SqlUpdateHandler.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jdbi.v3.sqlobject.SqlMethodHandlerFactory.buildHandler(SqlMethodHandlerFactory.java:68)
	at org.jdbi.v3.sqlobject.SqlMethodHandlerFactory.lambda$buildHandler$2(SqlMethodHandlerFactory.java:57)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
```

Tried to add the default constructor to `BindEventFactory` just to be extra explicit, even though the compiler adds it by itself. But no luck. Still the same exception.

Tried to make `BindEventFactory` public instead of package-private, still the same exception.

Tried to add `String value() default "";` to the `BindEvent` interface, just to be more like `BindBean` and the like. Still the same error. (Grasping at straws here)

If I add breakpoints where I catch the exception that tries to execute the statement, the `cause` I see `java.lang.NoSuchMethodException: path.to.my.Binder$BindEventFactory.<init>()`

If I break out the `BindEvent` interface and the `BindEventFactory` to their own respective files, I'm back to the `UnsupportedOperationException: Not supported for parameter`.

**Comment by TheRealMarnes** [comment]
I'll make some time tonight (in an hour or 5, 6) to recreate your situation and get hands-on with this problem. I don't immediately see what's going wrong here.

**Comment by stevenschlansker** [comment]
I think you must have cut off the actual cause from the exception message -- that exception is always caused by a ReflectiveOperationException that should describe the problem.
I suspect the type must be public so we can instantiate it.

Also note that generally you can make nested classes `static` and that's just as good as promoting it to a top level class.

**Comment by TheRealMarnes** [comment]
> must be public

Ack, can't believe I missed that :) Yeah that must be it

**Comment by qwelyt** [comment]
> type must be public

Which "type" are you referring to?  
If you mean my `DomainEvent`, it is public. I had a private default constructor, removed it, but still get the same Exception.

The Exception is not cut of.
```java
try {
    queryInterface.save("mytable", event); // Breakpoint added here
} catch (final Exception e) { // Posting exact stack trace from this exception
    e.printStackTrace(); 
}
```

```
java.lang.UnsupportedOperationException: Not supported for parameter
	at org.jdbi.v3.sqlobject.customizer.SqlStatementCustomizerFactory.createForParameter(SqlStatementCustomizerFactory.java:66)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.lambda$eachParameterCustomizers$5(CustomizingStatementHandler.java:98)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.eachParameterCustomizers(CustomizingStatementHandler.java:99)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.lambda$parameterCustomizers$4(CustomizingStatementHandler.java:89)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.<init>(CustomizingStatementHandler.java:73)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.<init>(SqlUpdateHandler.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jdbi.v3.sqlobject.SqlMethodHandlerFactory.buildHandler(SqlMethodHandlerFactory.java:68)
	at org.jdbi.v3.sqlobject.SqlMethodHandlerFactory.lambda$buildHandler$2(SqlMethodHandlerFactory.java:57)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.jdbi.v3.sqlobject.SqlMethodHandlerFactory.buildHandler(SqlMethodHandlerFactory.java:58)
	at org.jdbi.v3.sqlobject.Handlers.lambda$findFor$0(Handlers.java:56)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.jdbi.v3.sqlobject.Handlers.findFor(Handlers.java:57)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.buildMethodHandler(SqlObjectFactory.java:133)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$9(SqlObjectFactory.java:125)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$methodHandlersFor$10(SqlObjectFactory.java:125)
	at java.util.Map.computeIfAbsent(Map.java:957)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.methodHandlersFor(SqlObjectFactory.java:106)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.attach(SqlObjectFactory.java:83)
	at org.jdbi.v3.core.extension.Extensions.lambda$findFor$0(Extensions.java:70)
	at java.util.Optional.map(Optional.java:215)
	at org.jdbi.v3.core.extension.Extensions.findFor(Extensions.java:70)
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:436)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$create$2(OnDemandExtensions.java:61)
	at com.sun.proxy.$Proxy10.save(Unknown Source)
	at path.to.my.SqlStore.save(SqlStore.java:117)
```

I'll see if I can put up an example project that demonstrates the problem if that would help.

**Comment by TheRealMarnes** [comment]
>  Not supported for parameter

This exception means your factory doesn't override the createForParameter
method of SqlStatementCustomizerFactory.

The type that must be public is BindEventFactory and its default
constructor. Jdbi needs to be able to create an instance of the class you
link to in your annotation to be able to call its methods. For good
measure, try making the annotation public too and see.

Yes, putting a full code sample up here would be helpful.
--
Marnick "with ck, 3 capitals, and an apostrophe" L'Eau

**Comment by qwelyt** [comment]
ooookey. This is super strange. I created an example project to show the error. Like with any good test I wrote the code that I knew would generate the error. But the code works... The code that I posted in https://github.com/jdbi/jdbi/issues/1301#issuecomment-436219008 works without throwing any exceptions at all. And I can't for the life of me figure out why.

I tried running my real project with the same code, and it works. Not longer the exceptions I got yesterday, even though I haven't changed the code.  
Sometimes I hate computers... Or at least stuff that breaks "sometimes".

Anyway, thanks very much for your help!

I do have one request though, if possible.  
```java
         @Override
         public SqlStatementParameterCustomizer createForParameter(final Annotation annotation, final Class<?> sqlObjectType, final Method method, final Parameter param, final int index, final Type paramType) {
            return (q, arg) -> {
               final Event event = (Event) arg;
```
This cast is not very nice. Could `arg` become typed in a later release? I think changing
```java
public interface SqlStatementParameterCustomizer {
    void apply(SqlStatement<?> stmt, Object arg) throws SQLException;
}
```
To
```java
public interface SqlStatementParameterCustomizer<T> {
    void apply(SqlStatement<?> stmt, T arg) throws SQLException;
}
```
would be enough.  
I might do a pull-request if you prefer that.

**Comment by TheRealMarnes** [comment]
Hmm, I don't think we should do that. It would create a false sense of security and hide a risk the user should be aware of, namely the cast which is necessary because we lose the type information no matter what. Nothing can stop you from making your BindEvent's implementation generic for Event and then putting it on a param of any other type. Jdbi shouldn't pretend to be able to safely give you a T when that isn't what happens in reality. The Object param isn't nice to users, I agree, but it is technically the correct thing to do, the right representation of the situation.

**Comment by qwelyt** [comment]
I opened a pull request so the discussion, if there would be any, could be moved there.

**Comment by qwelyt** [comment]
It is. Thank you for all the help!

**Comment by stevenschlansker** [comment]
Glad this got worked out.
