### ISSUE TITLE
BOM is incompatible with Spring Boot 2.1

### ISSUE THREAD

**Issue by ivandeskov** [jdbi/jdbi#1340]
Hi guys,

I've just started exploring jdbi and it's a great library, thanks very much for your efforts!

I noticed a problem when using the bom with Spring Boot 2.1. Boot is bringing Spring 5.1.2 in and jdbi3-parent has declared Spring v4.2.4 in its dependency management section, so I ended up with spring-core and spring-context 4.2.4 on my classpath

The issue is that spring-context 4.2.4 is incompatible with boot 2.1 and this causes the following error at startup:

> Exception in thread "main" java.lang.AbstractMethodError: org.springframework.boot.context.config.ConfigFileApplicationListener.supportsSourceType(Ljava/lang/Class;)Z
	at org.springframework.context.event.GenericApplicationListenerAdapter.supportsSourceType(GenericApplicationListenerAdapter.java:79)
	at org.springframework.context.event.AbstractApplicationEventMulticaster.supportsEvent(AbstractApplicationEventMulticaster.java:282)
	at org.springframework.context.event.AbstractApplicationEventMulticaster.retrieveApplicationListeners(AbstractApplicationEventMulticaster.java:214)
	at org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:185)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:125)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.aexp.rcomply.rcomplyapi.CaiapiApplication.main(CaiapiApplication.java:11)

Please let us know if I can provide any further information about this.

Thanks!

**Comment by TheRealMarnes** [comment]
Can you try explicitly setting the spring version in your pom.xml to 5.1.2 so that it overrides jdbi's dependency and check if everything still works that way?

**Comment by ivandeskov** [comment]
What I did was I stopped using the jdbi bom and manage the jdbi modules I need manually.

The error would appear regardless of whether one is using the spring integration module or not. It's more to do with the fact that the dependency management in jdbi-parent conflicts with the dependency management from spring boot.

**Comment by TheRealMarnes** [comment]
Hmm, I'm not very experienced with boms. You can't manually override a version defined by a bom?

**Comment by TheRealMarnes** [comment]
Hmm, I'm not very experienced with boms. You can't manually override a version defined by a bom?

**Comment by ivandeskov** [comment]
I'd think that would be possible if you declare the dependency version in the dependency management section of your project's pom. But that would also mean you're overriding the version coming from spring boot which I would prefer not to do.

**Comment by TheRealMarnes** [comment]
Understandable. Glad you got it working anyway. I don't think there's anything we should or can do, so shall we close this?

**Comment by TheRealMarnes** [comment]
I might add a doc note :)

**Comment by qualidafial** [comment]
An explicit managed dependency will always win over a managed dependency brought in through a BOM:

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.jdbi</groupId>
      <artifactId>jdbi3-bom</artifactId>
      <version>3.5.1</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-jdbc</artifactId>
      <version>5.1.3.RELEASE</version>
    </dependency>
  </dependencies>
</dependencyManagement>
