### ISSUE TITLE
Extension not found when using Kotlin

### ISSUE THREAD

**Issue by KristianSelnas** [jdbi/jdbi#1383]
I have been trying to use SQL Objects in a Kotlin project, but keep getting exceptions I'm not experiencing when using Java. I have created two minimal examples illustrating the problem, one with Java and one with Kotlin. The two are as similar as possible. The Java version works like a charm, but the Kotlin version yields the following exception:
```
org.jdbi.v3.core.extension.NoSuchExtensionException: Extension not found: interface com.example.demo.repository.ThingDao
	at org.jdbi.v3.core.Jdbi.lambda$withExtension$9(Jdbi.java:437) ~[jdbi3-core-3.3.0.jar:3.3.0]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_111]
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:437) ~[jdbi3-core-3.3.0.jar:3.3.0]
	at com.example.demo.repository.ThingRepository.getThings(ThingRepository.kt:11) ~[classes/:na]
	at com.example.demo.api.ThingController.things(ThingController.kt:12) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
```
Is this a problem with my setup or a JDBI bug?

My examples can be found here:
* [Java example](https://github.com/KristianSelnas/jdbi-java-example)
* [Kotlin example](https://github.com/KristianSelnas/jdbi-kotlin-example)

Any help is greatly appreciated. Thanks!

**Comment by TheRealMarnes** [comment]
I don't know kotlin, but can you make ThingDao `public` like in java?

**Comment by qualidafial** [comment]
It sounds like you haven't installed the plugins for SQL Object and/or Kotlin:

```kotlin
Jdbi jdbi = ...
jdbi.installPlugin(SqlObjectPlugin())
    .installPlugin(KotlinPlugin())
    .installPlugin(KotlinSqlObjectPlugin())
```

**Comment by TheRealMarnes** [comment]
Well he got the last 2, but yeah, not the base SqlObjectPlugin

**Comment by KristianSelnas** [comment]
Thank you guys! Adding the SqlObjectPlugin actually solves the problem. The docs are not clear on this. I thought the KotlinSqlObject plugin did the same in Kotlin as the SqlObjectPlugin in Java. The fact that you need both is not very intuitive.

**Comment by qualidafial** [comment]
Sorry for the confusion. The Kotlin SQL object plugin just tweaks SQL Object to play nice with Kotlin, but it's not a replacement for installing the SQL Object plugin.
