### ISSUE TITLE
Built-in transaction handler causes ClassCastException when an Error is thrown

### ISSUE THREAD

**Issue by rherrmann** [jdbi/jdbi#1405]
The transaction handler causes a `ClassCastException` if an `Error` is thrown while executing the transaction.

If , for example, the template engine throws an error like so:

```java
jdbi.setTemplateEngine((sql, ctx) -> {
  throw new Error();
});
```

the error isn't propagated but causes this exception instead:

```
java.lang.ClassCastException: java.lang.Error cannot be cast to java.lang.Exception
	at org.jdbi.v3.core.transaction.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:145)
	at org.jdbi.v3.core.transaction.SerializableTransactionRunner.inTransaction(SerializableTransactionRunner.java:54)
	at org.jdbi.v3.core.Handle.inTransaction(Handle.java:393)
	at org.jdbi.v3.core.Jdbi.lambda$inTransaction$5(Jdbi.java:353)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:318)
	at org.jdbi.v3.core.Jdbi.inTransaction(Jdbi.java:353)
```

**Comment by stevenschlansker** [comment]
I'm not able to reproduce this exact class cast exception (I think the code has changed since) but I added a test case and improved our handling in #1411

**Comment by rherrmann** [comment]
Just for the record, the class cast exception occurred with v3.5.1 where the exception handling in `inTransaction` tried to cast the caught `Throwable` to the declared exception of type `X`.

The code looked like this:
```java
<R, X extends Exception> R inTransaction(...) {
  try {
    // execute callback
  } catch (Throwable e) {
    // rollback
    throw (X) e;
  }
}
```
Everything other than `Exception` (or descendants) would be 'hidden' by the class cast exception.

Thanks for your quick response and for this neat and useful library!

**Comment by rherrmann** [comment]
Thanks again for the prompt fix! The new version solves the problem.

For reference, this is the test case I used:
```java
@Test
public void useTransactionPropagatesError() {
  Handle handle = Jdbi.open("URL to test database");
  HandleConsumer<RuntimeException> badCallback = h -> {
    throw new AssertionError("BAD");
  };

  Throwable thrown = catchThrowable(() -> handle.useTransaction(badCallback));

  assertThat(thrown).isInstanceOf(AssertionError.class);
}
```
