### ISSUE TITLE
Incompatibility between v2 and v3 when using superfluous parameters map

### ISSUE THREAD

**Issue by sarxos** [jdbi/jdbi#1418]
Hello @jdbi Team :)

In JDBI v2 we were using construction like this:

```java
@SqlQuery("SELECT COUNT(*) FROM account a WHERE <where>")
int count(@Define("where") String where, @BindMap Map<String, Object> params);
```

The `where` is being build in runtime. In some cases it's empty (simply `1 = 1`) and in some cases it contains some values provided by user on GUI filter. For example:

```sql
SELECT COUNT(*) FROM account a WHERE 1 = 1;
```
With:
```
where = '1 = 1'
params = { }
```
Or:
```sql
SELECT COUNT(*) FROM account a WHERE 1 = 1 AND a.status = :status;
```
With:

```
where = '1 = 1 AND a.status = :status'
params = { status = 2 }
```

Right now, when empty `params` argument is provided, this throws an exception. For example:

```plain
com.vividgames.swim.akka.exception.MessageProcessingException: org.jdbi.v3.core.statement.UnableToCreateStatementException: Superfluous named parameters provided while the query declares none: '{positional:{}, named:{}, finder:[{}]}'. [statement:"SELECT count(*) FROM test t WHERE <where>", rewritten:"/* templated */ SELECT count(*) FROM test t WHERE value > 0", parsed:"ParsedSql{sql='/* CountDao.count */ SELECT count(*) FROM `dev-abc.1`.test t WHERE value > 0', parameters=ParsedParameters{positional=false, parameterNames=[]}}", arguments:{positional:{}, named:{}, finder:[{}]}]
	at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:58)
	at org.jdbi.v3.core.statement.ArgumentBinder.bind(ArgumentBinder.java:29)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1429)
	at org.jdbi.v3.core.result.ResultProducers.lambda$getResultSet$2(ResultProducers.java:68)
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:53)
	at org.jdbi.v3.core.result.ResultIterable.findFirst(ResultIterable.java:116)
	at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.mappedResult(ResultReturner.java:266)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:54)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:155)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:26)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:163)
	at org.jdbi.v3.core.ConstantHandleSupplier.invokeInContext(ConstantHandleSupplier.java:52)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:162)
```

I found a flag in `SqlStatements` which can be used to [allow unused bindings](https://github.com/jdbi/jdbi/blob/96d95bda61cf4c107e83816486a9364fcf96982a/core/src/main/java/org/jdbi/v3/core/statement/SqlStatements.java#L226):

```plain
/**
 * Sets whether or not an exception should be thrown when any arguments are given to a query but not actually used in it. Unused bindings tend to be bugs or oversights, but can also just be convenient. Defaults to false: unused bindings are not allowed.
 *
 * @see org.jdbi.v3.core.argument.Argument
 */
public SqlStatements setUnusedBindingAllowed(boolean allowUnusedBindings) {
    this.allowUnusedBindings = allowUnusedBindings;
    return this;
}
```

But I cannot find any way to use this method :( In JDBI source code I found only usages, but no place where it's being set.

I can rewrite our DAOs and introduce new methods which takes no `params`, e.g.:

```java
@SqlQuery("SELECT COUNT(*) FROM account a")
int countAll();

@SqlQuery("SELECT COUNT(*) FROM account a WHERE <where>")
int countFiltered(@Define("where") String where, @BindMap Map<String, Object> params);
```

But this would have to be done in a number of existing DAOs and to be honest I would rather like to change one line and magically make it work again.

**Comment by TheRealMarnes** [comment]
You'll have to set the flag on the Jdbi/Handle that creates the SqlObject.

```
jdbi.useHandle(h -> {
    Dao dao = h.configure(SqlStatements.class, stmts -> stmts.setUnusedBindingAllowed(true))
        .attach(Dao.class);
});
```

As far as I remember, there's no statement customizing annotation to do it. Could easily be contributed if you really want it.

**Comment by sarxos** [comment]
Hi @TheRealMarnes,

Your code works perfectly :) Thank you!

I think this could be described in a JDBI documentation available from www, or in `setUnusedBindingAllowed` javadoc (because these were the first places where I started looking on how to use it).

I don't know how to edit documentation, but I can update javadoc if you like.

**Comment by TheRealMarnes** [comment]
I think you're missing the bigger picture. The `handle.configure` thing is standard for all configuration (along with `getConfig`), it's not something special just for this. `allowUnusedBindings` takes a boolean, and with just that it should be pretty obvious. Calling the method and how it propagates follows our standard configuration paradigm.

**Comment by sarxos** [comment]
Well, indeed, it seems I missing it, but the other users are probably missing it as well. It looks to me as quite advanced and kind of a _tribal_ knowledge obvious for core developers but not as obvious for us here in a wild. After you describe it as a _standard configuration paradigm_ I went do JDBI documentation, and after reading it in regards to configuration stuff, I still have just a brief idea how it works. The `configure` method is used only once in regards to setting `TupleMappers` of Vavr.

It's a part of a bigger issue with not all features described in doc in enough details, but we, a JDBI users, are here to help pointing what is missing and help filling the gaps.

Therefore, I propose to change javadoc to contain more details, e.g.:

```java
/**
 * Sets whether or not an exception should be thrown when any arguments are
 * given to a query but not actually used in it. Unused bindings tend to be bugs or
 * oversights, but can also just be convenient. Defaults to false: unused bindings 
 * are not allowed.<br>
 * <br>
 * It can be changed by configuring {@link Configurable} object (e.g. {@link Jdbi}
 * or {@link Handle}), for example:
 * <pre>
 * handle.configure(SqlStatements.class, s -> s.setUnusedBindingAllowed(true))
 * </pre>
 *
 * @see org.jdbi.v3.core.argument.Argument
 * @see Handle.configure
 * @see Jdbi.configure
 */
```

I will gladly add it, but please let me know if what I wrote is ok.

**Comment by TheRealMarnes** [comment]
> tribal knowledge obvious for core developers but not as obvious for us here in a wild

I'd just like to point out I'm a core member since only like 2 months and I was just a regular user like yourself for over a year before then, so it's not like I'm savvy on the arcane knowledge. 😛 I know most things I know about jdbi by being in your same situation and just exploring and clicking-through on the API and interfaces, letting intellij hint methods at me and such.

But yes, it should be clearly documented because we can't expect everyone to inspect jdbi's internals to figure out basic usage. :)

I don't think we'll be adding the javadoc the way you suggest though. The config mantra should be dcoumented in its own right, not repeated on every single config setting or included on any one particularly chosen config setting. Each config setting should explain its own effects only.

**Comment by stevenschlansker** [comment]
We have a section on `JdbiConfig`: http://jdbi.org/#_jdbiconfig but it's more focused on making your own implementations.  Maybe we should add a "config from the user's perspective" section in the docs in an earlier section?  Would that address this need better?

**Comment by sarxos** [comment]
I was reading through `JdbiConfig` and I was under the same impression. Things cleared after @TheRealMarnes gave me an example he provided in the comment.

Thank you for the `@AllowUnusedBindings` :)

**Comment by TheRealMarnes** [comment]
I agree with that much, the exception itself should hint at it.

**Comment by sarxos** [comment]
@TheRealMarnes hint added in https://github.com/jdbi/jdbi/pull/1428

**Comment by sarxos** [comment]
Thank you Steven! Take care :)
