### ISSUE TITLE
Occasional "SQLException: No parameters defined during prepareCall()" from onDemand SqlObject on query

### ISSUE THREAD

**Issue by eric** [jdbi/jdbi#150]
I've noticed an occasional exception that I have trouble making sense of.

The `SQLException: No parameters defined during prepareCall()` exception sounds like no parameter was defined, but the outer exception does list an argument for `id`: `arguments:{ positional:{}, named:{id:540333}, finder:[]}`.

Am I doing something wrong? I've seen that the `SqlObject` from `onDemand()` is supposed to be threadsafe. Is there something that I can do to help track down what is causing this issue?

Here's the exception:

```
! org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: Exception while binding 'id' [statement:"SELECT id, col1, col2 FROM tbl WHERE id = :id", located:"SELECT id, col1, col2 FROM tbl WHERE id = :id", rewritten:"SELECT id, col1, col2 FROM tbl WHERE id = ?", arguments:{ positional:{}, named:{id:540333}, finder:[]}]
! at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter$MyRewrittenStatement.bind(ColonPrefixNamedParamStatementRewriter.java:165) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1318) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at org.skife.jdbi.v2.Query.fold(Query.java:173) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at org.skife.jdbi.v2.Query.first(Query.java:273) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at org.skife.jdbi.v2.sqlobject.ResultReturnThing$SingleValueResultReturnThing.result(ResultReturnThing.java:112) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:48) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:45) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:175) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at org.skife.jdbi.v2.sqlobject.SqlObject$1.intercept(SqlObject.java:75) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$9e7b5fcf.findById(<generated>) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at n.tbl.dbi.DbiManager$$anonfun$createRecord$1$$anonfun$apply$3.apply(DbiManager.scala:52) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at n.tbl.dbi.DbiManager$$anonfun$createRecord$1$$anonfun$apply$3.apply(DbiManager.scala:51) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$5.block(ExecutionContextImpl.scala:48) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:2803) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at scala.concurrent.package$.blocking(package.scala:50) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at n.tbl.dbi.DbiManager$$anonfun$createRecord$1.apply(DbiManager.scala:50) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at n.tbl.dbi.DbiManager$$anonfun$createRecord$1.apply(DbiManager.scala:50) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
Caused by: ! java.sql.SQLException: No parameters defined during prepareCall()
! at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at com.mysql.jdbc.ServerPreparedStatement.getBinding(ServerPreparedStatement.java:867) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at com.mysql.jdbc.ServerPreparedStatement.setLong(ServerPreparedStatement.java:1943) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.setLong(PreparedStatementJavassistProxy.java) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at org.skife.jdbi.v2.LongArgument.apply(LongArgument.java:40) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
! at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter$MyRewrittenStatement.bind(ColonPrefixNamedParamStatementRewriter.java:162) ~[n-8e7e0e1bac07680bdf5377a1fbcb0c689d82ccc8.jar:na]
!... 24 common frames omitted
```

Here's what the code looks like:

``` scala
  val queries = dbi.onDemand(classOf[TblQueries])

  // ...

  def find(id: Long): Future[Option[Tbl]] = {
    Future {
      blocking {
        queries.find(id)
      }
    }
  }
```

``` scala
@RegisterMapper(Array(classOf[TblMapper]))
trait TblQueries {
  @SqlQuery("SELECT id, col1, col2 FROM tbl WHERE id = :id")
  @SingleValueResult(classOf[Tbl])
  def find(@Bind("id") id: Long): Option[Tbl]
}
```

**Comment by stevenschlansker** [comment]
Have you considered creating a separate TblQueries instance per thread (sharing the same DBI is fine), and seeing if that fixes your problem?  Would help figure out if this is a threading issue or not.

**Comment by eric** [comment]
I had not. If the `onDemand()` call isn't thread safe, I can just handle that manually, I just wasn't sure if I was using it as intended.

**Comment by stevenschlansker** [comment]
I'm not sure either, it was just a guess.  Just trying to rule out possibilities because I don't have any clue what's going on :)

Do you happen to have a runnable test case?

**Comment by eric** [comment]
I don't. It's something that just happens in production very sporadically.

**Comment by stevenschlansker** [comment]
Closing due to inactivity.  Feel free to reopen if you have additional information
