### ISSUE TITLE
Exception while binding named parameter of type java.util.List

### ISSUE THREAD

**Issue by NaumGj** [jdbi/jdbi#1512]
JDBI 3.3.0 probably has a bug while binding named parameters of type java.util.List.

I have a REST API service that should insert a _comparison_ into a PostgreSQL table. The _comparisons_ table is created on application startup by executing the following SQL statement:
```sql
CREATE TABLE IF NOT EXISTS TEST_SCHEMA.COMPARISONS(
  ID SERIAL PRIMARY KEY,
  EXECUTION_TIMESTAMP TIMESTAMP WITH TIME ZONE,
  STRING_LIST VARCHAR[]
);
```

The problematic column for insertions into this table would be _STRING_LIST_.  To insert a _comparison_ into the table, a _ComparisonData_ bean is populated. The attributes of the _ComparisonData_ bean are identical to the columns of the database table:
```java
public class ComparisonData {
    private Integer comparisonId;
    private OffsetDateTime executionTimestamp;
    private List<String> stringList;
}
```
The _stringList_ attribute is populated from the request body of the API call:
```java
public Response handleRequest(@NotNull @Valid ComparisonRequest comparisonRequest) {
    ComparisonData comparisonData = ComparisonData.builder()
            .executionTimestamp(OffsetDateTime.now())
            .stringList(comparisonRequest.getStringList())
            .build();

    Jdbi jdbi = jdbiFactory.getJdbiForDB();
    try (Handle handle = jdbi.open()) {
        ComparisonDao comparisonDao = handle.attach(ComparisonDao.class);
        int comparisonId = comparisonDao.insertComparison(comparisonData);
        return Response.ok().status(Response.Status.CREATED).entity(comparisonId).build();
    }
}
```

_comparisonData_ is binded into the SQL statement as a bean. The _ComparisonDao_ class is defined as follows:
```java
@UseClasspathSqlLocator
public interface ComparisonDao {

    @SqlUpdate
    @GetGeneratedKeys
    int insertComparison(@BindBean("cmp") ComparisonData comparisonData);
}
```
and the corresponding SQL file for the _insertComparison()_ method is a simple INSERT statement:
```sql
INSERT INTO TEST_SCHEMA.COMPARISONS (EXECUTION_TIMESTAMP, STRING_LIST)
VALUES (:cmp.executionTimestamp, :cmp.stringList)
```

The _insertComparison()_ method fails **only the second time** it is executed, stating that it cannot bind the named parameter _cmp.stringList_:
```
org.jdbi.v3.core.statement.UnableToCreateStatementException: Exception while binding named parameter 'cmp.stringList'
[statement:"INSERT INTO TEST_SCHEMA.COMPARISONS (EXECUTION_TIMESTAMP, STRING_LIST) VALUES (:cmp.executionTimestamp, :cmp.stringList) ",
rewritten:"INSERT INTO TEST_SCHEMA.COMPARISONS (EXECUTION_TIMESTAMP, STRING_LIST) VALUES (:cmp.executionTimestamp, :cmp.stringList) ",
parsed:"ParsedSql{sql='INSERT INTO TEST_SCHEMA.COMPARISONS (EXECUTION_TIMESTAMP, STRING_LIST) VALUES (?, ?) ', parameters=ParsedParameters{positional=false,
parameterNames=[cmp.executionTimestamp, cmp.stringList]}}",
arguments:{ positional:{}, named:{},
finder:[{lazy bean property arguments "ComparisonData(comparisonId=null, executionTimestamp=2019-04-23T13:41:26.721+02:00, stringList=[string1, string2, string3])"]}]
```

I use a JDBC connection pool defined as a Glassfish resource. The application does not hold or cache any state that would cause the binding to fail. If I catch the thrown exception (the exception is thrown only once, i.e. on the second execution of the _insertComparison()_ method) and reexecute the _insertComparison_ method with the same:
```java
int comparisonId;
try {
    comparisonId = comparisonDao.insertComparison(comparisonData);
} catch (UnableToCreateStatementException e) {
    comparisonId = comparisonDao.insertComparison(comparisonData);
}
```
... the insertion in the catch block succeeds. I checked the _comparisonData_ bean that is binded and its _stringList_ attribute, but there is nothing strange about them. The fact that the insertion succeeds with exactly the same parameter makes me think that there is a bug in the list binding.

I would be happy to receive feedback from you regarding the issue.

**Comment by TheRealMarnes** [comment]
> INSERT INTO TEST_SCHEMA.COMPARISONS (EXECUTION_TIMESTAMP, STRING_ARRAY)

It was first called `STRING_LIST` not `STRING_ARRAY`, is that just copypasta garble or are we looking at a false trail?

The other thing that comes to mind is a race condition in your table creation, similar to how I once had some concurrent code that had a transaction race despite one transaction explicitly being opened before the other, but it turned out the tx would not be started by the until you actually executed a statement inside it.

If neither of those, I see nothing fishy in your code so I'm gonna go ahead and agree this might need investigation by us.

3.3.0 is an old version of jdbi by now though, could you update to the latest (3.7.1, I think) and see what that does?

**Comment by qualidafial** [comment]
Can you give more of the whole stack trace--including the `Caused by` sections?

**Comment by NaumGj** [comment]
It should be STRING_LIST everywhere, I changed the name in between. Sorry about that, I fixed it now.

I was able to circumvent the problem by disabling statement caching in the connection pool. This is my connection pool now:
```
<jdbc-connection-pool name="ComparisonConnectionPool"
                          datasource-classname="${db.driver}"
                          res-type="javax.sql.DataSource"
                          transaction-isolation-level="read-committed"
                          non-transactional-connections="true"
                          connection-validation-method="meta-data"
                          statement-cache-size="0"
                          steady-pool-size="2"
                          max-pool-size="10">
```
The exception is thrown for every statement-cache-size>=2. I am still puzzled why the exception was thrown only the second time.

Here is the whole stacktrace:
```
[2019-04-23T16:22:31.974+0200] [] [SEVERE] [] [fish.payara.microprofile.opentracing.jaxrs.JaxrsContainerRequestTracingFilter] [tid: _ThreadID=29 _ThreadName=http-thread-pool::http-listener(1)] [timeMillis: 1556029351974] [levelValue: 1000] [[
  org.jdbi.v3.core.statement.UnableToCreateStatementException: Exception while binding named parameter 'cmp.stringList' [statement:"INSERT INTO TEST_SCHEMA.COMPARISONS (EXECUTION_TIMESTAMP, STRING_LIST) VALUES (:cmp.executionTimestamp, :cmp.stringList) ", rewritten:"INSERT INTO TEST_SCHEMA.COMPARISONS (EXECUTION_TIMESTAMP, STRING_LIST) VALUES (:cmp.executionTimestamp, :cmp.stringList) ", parsed:"ParsedSql{sql='INSERT INTO TEST_SCHEMA.COMPARISONS (EXECUTION_TIMESTAMP, STRING_LIST) VALUES (?, ?) ', parameters=ParsedParameters{positional=false, parameterNames=[cmp.executionTimestamp, cmp.stringList]}}", arguments:{ positional:{}, named:{}, finder:[{lazy bean property arguments "ComparisonData(comparisonId=null, executionTimestamp=2019-04-23T16:22:31.952+02:00, stringList=[string1, string2, string3])"]}]
org.jdbi.v3.core.statement.UnableToCreateStatementException: Exception while binding named parameter 'cmp.stringList' [statement:"INSERT INTO TEST_SCHEMA.COMPARISONS (EXECUTION_TIMESTAMP, STRING_LIST) VALUES (:cmp.executionTimestamp, :cmp.stringList) ", rewritten:"INSERT INTO TEST_SCHEMA.COMPARISONS (EXECUTION_TIMESTAMP, STRING_LIST) VALUES (:cmp.executionTimestamp, :cmp.stringList) ", parsed:"ParsedSql{sql='INSERT INTO TEST_SCHEMA.COMPARISONS (EXECUTION_TIMESTAMP, STRING_LIST) VALUES (?, ?) ', parameters=ParsedParameters{positional=false, parameterNames=[cmp.executionTimestamp, cmp.stringList]}}", arguments:{ positional:{}, named:{}, finder:[{lazy bean property arguments "ComparisonData(comparisonId=null, executionTimestamp=2019-04-23T16:22:31.952+02:00, stringList=[string1, string2, string3])"]}]
        at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:67)
        at org.jdbi.v3.core.statement.ArgumentBinder.bind(ArgumentBinder.java:31)
        at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1375)
        at org.jdbi.v3.core.result.ResultProducers.lambda$getGeneratedKeys$4(ResultProducers.java:108)
        at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:53)
        at org.jdbi.v3.core.result.ResultIterable.findFirst(ResultIterable.java:116)
        at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.mappedResult(ResultReturner.java:266)
        at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$new$0(SqlUpdateHandler.java:56)
        at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$configureReturner$3(SqlUpdateHandler.java:74)
        at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:155)
        at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.invoke(SqlUpdateHandler.java:30)
        at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:158)
        at org.jdbi.v3.core.ConstantHandleSupplier.invokeInContext(ConstantHandleSupplier.java:52)
        at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:157)
        at com.sun.proxy.$Proxy319.insertComparison(Unknown Source)
        at com.bmw.psmg.hub.dqstais.mtvn.comparison_util.control.ComparisonUtilResourceImpl.insertComparison(ComparisonUtilResourceImpl.java:48)
        at com.bmw.psmg.hub.dqstais.mtvn.comparison_util.control.ComparisonUtilResourceImpl$Proxy$_$$_WeldSubclass.insertComparison$$super(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
        at org.hibernate.validator.cdi.internal.interceptor.ValidationInterceptor.validateMethodInvocation(ValidationInterceptor.java:79)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
        at com.bmw.psmg.hub.dqstais.mtvn.comparison_util.control.ComparisonUtilResourceImpl$Proxy$_$$_WeldSubclass.insertComparison(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:704)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:258)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:755)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:575)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Connection closed
        at com.sun.gjc.spi.base.ConnectionHolder.checkValidity(ConnectionHolder.java:766)
        at com.sun.gjc.spi.jdbc40.ConnectionHolder40.createArrayOf(ConnectionHolder40.java:454)
        at org.jdbi.v3.core.array.SqlArrayArgument.apply(SqlArrayArgument.java:53)
        at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:64)
        ... 88 more
]]
```

**Comment by TheRealMarnes** [comment]
> Caused by: java.sql.SQLException: Connection closed

Well there's your problem, I guess.

**Comment by NaumGj** [comment]
You are probably right.

A developer should not be aware whether a connection from the connection pool was caching prepared statements, but was then closed. Anyway, this is not a JDBI issue, so I'm closing the ticket. Thank you for the support.

**Comment by qualidafial** [comment]
No problem. Let us know what solution you settle on.

**Comment by stevenschlansker** [comment]
Server side prepared statements can interact poorly with connection pooling, for example: https://pgbouncer.github.io/faq.html#how-to-use-prepared-statements-with-transaction-pooling

**Comment by NaumGj** [comment]
Since our application is not database-intensive, we decided not to invest more time into debugging and disabled statement caching.
