### ISSUE TITLE
Corrupted 2.60 build

### ISSUE THREAD

**Issue by pierre** [jdbi/jdbi#152]
It looks like `org/skife/jdbi/cglib/` hasn't been included in the 2.60 jar.

Previous `maven-shade-plugin` logs:

```
[INFO] --- maven-shade-plugin:2.3:shade (default) @ jdbi ---
[INFO] Including cglib:cglib-nodep:jar:3.1 in the shaded jar.
[INFO] Including com.fasterxml:classmate:jar:0.9.0 in the shaded jar.
[INFO] Including org.antlr:antlr-runtime:jar:3.4 in the shaded jar.
[INFO] Excluding antlr:antlr:jar:2.7.7 from the shaded jar.
[INFO] Excluding log4j:log4j:jar:1.2.17 from the shaded jar.
[INFO] Excluding org.springframework:spring:jar:2.0.1 from the shaded jar.
[INFO] Excluding commons-logging:commons-logging:jar:1.1.1 from the shaded jar.
[INFO] Excluding org.slf4j:slf4j-api:jar:1.7.10 from the shaded jar.
[INFO] Excluding org.antlr:stringtemplate:jar:3.2.1 from the shaded jar.
```

New `maven-shade-plugin` logs:

```
[INFO] --- maven-shade-plugin:2.3:shade (default) @ jdbi ---
[INFO] Excluding cglib:cglib:jar:3.1 from the shaded jar.
[INFO] Excluding org.ow2.asm:asm:jar:5.0.2 from the shaded jar.
[INFO] Including com.fasterxml:classmate:jar:1.1.0 in the shaded jar.
[INFO] Including org.antlr:antlr-runtime:jar:3.4 in the shaded jar.
[INFO] Excluding antlr:antlr:jar:2.7.7 from the shaded jar.
[INFO] Excluding log4j:log4j:jar:1.2.17 from the shaded jar.
[INFO] Excluding org.springframework:spring:jar:2.0.1 from the shaded jar.
[INFO] Excluding commons-logging:commons-logging:jar:1.1.1 from the shaded jar.
[INFO] Excluding org.slf4j:slf4j-api:jar:1.7.10 from the shaded jar.
[INFO] Excluding org.antlr:stringtemplate:jar:3.2.1 from the shaded jar.
```

**Comment by natnan** [comment]
yep; this is what I get on a simple dao test:
Should be related to #144 
```
java.lang.NoClassDefFoundError: org/skife/jdbi/cglib/proxy/Callback
	at org.skife.jdbi.v2.sqlobject.SqlObjectBuilder.onDemand(SqlObjectBuilder.java:66)
	at org.skife.jdbi.v2.DBI.onDemand(DBI.java:350)
	at test.dao.DaoTest.test(DaoTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: org.skife.jdbi.cglib.proxy.Callback
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more
```

**Comment by stevenschlansker** [comment]
Gaaaaah :(

**Comment by arteam** [comment]
In 2.61 fixed that, but now ASM dependency is required
````
java.lang.NoClassDefFoundError: org/objectweb/asm/Type
	at org.skife.jdbi.cglib.core.TypeUtils.parseType(TypeUtils.java:184)
	at org.skife.jdbi.cglib.core.KeyFactory.<clinit>(KeyFactory.java:66)
	at org.skife.jdbi.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
	at org.skife.jdbi.v2.sqlobject.SqlObject.buildSqlObject(SqlObject.java:57)
	at org.skife.jdbi.v2.sqlobject.SqlObjectBuilder.attach(SqlObjectBuilder.java:38)
	at org.skife.jdbi.v2.BasicHandle.attach(BasicHandle.java:408)
````

**Comment by arteam** [comment]
Thanks, @stevenschlansker! 2.62 works fine.

**Comment by stevenschlansker** [comment]
Thank goodness.
