### ISSUE TITLE
How to insert Postgresql JSONB data type using SQL Objects

### ISSUE THREAD

**Issue by yunspace** [jdbi/jdbi#157]
We have a table defined as:
```
CREATE TABLE threads
(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(21) NOT NULL,
    acl JSONB NOT NULL
);
```
And the corresponding DAO method using `SQL Objects`:

    @SqlUpdate("insert into threads (name, acl) values (:name, :acl)")
    void insert(@Bind("name") String name, @Bind("acl") String acl);

We attempt to do the following insertion:

    dao.insert("name", "{}");

And we get the following exception:

````
org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: column "acl" is of type jsonb but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 87 [statement:"insert into threads (name, acl) values (:name, :acl)", located:"insert into threads (name, acl) values (:name, :acl)", rewritten:"/* ThreadDAO.insert */ insert into threads (name, acl, created, modified) values (?, ?)", arguments:{ positional:{}, named:{name:'myThreadName',acl:'{}'}, finder:[]}]
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1334)
	at org.skife.jdbi.v2.Update.execute(Update.java:56)
	at org.skife.jdbi.v2.sqlobject.UpdateHandler$2.value(UpdateHandler.java:62)
	at org.skife.jdbi.v2.sqlobject.UpdateHandler.invoke(UpdateHandler.java:75)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:175)
	at org.skife.jdbi.v2.sqlobject.SqlObject$1.intercept(SqlObject.java:75)
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$109c4e5a.insert(<generated>)
	at trunk.stream.db.jdbi.ThreadDAOTest.doStuff(ThreadDAOTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at 
````

However if I go to a SQL terminal and run the following command it works fine:

    INSERT INTO threads (name, acl) VALUES ('jsonb test', '{}');

We tried using `to_json()` casting but that gives us `json` not `jsonb`. We also tried casting using `:acl::jsonb` but Sql Object misinterprets that as a extra paramater. Please assist.

**Comment by christophercurrie** [comment]
This is a question that is more appropriate for [the mailing list](https://groups.google.com/forum/#!forum/jdbi).

Use the SQL standard cast syntax: `CAST(:acl as jsonb)`.

**Comment by yunspace** [comment]
Thanks for the suggestion. I will try it out. Will use mailing list next time.
