### ISSUE TITLE
SqlBatch automatic binding of nested data classes not working

### ISSUE THREAD

**Issue by Globegitter** [jdbi/jdbi#1631]
I am using jdbi version 3.10.1 and have a Dao and Configuration class like this:

```
interface ConfigurationDao : SqlObject {
    @SqlBatch
    @UseClasspathSqlLocator
    fun batchUpsert(tablets: Collection<Configuration>)
}

package self_service.domain

import org.jdbi.v3.core.mapper.Nested

data class Retailer(
    val name: String,
)

data class Configuration(
    val id: String,
    val retailer: Retailer
)

```

with a (simplified) `batchUpsert.sql` as follows:

```
INSERT INTO tablets
    (id, retailer_name)
    VALUES
    (:tablets.id, :tablets.retailer.name)
    ON CONFLICT (id) DO UPDATE SET
    (retailer_name) =
    (EXCLUDED.retailer_name)
```

And I create my jdbi instance as follows:

```
Jdbi.create(dataSource)
        .installPlugin(KotlinPlugin())
        .installPlugin(KotlinSqlObjectPlugin())
        .installPlugin(PostgresPlugin())
```

And when I try to use `batchUpsert` I get the following error:
```
java.lang.IllegalArgumentException: Mapping constructor-injected type TabletConfiguration matched columns for constructor parameters ... , but not for [parameter #x retailer of fun <init>(..., something.domain.Retailer): something.domain.Configuration]
        at org.jdbi.v3.core.kotlin.KotlinMapper.specialize0(KotlinMapper.kt:116)
        at org.jdbi.v3.core.kotlin.KotlinMapper.specialize(KotlinMapper.kt:73)
        at org.jdbi.v3.core.result.ResultSetResultIterator.<init>(ResultSetResultIterator.java:38)
        at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:54)
        at org.jdbi.v3.core.result.ResultIterable.iterator(ResultIterable.java:40)
        at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1155)
        at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1188)
        at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1179)
        at something.ConfigurationTest.getTablets(ConfigurationTest.kt:341)
        at something.ConfigurationTest.getTablets$default(ConfigurationTest.kt:333)
        at something.ConfigurationTest$4.invokeSuspend(ConfigurationTest.kt:66)
        at something.ConfigurationTest$4.invoke(ConfigurationTest.kt)
```

If I make the data class not nested or I add the `@Nested` annotation it works. But the readme about the `KotlinSqlObjectPlugin` states:

```
Parameter binding supports individual primitive types as well as Kotlin or JavaBean style objects as a parameter (referenced in binding as :paramName.propertyName). No annotations are needed.
```

So is there anything I am missing to get this to work without annotations?

**Comment by Globegitter** [comment]
One thing that I also just noticed, if I use the `@Nested` annotation I can have a nesting of one level, but if I than add another level of nesting it does not work. E.g.:

```
data class Address(
...
)

data class Retailer(
    val name: String,
   @Nested val address: Address
)
```

to extend the example above, it can bind the `:tablets.retailer.name` perfectly fine but it can not bind `:tablets.retailer.address.street`. If I inline address into retailer, so I have `:tablets.retailer.street` than it works fine. Is there anything I am missing here?

**Comment by Globegitter** [comment]
@stevenschlansker I am just noticing the question label but this was at least as much intended as a bug report or documentation issue.
