### ISSUE TITLE
Use of `UseStringTemplate3StatementLocator` does read and use STG file

### ISSUE THREAD

**Issue by ktalebian** [jdbi/jdbi#1636]
I'm using jDBI 2.78 with StringTemplate 3.2.1. Here is a simple DAO file I have

```java
package com.myapp.dao;

@UseStringTemplate3StatementLocator
@RegisterMapper(AccountsDaoMapper.class)
public interface AccountsDao {

  @SqlQuery
  List<AccountEntity> listPage(final String accountId);
}
```

I have made sure I have placed an `AccountsDao.sql.stg` at `resources/com/myapp/dao` and I simplified it to be:

```stg
group accounts;

listPage() ::= <<
SELECT * FROM accounts;
>>
```

When I run a query, I get 

```
org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'listPage' at line 1 [statement:"listPage", located:"listPage", rewritten:"/* AccounstDao.listPage */ listPage", arguments:{ positional:{}, named:{limit:0,accountId:'123'}, finder:[]}]
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1338)
	at org.skife.jdbi.v2.Query.fold(Query.java:173)
	at org.skife.jdbi.v2.Query.list(Query.java:82)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:253)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:46)
	at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:41)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:224)
	at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:133)
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$92dccbf.listPage(<generated>)
```

I tried putting a breakpoint on `UseStringTemplate3StatementLocator` file, and checked the `createForType` method. The `builder` has the correct `basePath` as my STG file. 

If I were to pass the query to the `SqlQuery` then it works. I don't know how else I can debug this and find out why this is not working.

**Comment by stevenschlansker** [comment]
Hi, unfortunately Jdbi 2 is very old and unlikely to receive feature enhancements like this.  Jdbi 3 supports at least basic usage of string template groups, so upgrading is the easiest forward.  

Otherwise we will accept community patches against Jdbi 2 but the main developers are unlikely to focus their time on the old code.  Thanks for understanding!

**Comment by stevenschlansker** [comment]
closing v2 issues, this works in v3
