### ISSUE TITLE
Multiple getters with the same name breaks @BindBean

### ISSUE THREAD

**Issue by ljl** [jdbi/jdbi#1642]
If you have a class with multiple getters with the same name but different method signature, it somehow breaks using JDBI 3.11.1.

Example:

Bean
```
public interface Order {
    int getId();
    LocalDate getDeliveryDate();
    OrderLine getOrderLineById(int id);
    OrderLine getOrderLineById(String id);
} 
```

Query
```
    @SqlBatch("UPDATE order SET deliveryDate = :deliveryDate WHERE id = :id")
    void updateDeliveryDate(@BindBean List<Order> orders);
```

Nullpointer exception is thrown in BeanPropertiesFactory because the descriptor in the following block has null for both getReadMethod and getWriteMethod
```
return QualifiedType.of((Type)Optional.ofNullable(this.descriptor.getReadMethod()).map(Method::getGenericReturnType).orElseGet(() -> { return this.descriptor.getWriteMethod().getGenericParameterTypes()[0];
```

Stacktrace:
```java.lang.NullPointerException
	at org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory$BeanPojoProperties$BeanPojoProperty.lambda$determineQualifiedType$3(BeanPropertiesFactory.java:154)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory$BeanPojoProperties$BeanPojoProperty.determineQualifiedType(BeanPropertiesFactory.java:154)
	at org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory$BeanPojoProperties$BeanPojoProperty.<init>(BeanPropertiesFactory.java:107)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory$BeanPojoProperties$PropertiesHolder.<init>(BeanPropertiesFactory.java:185)
	at org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory.lambda$static$0(BeanPropertiesFactory.java:51)
	at org.jdbi.v3.core.config.JdbiCaches.lambda$declare$0(JdbiCaches.java:49)
	at org.jdbi.v3.core.config.JdbiCaches$1.lambda$get$1(JdbiCaches.java:63)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.jdbi.v3.core.config.JdbiCaches$1.get(JdbiCaches.java:63)
	at org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory$BeanPojoProperties.getProperties(BeanPropertiesFactory.java:76)
	at org.jdbi.v3.core.argument.internal.NamedArgumentFinderFactory$Pojo.lambda$forPojoProps$2(NamedArgumentFinderFactory.java:63)
	at org.jdbi.v3.core.statement.ArgumentBinder$Prepared.lambda$prepareBinder$2(ArgumentBinder.java:205)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.jdbi.v3.core.statement.ArgumentBinder$Prepared.prepareBinder(ArgumentBinder.java:207)
	at org.jdbi.v3.core.statement.ArgumentBinder$Prepared.<init>(ArgumentBinder.java:190)
	at org.jdbi.v3.core.statement.PreparedBatch.internalBatchExecute(PreparedBatch.java:205)
	at org.jdbi.v3.core.statement.PreparedBatch.execute(PreparedBatch.java:105)```

**Comment by qualidafial** [comment]
Thanks for reporting this! `get` methods with arguments should not be recognized as bean property getters.
