### ISSUE TITLE
SqlBatch doesn't handle wildcard parameter types

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#1645]
From the mailing list,

```java
@SqlBatch("update "+TRAIN_ARTICLE_LABELS //
            + " set book_title=:value"
            + " where articleid=:key")    
    void setBookTitleTrainingData(@BindBean Iterable<? extends Entry<Integer,String>> forConversion);
```

causes

```
Exception in thread "main" java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135)
    at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.getParameterType(SqlBatchHandler.java:158)
```

**Comment by stevenschlansker** [comment]
https://github.com/jdbi/jdbi/commit/ff5771c9de4cca8461c0249c2670f79004ffdc08
