### ISSUE TITLE
IllegalAccessException: class is not public

### ISSUE THREAD

**Issue by radist-nt** [jdbi/jdbi#1684]
After migrating from jdbi2 to jdbi3, we found the problem with package-access beans.

Using package-access classes with @BindBean annotation in sql object leads to exception. Here is a part of stacktrace:

```
.....
Caused by: java.lang.reflect.UndeclaredThrowableException
	at f.q.p.$Proxy98.sqlMethodName(Unknown Source)
	at f.q.p.CallerCls.callerMethod(CallerCls.java:xxx)
	... 12 more
Caused by: java.lang.IllegalAccessException: class is not public: f.q.p.BeanClass.getBeanMethod()String/invokeVirtual, from org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory$BeanPojoProperties$BeanPojoProperty
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:850)
	at java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:1531)
	at java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:1469)
	at java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:1618)
	at java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:1612)
	at java.lang.invoke.MethodHandles$Lookup.unreflect(MethodHandles.java:1187)
	at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$function$4(Unchecked.java:76)
	at java.util.Optional.map(Optional.java:215)
	at org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory$BeanPojoProperties$BeanPojoProperty.<init>(BeanPropertiesFactory.java:116)
	at org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory$BeanPojoProperties$PropertiesHolder.lambda$new$1(BeanPropertiesFactory.java:192)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory$BeanPojoProperties$PropertiesHolder.<init>(BeanPropertiesFactory.java:193)
	at org.jdbi.v3.core.config.JdbiCaches.lambda$declare$0(JdbiCaches.java:49)
	at org.jdbi.v3.core.config.JdbiCaches$1.lambda$get$1(JdbiCaches.java:63)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.jdbi.v3.core.config.JdbiCaches$1.get(JdbiCaches.java:63)
	at org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory$BeanPojoProperties.getProperties(BeanPropertiesFactory.java:81)
	at org.jdbi.v3.core.argument.internal.PojoPropertyArguments.getValue(PojoPropertyArguments.java:51)
	at org.jdbi.v3.core.argument.internal.ObjectPropertyNamedArgumentFinder.find(ObjectPropertyNamedArgumentFinder.java:63)
	at org.jdbi.v3.core.statement.ArgumentBinder.lambda$bindNamed$1(ArgumentBinder.java:91)
	at org.jdbi.v3.core.statement.ArgumentBinder.lambda$wrapExceptions$6(ArgumentBinder.java:153)
	at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:103)
	at org.jdbi.v3.core.statement.ArgumentBinder.bind(ArgumentBinder.java:60)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1661)
	at org.jdbi.v3.core.result.ResultProducers.lambda$getResultSet$2(ResultProducers.java:67)
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:54)
	at org.jdbi.v3.core.result.ResultIterable.findFirst(ResultIterable.java:203)
	at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.mappedResult(ResultReturner.java:269)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:54)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:153)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:26)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.lambda$invoke$0(SqlObjectInitData.java:125)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
	at org.jdbi.v3.core.ConstantHandleSupplier.lambda$invokeInContext$0(ConstantHandleSupplier.java:56)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
	at org.jdbi.v3.core.ConstantHandleSupplier.invokeInContext(ConstantHandleSupplier.java:52)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.call(SqlObjectInitData.java:131)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.invoke(SqlObjectInitData.java:125)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$attach$2(SqlObjectFactory.java:110)
	... 14 more
```

The root of problem is call for MethodHandles.lookup() from BeanPropertiesFactory.BeanPojoProperties.BeanPojoProperty<T>. So, access rights checked from the BeanPojoProperty class. But more consistent way is to check access from the sql object's class.

**Comment by hgschmie** [comment]
Tracked in #2391, closing the issue here.
