### ISSUE TITLE
Cannot set null String value with Oracle Driver

### ISSUE THREAD

**Issue by helun** [jdbi/jdbi#17]
We are having a problem  inserting a null value with jdbi 2.32 and the oracle driver (ojdbc 14). 

org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: Exception while binding positional param at (0 based) position 2 [statement:"insert into eventLog (id, event, freeTextMessage, timestamp) values (?, ?, ?, current_date)", located:"insert into eventLog(id, event, freeTextMessage, timestamp) values (?, ?, ?, current_date)", rewritten:"insert into eventLog (id, event, freeTextMessage, timestamp) values (?, ?, ?, current_date)", arguments:{ positional:{0:e29269b6-4dd7-40c9-9af4-11092de27444,1:eventName,2:null}, named:{}, finder:[]}]

```
    at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter$MyRewrittenStatement.bind(ColonPrefixNamedParamStatementRewriter.java:123)
    at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1290)
    at org.skife.jdbi.v2.Update.execute(Update.java:57)
    at org.skife.jdbi.v2.BasicHandle.update(BasicHandle.java:278)
    at org.skife.jdbi.v2.BasicHandle.insert(BasicHandle.java:268)
    at myapp.dbi.DbiLogRepository.logEvent(DbiMigrationRepository.java:78)
    at 
```

Caused by: java.sql.SQLException: Invalid column type
        at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
        at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
        at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:208)
        at oracle.jdbc.driver.OracleStatement.getInternalType(OracleStatement.java:3433)
        at oracle.jdbc.driver.OraclePreparedStatement.setNullCritical(OraclePreparedStatement.java:4261)
        at oracle.jdbc.driver.OraclePreparedStatement.setNull(OraclePreparedStatement.java:4250)
        at org.skife.jdbi.v2.ObjectArgument.apply(ObjectArgument.java:43)
        at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter$MyRewrittenStatement.bind(ColonPrefixNamedParamStatementRewriter.java:120)
        ... 53 more

Here is the table definition:

CREATE TABLE eventLog
(
  id      VARCHAR2 (255) NOT NULL,
  event             VARCHAR2 (255) NOT NULL,
  freeTextMessage   VARCHAR2 (255),
  timestamp         DATE NOT NULL
);

**Comment by nitirajrathore** [comment]
Was this handled in Jdbi3? I am using Jdbi3 and facing the same problem that if some members of a bean are null then it is not able to insert those. 
Writing explicit parameter bindings for each sql can take away all the goodness of using JDBI over JDBC.

**Comment by stevenschlansker** [comment]
Yes, we now support `bindByType` as well as setting default "untyped" null: https://github.com/jdbi/jdbi/blob/master/core/src/main/java/org/jdbi/v3/core/argument/Arguments.java#L85
