### ISSUE TITLE
NullPointerException in SqlBatch with a constant parameter value of null

### ISSUE THREAD

**Issue by rherrmann** [jdbi/jdbi#1761]
I'm trying to execute an `@SqlBatch` with a constant parameter value of `null`. This causes a `NullPointerException` in JDBI while  testing if arguments are iterable-like.

This code reproduces the issue:
```java
public interface Sql {
  // create table user (tenant_id varchar(20), name varchar(20))
  @SqlBatch("insert into user(tenant_id, name) values (:tenantId, :name);")
  void insert(String tenantId, @Bind("name") List<String> names);
}

Jdbi jdbi = Jdbi.create(connectionUrl);
jdbi.installPlugin(new SqlObjectPlugin());
jdbi.useHandle(handle -> {
  Sql sql = handle.attach(Sql.class);
  sql.insert(null, asList("foo", "bar"));
});
```

Stacktrace:
```
java.lang.NullPointerException
	at org.jdbi.v3.core.internal.IterableLike.isIterable(IterableLike.java:48)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.zipArgs(SqlBatchHandler.java:269)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.invoke(SqlBatchHandler.java:174)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.lambda$invoke$0(SqlObjectInitData.java:125)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
	at org.jdbi.v3.core.ConstantHandleSupplier.lambda$invokeInContext$0(ConstantHandleSupplier.java:56)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
	at org.jdbi.v3.core.ConstantHandleSupplier.invokeInContext(ConstantHandleSupplier.java:52)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.call(SqlObjectInitData.java:131)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.invoke(SqlObjectInitData.java:125)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$attach$2(SqlObjectFactory.java:110)
	at com.sun.proxy.$Proxy39.insert(Unknown Source)
```

**Comment by stevenschlansker** [comment]
Thanks for reporting this, will be fixed in the next release.
