### ISSUE TITLE
@SqlBatch doesn't like NULL parameter 

### ISSUE THREAD

**Issue by ayethu** [jdbi/jdbi#1770]
**Environment**
- jdbi 3.14.4
- JDK 1.8.0_45
- OSX Catalina 10.15.6

**Description:**
If you have multiple bind parameters for a @SqlBatch method, and one of the non-iterable parameter is NULL, the following error is thrown:
```
java.lang.NullPointerException
        at org.jdbi.v3.core.internal.IterableLike.isIterable(IterableLike.java:48)
        at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.zipArgs(SqlBatchHandler.java:269)
        at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.invoke(SqlBatchHandler.java:174)
        at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.lambda$invoke$0(SqlObjectInitData.java:125)
        at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1$$Lambda$614/447234532.call(Unknown Source)
        at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
        at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:26)
        at org.jdbi.v3.core.LazyHandleSupplier.lambda$invokeInContext$1(LazyHandleSupplier.java:77)
        at org.jdbi.v3.core.LazyHandleSupplier$$Lambda$615/1028348585.call(Unknown Source)
        at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
        at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:26)
        at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:76)
        at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.call(SqlObjectInitData.java:131)
        at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.invoke(SqlObjectInitData.java:125)
        at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$attach$2(SqlObjectFactory.java:110)
```

Example, `durationMins` is null :
```
    @SqlBatch
    @GetGeneratedKeys
    long[] saveBatch(@Bind("user_id") Long userId,
                    @Bind("contact_id") Long contactId,
                    @Bind("scheduled_on") List<LocalDateTime> scheduledOn,
                    @Bind("duration_mins") Integer durationMinutes,
                    @Bind("state_id") Integer stateId,
                    @Bind("duologue_type_id") Integer typeId,
                    @Bind("title") List<String> title);
```

This can probably be handled with a null check for the `IterableLike.isIterable()` method call:

```
public static boolean isIterable(Object maybeIterable) {
        return maybeIterable instanceof Iterator<?>
            || maybeIterable instanceof Iterable<?>
            || maybeIterable.getClass().isArray();
    }
```
The `maybeIterable.getClass().isArray()` line is the one that's throwing NPE.

**Comment by stevenschlansker** [comment]
Thanks for reporting this, I think this is the same as https://github.com/jdbi/jdbi/issues/1761 which is fixed in 3.15.0 or 3.14.5
