### ISSUE TITLE
Native image (GraalVM) compilation error

### ISSUE THREAD

**Issue by hrensgory** [jdbi/jdbi#1797]
Trying to compile my project with jdbi usage into native image faced with following error:

```
Error: Unsupported features in methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, .g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.MethodHandle.invokeBasic()
To enable method handles that do not require LambdaForm interpretation (e.g. because of a call to MethodHandle.bindTo()) or to diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The error is then reported at run time when the invoke is executed and the method handle has to be interpreted.
Trace:
        at parsing java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
Call path from entry point to java.lang.invoke.Invokers$Holder.invokeExact_MT(Object, Object):
        at java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
        at org.jdbi.v3.core.config.ConfigRegistry.lambda$null$3(ConfigRegistry.java:100)
        at org.jdbi.v3.core.config.ConfigRegistry$$Lambda$1041/0x00000007c2550440.apply(Unknown Source)
        at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$function$4(Unchecked.java:76)
        at org.jdbi.v3.core.internal.exceptions.Unchecked$$Lambda$1042/0x00000007c2550840.apply(Unknown Source)
        at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:330)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

```
It will be very nice to have the ability to compile projects with jdbi usage into native images.

**Comment by stevenschlansker** [comment]
Interesting.  We'd like to support this, but I'm not entirely clear on what the fix is here.  Does the suggested `--report-unsupported-elements-at-runtime` give any additional useful information?  Is your test case easy to share?

**Comment by stevenschlansker** [comment]
In particular, how in the world is Jdbi `Unchecked` getting invoked from `sun.security.ec` elliptic curve???

**Comment by hrensgory** [comment]
I'll try to make a minimalistic reproducer.  The current project, I test on, is quite a big service, based on Quarkus (https://quarkus.io) which has a "native" maven profile to be built as a native executable. Unfortunately, I cant' share it as is.

**Comment by famartinrh** [comment]
Hi, I've also had this issues when trying to compile to native the project [apicurio-registry](https://github.com/Apicurio/apicurio-registry/issues/1068).

The main issue with jdbi and native compilation is the fact that the class `ConfigRegistry` uses `MethodHandle`, which is not supported by GraalVM. However in some cases it's possible to use reflection with GraalVM.

I'm triying to create a quarkus extension to address the issues with the class `ConfigRegistry` and some other things that may show up in the process... my theory is to write a [substitution](https://blog.frankel.ch/solving-substitution-graalvm-issue/) for the class `ConfigRegistry` but it's a bit difficult given it's my first time dealing with this kind of things...

Sometimes in this situations it's recommended to address the issues directly in the project/library which in this case should consist of refactoring the class `ConfigRegistry` to not use `MethodHandle` and instead instantiate the factories in a different way. 
Btw I'm not sure if doing reflection but without using `MethodHandle`, that could be explored.

**Comment by stevenschlansker** [comment]
It looks like Graal might be working on solving this problem for us: https://github.com/oracle/graal/issues/2761
We introduced the MethodHandles approach for performance on HotSpot, and probably don't want to regress performance.

Either we can accept the Graal fix when it lands, or maybe we can include a traditional reflection variant for Graal if this issue isn't fixed soon.

**Comment by stevenschlansker** [comment]
> Full method handles support will be included in the 21.0 release

Let's test this against 21.0, and if there's still issues, proceed from there.

**Comment by stevenschlansker** [comment]
Looks like 21.0 is out, so we can re-test this now to see if there's any progress:
> Added method handle invocation support for Native Image (see 2761). Methods and fields accessed through method handles have to be registered in the Reflection configuration file. Also added method handles support to the Tracing agent to automatically generate the configuration for the native image build. Most use cases of method handles are supported. VarHandles that are not stored in static fields are still not supported.

**Comment by famartinrh** [comment]
I would like to test this, however I tested this using quarkus, so I'll have to wait until quarkus upgrades to graalvm 21.0

**Comment by hrensgory** [comment]
Just tested it with JDBI 3.18.0, Quarkus 1.11.2.Final and graalvm-ce-java11-21.0.0, now it compiles ok, with no errors!

**Comment by medvedev** [comment]
Simple demo app compiles successfully with Quarkus 1.11.3, JDBI 3.18.0 and GraalVM CE 21.0.0
But in the runtime I'm getting an exception:
```
 org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalStateException: Unable to instantiate config class class org.jdbi.v3.core.config.JdbiCaches. Is there a public no-arg constructor?
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
 ...
 Caused by: java.lang.IllegalStateException: Unable to instantiate config class class org.jdbi.v3.core.config.JdbiCaches. Is there a public no-arg constructor?
        at org.jdbi.v3.core.config.ConfigRegistry.lambda$configFactory$4(ConfigRegistry.java:105)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at org.jdbi.v3.core.config.ConfigRegistry.configFactory(ConfigRegistry.java:83)
        at org.jdbi.v3.core.config.ConfigRegistry.get(ConfigRegistry.java:78)
        at org.jdbi.v3.core.config.ConfigRegistry.<init>(ConfigRegistry.java:46)

 ...
 Caused by: java.lang.NoSuchMethodException: no such constructor: org.jdbi.v3.core.config.JdbiCaches.<init>()void/newInvokeSpecial
        at java.lang.invoke.MemberName.makeAccessException(MemberName.java:961)
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
        at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
        at org.jdbi.v3.core.config.ConfigRegistry.lambda$configFactory$4(ConfigRegistry.java:96)
        ... 37 more
 Caused by: java.lang.NoSuchMethodError: org.jdbi.v3.core.config.JdbiCaches.<init>()
        at java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:230)
        at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098)
        ... 40 more
```

**Comment by medvedev** [comment]
Updated to GraalVM 21.0.0.2, and native image fails to compile again.
```
Error: Unsupported features in 3 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.MethodHandle.invokeBasic()
To enable method handles that do not require LambdaForm interpretation (e.g. because of a call to MethodHandle.bindTo()) or to diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The error is then reported at run time when the invoke is executed and the method handle has to be interpreted.
Trace: 
        at parsing java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
Call path from entry point to java.lang.invoke.Invokers$Holder.invokeExact_MT(Object, Object): 
        at java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
        at org.jdbi.v3.core.config.ConfigRegistry.lambda$null$3(ConfigRegistry.java:100)
```
(2 other errors are the same, pointing to lines 86 and 89 of the ConfigRegistry.java)

**Comment by stevenschlansker** [comment]
That is exciting that it compiles.  Any reports on whether the resulting executable works?

**Comment by famartinrh** [comment]
After giving this a try again, now that Quarkus uses GraalVM 21 and therefore we have support for MethodHandles , I'm able to compile my application to a native executable. But still it doesn't work.

It's required to register all the classes used for reflection, i.e. all the classes that implement JdbiConfig but there are a lot more.
I started a quarkus extension https://github.com/famartinrh/jdbi-quarkus-extension that should address all this kind of things, it's not finished yet, and I may need help from someone who knows better the internals of jdbi and maybe a quarkus expert.

Just for now [this](https://github.com/famartinrh/jdbi-quarkus-extension/blob/master/deployment/src/main/java/org/jdbi/quarkus/deployment/JdbiQuarkusProcessor.java#L36) describes the current status of the extension.

**Comment by stevenschlansker** [comment]
Yeah, I suppose that all Jdbi config classes, both internal and user-defined, need to be initialized in the equivalent of a static initializer, so that the MethodHandles are recorded as being used at runtime automatically.

One thing to try might be to have your application do an entire Jdbi operation against a fake database during static initialize.  That would force all the reflection machinery to initialize.

Another thing we should do is introduce a test case or CI step to Jdbi that builds a native Graal image.  I'm not sure so how difficult this will be but it would give us confidence that once we figure out how to make it work, it stays working.

It would be nice to not have to require any reflection configuration at all for Jdbi to work in graal native.

**Comment by vbsteven** [comment]
Is there any progress on this specific issue? 

I've been hacking a little bit on getting my jdbi/sqlite/kotlin setup to build and run using graalvm native-image and so far I have something that compiles and is able to make queries at runtime using version 3.28.0 of `jdbi3-kotlin`, `jdbi3-kotlin-sqlobject`, `jdbi3-sqlite` combined with `org.xerial:sqlite-jdbc:3.36.0.3`.

It mostly works by 
* adding a bunch of `org.jdbi.v3.core.`, `org.jdbi.v3.sqlobject`, `com.github.benmanes.cache` classes to `reflect-config.json`
* adding my Dao interfaces to `proxy-config.json`
* registering a manual RowMapper for my model classes

This way it compiles and at runtime Jdbi can connect and make queries.

I've noticed the xerial-sqlite jar includes a `META-INF/native-image/` folder that has the necessary native-image properties for the library. Is this something Jdbi wants to do as well? 

https://www.graalvm.org/22.0/reference-manual/native-image/BuildConfiguration/

**Comment by stevenschlansker** [comment]
That is very exciting that you got it to work, sounds like there is a lot of progress on this issue! ;)
We'd be happy to include the necessary configuration files. I still hope that over time we'd be able to reduce reflection usage.
Is the configuration you generated something you could adapt to the `META-INF/native-image` format and submit as a PR?

**Comment by Eng-Fouad** [comment]
https://stackoverflow.com/questions/73022125/lambda-expression-classes-in-graalvm-reflection-configuration

**Comment by Eng-Fouad** [comment]
> Hello, is @Eng-Fouad solution definitive? Can this issue be marked as solved?
> 
> 

Yes, JDBI currently can be compiled to native by including the necessary configurations as shown in this gist:

https://gist.github.com/Eng-Fouad/7b5925481dd391fcc74487a68484b987

**Comment by stevenschlansker** [comment]
Thanks everyone. Given that this is reported as working now, I will close this issue.
We still have more work to do to add Graal native to our own CI.
