### ISSUE TITLE
GetGeneratedKeys not working well with return of type List

### ISSUE THREAD

**Issue by TorRanfelt** [jdbi/jdbi#1807]
For some reason the code below (in its entirety of course) works when result is Int, but as soon as result in List<Int> I get:
org.jdbi.v3.core.result.ResultSetException: Error thrown mapping result set into return type
Caused by: org.postgresql.util.PSQLException: No results were returned by the query.

```
    @SqlUpdate(
        "INSERT INTO Boks (/* Something */) " +
        "SELECT // Something 
        "FROM Boks " +
        "WHERE // Something 

        "ON CONFLICT (/*Something*/) DO UPDATE SET " +
        // Something
    )
    @GetGeneratedKeys("baz")
    fun copyAll(foo1: UUID, foo2: UUID, @BindList("years") years: List<Int>) : List<Int>
```

**Comment by TorRanfelt** [comment]
I can make it work by by not using an SQLObject.

```
                        handle.createUpdate(
                            "INSERT INTO Boks (/* Something */) " +
                            "SELECT // Something
                            "FROM Boks " +
                            "WHERE // Something

                            "ON CONFLICT (/*Something*/) DO UPDATE SET " +
                            // Something
                        )
                            .bind("foo1", foo1)
                            .bind("foo2", foo2)
                            .bindList("years", years)
                            .executeAndReturnGeneratedKeys("baz")
                            .list()
```

**Comment by stevenschlansker** [comment]
Does the same code work with `List<Integer>` (the normal Java type, rather than the Kotlin type)?

**Comment by TorRanfelt** [comment]
The problem is identical with return type `List<Integer>`.

**Comment by blaenk** [comment]
I can confirm this _appears_ to be a bug with SqlObject. I am happy to help investigate. I'm not familiar with the Jdbi codebase but it _really_ feels like it's _almost there_ with working, just one little thing may be missing (basically I think the config map/cache is missing an entry it should and can easily have or something, like `JdbiCollectors` didn't kick in).

Given configuration (excuse the Spring):

```java
  @Bean
  public List<JdbiPlugin> jdbiPlugins() {
    return List.of(new PostgresPlugin(), new SqlObjectPlugin(), new Jackson2Plugin());
  }

  @Bean
  public Jdbi jdbi(DataSource ds, List<JdbiPlugin> jdbiPlugins, List<RowMapper<?>> rowMappers) {
    TransactionAwareDataSourceProxy proxy = new TransactionAwareDataSourceProxy(ds);
    Jdbi jdbi = Jdbi.create(proxy);

    jdbiPlugins.forEach(jdbi::installPlugin);
    rowMappers.forEach(jdbi::registerRowMapper);

    return jdbi;
  }

  @Bean
  public FeedDao feedDao(Jdbi jdbi) {
    return jdbi.onDemand(FeedDao.class);
  }
```

Given bean:

```java
@Data
@Builder(toBuilder = true)
@With
@NoArgsConstructor
@AllArgsConstructor
public class FeedEntry {
  private UUID feedEntryId;
  private Instant dateCreated;
  private String title;
  private UUID guid;
  private Instant publicationDate;
  private String link;
  private String description;
  private String content;
  private Set<String> tags;
  private UUID feedId;
}
```

This works, i.e. the query would be returning a list but I am only capturing the first row as per Jdbi semantics when specifying a non-collection return type:

```java
class FeedDao extends SqlObject {
  @SqlUpdate(
      """
    INSERT INTO app.feed_entries
      (feed_id, title, guid, publication_date, link, description, content, tags)
      VALUES <entries>
      RETURNING *;
    """)
  @GetGeneratedKeys
  FeedEntry insertEntries(
      @BindBeanList(
              value = "entries",
              propertyNames = {
                "feedId",
                "title",
                "guid",
                "publicationDate",
                "link",
                "description",
                "content",
                "tags"
              })
          List<FeedEntry> entries);
```

This does not work. All I changed was the return type from `FeedEntry` to `List<FeedEntry>` to capture all of the inserted rows:

```java
class FeedDao extends SqlObject {
  @SqlUpdate(
      """
    INSERT INTO app.feed_entries
      (feed_id, title, guid, publication_date, link, description, content, tags)
      VALUES <entries>
      RETURNING *;
    """)
  @GetGeneratedKeys
  List<FeedEntry> insertEntries(
      @BindBeanList(
              value = "entries",
              propertyNames = {
                "feedId",
                "title",
                "guid",
                "publicationDate",
                "link",
                "description",
                "content",
                "tags"
              })
          List<FeedEntry> entries);
```

The stack trace is:

```
org.jdbi.v3.core.mapper.NoSuchMapperException: No mapper registered for type java.util.List<app.models.FeedEntry>

	at org.jdbi.v3.core.result.ResultBearing.lambda$mapTo$0(ResultBearing.java:131)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.jdbi.v3.core.result.ResultBearing.lambda$mapTo$1(ResultBearing.java:131)
	at org.jdbi.v3.core.result.ResultBearing$1.scanResultSet(ResultBearing.java:58)
	at org.jdbi.v3.core.result.ResultBearing.mapTo(ResultBearing.java:129)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$new$0(SqlUpdateHandler.java:59)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$configureReturner$3(SqlUpdateHandler.java:90)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:187)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.invoke(SqlUpdateHandler.java:32)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.lambda$invoke$0(SqlObjectInitData.java:132)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:26)
	at org.jdbi.v3.core.LazyHandleSupplier.lambda$invokeInContext$1(LazyHandleSupplier.java:79)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:26)
	at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:78)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.call(SqlObjectInitData.java:138)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.invoke(SqlObjectInitData.java:132)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$attach$2(SqlObjectFactory.java:108)
	at org.jdbi.v3.core.internal.OnDemandExtensions.lambda$invoke$5(OnDemandExtensions.java:98)
	at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$function$4(Unchecked.java:76)
	at org.jdbi.v3.core.internal.OnDemandExtensions.invoke(OnDemandExtensions.java:98)
	at org.jdbi.v3.core.internal.OnDemandExtensions.lambda$createProxy$2(OnDemandExtensions.java:82)
	at org.jdbi.v3.core.Jdbi.callWithExtension(Jdbi.java:491)
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:478)
	at org.jdbi.v3.core.internal.OnDemandExtensions.lambda$createProxy$3(OnDemandExtensions.java:82)
	at jdk.proxy2/jdk.proxy2.$Proxy166.insertEntries(Unknown Source)
	at app.dao.FeedDaoIT.testIntegration(FeedDaoIT.java:135)
```

However, bypassing SqlObject annotations and going direct through the `Handle` does work as pointed out by @TorRanfelt:

```java
class FeedDao extends SqlObject {
  default List<FeedEntry> directInsertEntries(List<FeedEntry> entries) {
    return withHandle(
        h ->
            h.createUpdate(
                    """
            INSERT INTO app.feed_entries
                  (feed_id, title, guid, publication_date, link, description, content, tags)
                  VALUES <entries>;
            """)
                .bindBeanList(
                    "entries",
                    entries,
                    List.of(
                        "feedId",
                        "title",
                        "guid",
                        "publicationDate",
                        "link",
                        "description",
                        "content",
                        "tags"))
                .executeAndReturnGeneratedKeys()
                .mapToBean(FeedEntry.class)
                .list());
  }
```

Some of the things I tried (forgot most of them):

* I spent a while stepping through the debugger. It seems like it may be something related to `JdbiCollectors` and the `factoryCache` or something, the entry for `List<FeedEntry>` is _present_ in the cache but it's `Optional.empty`, but honestly I got a little lost in tracing where I was so I may be mixing up different threads of execution.
* I tried omitting `RETURNING` or specifying `RETURNING *` or `RETURNING a, b, c` from the query. No difference.
* I tried omitting or explicitly listing the `GeneratedKeys` columns. No difference.

**Comment by blaenk** [comment]
After reading the end of [this section](https://jdbi.org/#_map_entry_mapping) of the docs, which gives an overview of `JdbiCollectors`, I think an issue may be that `Mappers.findFor()` is looking for a mapper for `List<FeedEntry>` when it _seems_ like it should be looking for a mapper for the element type, `FeedEntry`, which _is_ present in the mappers map. It seems like the act of collecting into a list is a later process after mapping the rows or something.

While debugging, the state of the code below is:

* type: `java.util.List<app.models.FeedEntry>`
* rowMappers: `Map { cache { app.models.FeedEntry -> BeanMapper } }`

https://github.com/jdbi/jdbi/blob/26a03d3479daead969d1010d893b91fb13af0af2/core/src/main/java/org/jdbi/v3/core/mapper/Mappers.java#L105-L114

Paused at the `if` statement I evaluated the expression:

```java
rowMappers.register(type.getType(), rowMappers.findFor(FeedEntry.class).get())
```

So as to create a Mappers entry of the type:

```
java.util.List<app.models.FeedEntry> -> BeanMapper
```

AFAIK the types don't line up but type erasure makes that moot, I think.

Resuming execution resulted in a successful result: a `List<FeedEntry>`.

That said, I'm not quite sure what would be the best way to remedy this. I have looked through historical posts from @stevenschlansker and @qualidafial but I must admit this reflection stuff is stuff is pretty difficult to follow (though undoubtedly useful as a user!). I'm happy to take pointers so I can contribute the fix, or if someone is happy to take it from here that works too!

**Comment by blaenk** [comment]
Tried `jdbi3-generator` and `@GenerateSqlObject` and also ran into this there.

I looked into it some more, and I found that in `SqlUpdateHandler.java` here:

https://github.com/jdbi/jdbi/blob/0420cc462f98565062bd577cf5d3a4d92a621060/sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/SqlUpdateHandler.java#L45-L47

That type resolves to `List<MyBean>`, but if I use the debugger to set the type to `MyBean` instead, everything works as intended.

I think something like `ListCollectorFactory` would need to be used where if it's a `List` (or other collection?), it instead resolves to its contained "element type".

**Comment by stevenschlansker** [comment]
Finally should be implemented in the next release :)

**Comment by stevenschlansker** [comment]
Oops, sorry, this linked PR isn't merged yet. We hope to merge it soon but I shouldn't close this issue until it is.
