### ISSUE TITLE
Returning a ResultIterator from a method using getHandle returns a closed iterator

### ISSUE THREAD

**Issue by jkebinger** [jdbi/jdbi#184]
When I create a method to dynamically generate some sql and return an iterator like the simplified example below, the returned Iterator belongs to a closed Handle and throws an exception when used.

I verified with a debugger that OnDemandHandleDing$LocalDing is closing the handle when my method returns, which makes it impossible to build sophisticated queries and iterate over the results.

```java

public abstract class EventDetailDao implements Closeable, GetHandle { 
  public ResultIterator<EventDetail> getEventDetailsIterator(Map<AllowedFilter, String> queryParams) {
    String sql = buildSql(queryParms);
    return getHandle().createQuery(sql).mapTo(EventDetail.class).iterator();
  }
}
```
here's the stack trace 
```
org.skife.jdbi.v2.exceptions.ResultSetException: Unable to advance result set [statement:"SELECT id, domain, portalId, emailCampaignId, email, emailAccountId, eventType, status, reason, date, category FROM eventDetails WHERE portalId = :portalId AND email = :email LIMIT 100 OFFSET 0", located:"SELECT id, domain, portalId, emailCampaignId, email, emailAccountId, eventType, status, reason, date, category FROM eventDetails WHERE portalId = :portalId AND email = :email LIMIT 100 OFFSET 0", rewritten:"SELECT id, domain, portalId, emailCampaignId, email, emailAccountId, eventType, status, reason, date, category FROM eventDetails WHERE portalId = ? AND email = ? LIMIT 100 OFFSET 0", arguments:{ positional:{}, named:{portalId:53,email:'test@email.com'}, finder:[]}]
	at org.skife.jdbi.v2.ResultSetResultIterator.safeNext(ResultSetResultIterator.java:122)
	at org.skife.jdbi.v2.ResultSetResultIterator.hasNext(ResultSetResultIterator.java:72)
	at com.google.common.collect.Lists.newArrayList(Lists.java:144)
	at com.hubspot.email.api.event.details.EventDetailDaoTest.queryBuilderShouldWork(EventDetailDaoTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.sql.SQLException: Operation not allowed after ResultSet closed
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872)
	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:740)
	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6314)
	at com.zaxxer.hikari.proxy.ResultSetJavassistProxy.next(ResultSetJavassistProxy.java)
	at org.skife.jdbi.v2.ResultSetResultIterator.safeNext(ResultSetResultIterator.java:119)
	... 33 more
```

**Comment by stevenschlansker** [comment]
See discussion on the mailing list:  https://groups.google.com/forum/#!topic/jdbi/asJUXT1Uirw

This is a new feature request, not a bug per se.

**Comment by qualidafial** [comment]
@stevenschlansker I believe this issue is now moot in v3. This usage is no longer supported for on-demand SQL objects.

If using e.g. `Handle.attach` or `Jdbi.withExtension`, the result iterator should continue to be valid until the iterator is consumed, the handle is disposed, or (in the case of `withExtension) the callback returns.

**Comment by stevenschlansker** [comment]
Seems reasonable.  @jkebinger please feel free to follow up if you believe there is still an issue here.  We will strive to improve the v3 documentation so it is clear exactly why this sort of usage doesn't (and in my opinion probably shouldn't) work.
