### ISSUE TITLE
return java.util.optional

### ISSUE THREAD

**Issue by GeorgeSalu** [jdbi/jdbi#1859]
hello, jdbi beginner

jdbi: 3.18.1
jdk: 15

I have a problem to return optional (java.util.Optional),

example:

`@SqlQuery("""
			SELECT 
				id, first_name, last_name, email_address 
			FROM 
				employees
			""")
	@RegisterBeanMapper(value = Employee.class)
	List<Employee> findAll();

`

this works very well, until you try to return an optional

> 

 @SqlQuery("""
			SELECT 
				id, first_name, last_name, email_address 
			FROM 
				employees
			""")
	@RegisterBeanMapper(value = Employee.class)
	Optional<List <Employee> > findAll();
> 

he throws me this exception: 

org.jdbi.v3.core.mapper.NoSuchMapperException: No mapper registered for type java.util.List<com.test.model.Employee>
	at org.jdbi.v3.core.result.ResultBearing.lambda$null$0(ResultBearing.java:133) ~[jdbi3-core-3.18.1.jar:3.18.1]
	at java.base/java.util.Optional.orElseThrow(Optional.java:401) ~[na:na]
	at org.jdbi.v3.core.result.ResultBearing.lambda$mapTo$1(ResultBearing.java:133) ~[jdbi3-core-3.18.1.jar:3.18.1]
	at org.jdbi.v3.core.result.ResultBearing$1.scanResultSet(ResultBearing.java:59) ~[jdbi3-core-3.18.1.jar:3.18.1]
	at org.jdbi.v3.core.statement.Query.scanResultSet(Query.java:56) ~[jdbi3-core-3.18.1.jar:3.18.1]
	at org.jdbi.v3.core.result.ResultBearing.mapTo(ResultBearing.java:131) ~[jdbi3-core-3.18.1.jar:3.18.1]
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:59) ~[jdbi3-sqlobject-3.18.1.jar:3.18.1]
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:178) ~[jdbi3-sqlobject-3.18.1.jar:3.18.1]
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:27) ~[jdbi3-sqlobject-3.18.1.jar:3.18.1]
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.lambda$invoke$0(SqlObjectInitData.java:132) ~[jdbi3-sqlobject-3.18.1.jar:3.18.1]
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44) ~[jdbi3-core-3.18.1.jar:3.18.1]
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:26) ~[jdbi3-core-3.18.1.jar:3.18.1]
	at org.jdbi.v3.core.LazyHandleSupplier.lambda$invokeInContext$1(LazyHandleSupplier.java:77) ~[jdbi3-core-3.18.1.jar:3.18.1]
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44) ~[jdbi3-core-3.18.1.jar:3.18.1]
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:26) ~[jdbi3-core-3.18.1.jar:3.18.1]
	at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:76) ~[jdbi3-core-3.18.1.jar:3.18.1]
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.call(SqlObjectInitData.java:138) ~[jdbi3-sqlobject-3.18.1.jar:3.18.1]
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.invoke(SqlObjectInitData.java:132) ~[jdbi3-sqlobject-3.18.1.jar:3.18.1]
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$attach$2(SqlObjectFactory.java:110) ~[jdbi3-sqlobject-3.18.1.jar:3.18.1]
	at com.sun.proxy.$Proxy68.buscaTodos(Unknown Source) ~[na:na]

**Comment by x80486** [comment]
`Optional<List>` (or for that matter `Optional<List<?>>`) shouldn't be a thing. A list will have elements or not — empty in that case. Those are the proper semantics for a collection.

**Comment by GeorgeSalu** [comment]
esta assim Optional<List<?>>, não estou conseguindo colocar aqui, Optional<List<Employee>>

**Comment by GeorgeSalu** [comment]
I managed to find a better solution
