### ISSUE TITLE
How to map primitive types?

### ISSUE THREAD

**Issue by mritd** [jdbi/jdbi#1860]
I saw that the primitive type mapping in the documentation is available out of the box, 
but I encountered the following error:

```java
@SqlQuery("SELECT id FROM t_user_whitelist WHERE phone = ?")
int checkWhitelist(String phone);
```

error message:

```sh
java.lang.IllegalStateException: SQL method returns primitive int, but statement returned no results
	at org.jdbi.v3.sqlobject.statement.internal.ResultReturner.checkResult(ResultReturner.java:115)
	at org.jdbi.v3.sqlobject.statement.internal.ResultReturner.access$000(ResultReturner.java:41)
	at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.mappedResult(ResultReturner.java:277)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:61)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:178)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:27)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.lambda$invoke$0(SqlObjectInitData.java:132)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:26)
	at org.jdbi.v3.core.LazyHandleSupplier.lambda$invokeInContext$1(LazyHandleSupplier.java:77)
...
```

**Comment by mritd** [comment]
Sorry, the database type is bigint....

**Comment by leaumar** [comment]
Are you sure your query matched any records?

> but statement returned no results

**Comment by mritd** [comment]
I confirm that the record is found

```sh
2021-04-16 19:08:07.739 localhost [http-nio-8080-exec-1] DEBUG org.jdbi.sql.logAfterExecution - Executed in 0:00:00.001 'SELECT id FROM t_user_whitelist WHERE phone = ?' with parameters '{positional:{0:{"phone":"17610552201"}}, named:{phone:{"phone":"17610552201"}}, finder:[]}' 
2021-04-16 19:08:07.748 localhost [http-nio-8080-exec-1] ERROR c.x.a.c.WebMVCConfig$GlobalHandlerExceptionResolver.resolveException - 服务器遇到未知错误: 
java.lang.IllegalStateException: SQL method returns primitive int, but statement returned no results
```

**Comment by mritd** [comment]
![image](https://user-images.githubusercontent.com/13043245/115016367-8622e580-9ee7-11eb-889f-ac4020f813d8.png)

**Comment by mritd** [comment]
Sorry this is a stupid question. I wrongly used json string as query parameter.

**Comment by sixinli** [comment]
for the case when it's actually null (no rows found), how should it be handle? it seems like there's `PrimitiveMapperFactory` that does some conversions for primitive but its not in use for `ResultReturner`?

**Comment by stevenschlansker** [comment]
If you want your `int` to be optional, try `Integer` which may be `null`.

**Comment by sixinli** [comment]
yea that'd work, but would still be good if theres a way to define mappers that maps to primitive types too, just like how the `PrimitiveMapperFactory` does it :)

**Comment by stevenschlansker** [comment]
If you have a specific use for this, please feel free to open a new feature request ticket, including what code you expect to execute and what result you expect.
