### ISSUE TITLE
fix mockito warnings

### ISSUE THREAD

**Issue by hgschmie** [jdbi/jdbi#1877]
```
[INFO] Running org.jdbi.v3.core.mapper.TestEnums
[MockitoHint] ArgumentBinderTest.testNamedEmpty (see javadoc for MockitoHint):
[MockitoHint] 1. Unused -> at org.jdbi.v3.core.statement.ArgumentBinderTest.before(ArgumentBinderTest.java:46)
[MockitoHint] 2. Unused -> at org.jdbi.v3.core.statement.ArgumentBinderTest.before(ArgumentBinderTest.java:47)

[MockitoHint] ArgumentBinderTest.testNamedDeclaredButNotProvided (see javadoc for MockitoHint):
[MockitoHint] 1. Unused -> at org.jdbi.v3.core.statement.ArgumentBinderTest.before(ArgumentBinderTest.java:46)
[MockitoHint] 2. Unused -> at org.jdbi.v3.core.statement.ArgumentBinderTest.before(ArgumentBinderTest.java:47)

[MockitoHint] ArgumentBinderTest.testPositionalNotDeclaredButProvidedWithPermission (see javadoc for MockitoHint):
[MockitoHint] 1. Unused -> at org.jdbi.v3.core.statement.ArgumentBinderTest.before(ArgumentBinderTest.java:46)

[MockitoHint] ArgumentBinderTest.testPositionalEmpty (see javadoc for MockitoHint):
[MockitoHint] 1. Unused -> at org.jdbi.v3.core.statement.ArgumentBinderTest.before(ArgumentBinderTest.java:46)
[MockitoHint] 2. Unused -> at org.jdbi.v3.core.statement.ArgumentBinderTest.before(ArgumentBinderTest.java:47)

[MockitoHint] ArgumentBinderTest.testNamedNotDeclaredButProvided (see javadoc for MockitoHint):
[MockitoHint] 1. Unused -> at org.jdbi.v3.core.statement.ArgumentBinderTest.before(ArgumentBinderTest.java:46)

[MockitoHint] ArgumentBinderTest.testPositionalDeclaredButNotProvided (see javadoc for MockitoHint):
[MockitoHint] 1. Unused -> at org.jdbi.v3.core.statement.ArgumentBinderTest.before(ArgumentBinderTest.java:46)

[MockitoHint] ArgumentBinderTest.testNamedNotDeclaredButProvidedWithPermission (see javadoc for MockitoHint):
[MockitoHint] 1. Unused -> at org.jdbi.v3.core.statement.ArgumentBinderTest.before(ArgumentBinderTest.java:46)

[MockitoHint] ArgumentBinderTest.testPositionalNotDeclaredButProvided (see javadoc for MockitoHint):
[MockitoHint] 1. Unused -> at org.jdbi.v3.core.statement.ArgumentBinderTest.before(ArgumentBinderTest.java:46)
```

**Comment by SivaTharun** [comment]
@hgschmie can i work on this issue.

**Comment by sman-81** [comment]
@hgschmie I cannot reproduce this issue or rather these Mockito warnings in master
Likely this has resolved itself with dependency updates or other changes with (positive) side effects ;)

**Comment by stoyants** [comment]
@hgschmie 
Hi Henning, 
Seems you fixed this issue with the following Pull Request: #1926.
In release v3.24.0 the MockitoHint messages do not appear anymore.
Someone can double check this, but I think the Issue #1877 can be closed.
Best Regards,
Stoyan

**Comment by stevenschlansker** [comment]
Thanks all!
