### ISSUE TITLE
Adapt to new mysql driver version

### ISSUE THREAD

**Issue by carlesarnal** [jdbi/jdbi#1880]
Hi, first of all, thanks for the amazing work. Due to the recent changes in the MySQL driver version 8.0.23, we've found this issue in our project, probably because jdbi has not been adapted yet. Do you have any insight on this?

Thanks!

```
 Caused by: java.lang.ClassCastException: Cannot cast java.time.LocalDateTime to java.util.Date
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361)
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356)
	at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$biConsumer$6(Unchecked.java:96)
	at org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory$BeanPojoProperties$1.set(BeanPropertiesFactory.java:93)
	at org.jdbi.v3.core.mapper.reflect.internal.PojoProperties$PojoBuilder.set(PojoProperties.java:44)
	at org.jdbi.v3.core.mapper.reflect.internal.PojoMapper.lambda$specialize0$7(PojoMapper.java:150)
	at org.jdbi.v3.core.result.ResultSetResultIterator.next(ResultSetResultIterator.java:83)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at org.jdbi.v3.core.result.ResultIterator.forEachRemaining(ResultIterator.java:39)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:285)
	at org.jdbi.v3.core.result.ResultIterable.list(ResultIterable.java:273)
	at io.apicurio.hub.core.storage.jdbc.JdbcStorage.lambda$listLinkedAccounts$14(JdbcStorage.java:442)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:341)
```

**Comment by stevenschlansker** [comment]
Thank you for reporting this - can you show us the Jdbi call you make to cause this exception, and any driver configuration you might have?
We will need to fix this in a way that does not break older drivers either.

**Comment by carlesarnal** [comment]
> Thank you for reporting this - can you show us the Jdbi call you make to cause this exception, and any driver configuration you might have?
> We will need to fix this in a way that does not break older drivers either.

Hi, this is the code fragment 
```
return this.jdbi.withHandle( handle -> {
                String statement = sqlStatements.selectLinkedAccountByType();
                return handle.createQuery(statement)
                        .bind(0, userId)
                        .bind(1, type.name())
                        .mapToBean(LinkedAccount.class)
                        .one();
```

The error is happening when using MySQL connector 8,0.25. You have more information around this [here](https://bugs.mysql.com/bug.php?id=102435).

**Comment by hgschmie** [comment]
This is caused because the LinkedAccount class in the apicurio-studio uses Date and the driver used by the project uses LocalDateTime. JDBI uses the information passed in by the bean it is asked to map to and calls the driver code that is used by the project that also uses JDBI. 

This is not a JDBI bug.
