### ISSUE TITLE
Unable to connect to SQL Server using JDBI

### ISSUE THREAD

**Issue by miteshgupta** [jdbi/jdbi#1881]
## Driver version
JDBI version: 3.6.0
```
        <dependency>
            <groupId>org.jdbi</groupId>
            <artifactId>jdbi3-core</artifactId>
            <version>3.6.0</version>
        </dependency>

        <dependency>
            <groupId>org.jdbi</groupId>
            <artifactId>jdbi3-sqlobject</artifactId>
            <version>3.6.0</version>
        </dependency>
```

## SQL Server version
Azure SQL
```
Microsoft SQL Azure (RTM) - 12.0.2000.8 
	Apr 29 2021 13:52:20 
	Copyright (C) 2019 Microsoft Corporation
```
## Client Operating System
> macOS Big Sur 
> Version 11.2.3 (20D91)

## JAVA/JVM version
> JDK Version:  jdk1.8.0_152

## Table schema
Not relevant since we are not able to connect to DB programmatically, but able to connect via other ways.

## Problem description

1. Expected behavior: Connect to DB and query via code.
2. Actual behavior: Unable to connect to the SQL server.
3. Other details: I'm able to connect/query the SQL server via my IDE/other ways. So this can't be a connectivity/network issue.

## Stack trace
```
Exception in thread "main" org.jdbi.v3.core.ConnectionException: com.microsoft.sqlserver.jdbc.SQLServerException: SQL Server did not return a response. The connection has been closed. ClientConnectionId:98f79b96-a379-48ca-96cc-15137038d4e4
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:312)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:329)
	at com.udaan.promotions.api.Test.main(Test.java:16)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: SQL Server did not return a response. The connection has been closed. ClientConnectionId:98f79b96-a379-48ca-96cc-15137038d4e4
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2392)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2376)
	at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6680)
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7993)
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7945)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:4375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3188)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$100(SQLServerConnection.java:61)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3151)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7535)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2438)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:1973)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1616)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1447)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:788)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1187)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.jdbi.v3.core.Jdbi.lambda$create$2(Jdbi.java:135)
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:297)
	... 2 more

Process finished with exit code 1
```

## Reproduction code

```
public class Test {
    public static void main(String[] args) {
        Jdbi jdbi = Jdbi.create("jdbc:sqlserver://<db-connection-string>", "<username>", "<password>");

        List<String> config = jdbi.withHandle(handle ->
            handle.createQuery("SELECT * from config")
                    .mapTo(String.class)
                    .list()
        );

    }
}

```

**Comment by stevenschlansker** [comment]
Hi @miteshgupta, as you can see this exception is coming from the Microsoft JDBC driver, not Jdbi. Please double check your connect string with the vendor documentation, and verify that no firewalls or other security systems are blocking your connection. I expect if you try to connect with JDBC directly and no Jdbi at all, you will still encounter this exception.
