### ISSUE TITLE
Quarkus native image error using JDBI 3

### ISSUE THREAD

**Issue by henryx** [jdbi/jdbi#1908]
JDBI version: 3.21.0
Quarkus version: 2.1.Final

In a prorject developed with Quarkus and JDBI, native compilation returns a `java.lang.IllegalStateException` when execute a query. Compilation is executed with this maven command:
```
mvn clean package -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true
```
Below the stack trace:
```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-08-25 15:29:16,588 INFO  [io.quarkus] (main) test-app 0.1.0 native (powered by Quarkus 2.1.1.Final) started in 0.032s. Listening on: http://0.0.0.0:8080
2021-08-25 15:29:16,588 INFO  [io.quarkus] (main) Profile prod activated. 
2021-08-25 15:29:16,588 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, jdbc-postgresql, narayana-jta, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-openapi, swagger-ui]
2021-08-25 15:29:40,113 INFO  [io.ver.ext.web.RoutingContext] (executor-thread-0) RoutingContext failure (500): org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalStateException: Unable to instantiate config class class org.jdbi.v3.core.config.JdbiCaches. Is there a public no-arg constructor?
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.IllegalStateException: Unable to instantiate config class class org.jdbi.v3.core.config.JdbiCaches. Is there a public no-arg constructor?
	at org.jdbi.v3.core.config.ConfigRegistry.lambda$configFactory$4(ConfigRegistry.java:105)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.jdbi.v3.core.config.ConfigRegistry.configFactory(ConfigRegistry.java:83)
	at org.jdbi.v3.core.config.ConfigRegistry.get(ConfigRegistry.java:78)
	at org.jdbi.v3.core.config.ConfigRegistry.<init>(ConfigRegistry.java:46)
	at org.jdbi.v3.core.Jdbi.<init>(Jdbi.java:58)
	at org.jdbi.v3.core.Jdbi.create(Jdbi.java:104)
	at org.jdbi.v3.core.Jdbi.create(Jdbi.java:79)
	at com.application.test.common.db.Database.<init>(Database.java:15)
	at com.application.test.common.db.lookup.Plant.<init>(Plant.java:15)
	at com.com.application.test.app.TestRoot.getRoot(TestRoot.java:42)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 17 more
	Suppressed: java.lang.NoSuchMethodException: no such constructor: org.jdbi.v3.core.config.JdbiCaches.<init>(ConfigRegistry)void/newInvokeSpecial
		at java.lang.invoke.MemberName.makeAccessException(MemberName.java:961)
		at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
		at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
		at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
		at org.jdbi.v3.core.config.ConfigRegistry.lambda$configFactory$4(ConfigRegistry.java:86)
		... 39 more
	Caused by: java.lang.NoSuchMethodError: org.jdbi.v3.core.config.JdbiCaches.<init>(org.jdbi.v3.core.config.ConfigRegistry)
		at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:340)
		at java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:214)
		at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
		at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098)
		... 42 more
Caused by: java.lang.NoSuchMethodException: no such constructor: org.jdbi.v3.core.config.JdbiCaches.<init>()void/newInvokeSpecial
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:961)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
	at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
	at org.jdbi.v3.core.config.ConfigRegistry.lambda$configFactory$4(ConfigRegistry.java:96)
	... 39 more
Caused by: java.lang.NoSuchMethodError: org.jdbi.v3.core.config.JdbiCaches.<init>()
	at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:340)
	at java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:214)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098)
	... 42 more

2021-08-25 15:29:40,114 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to / failed, error id: fbc5a21f-bb9d-47eb-9c84-5b4f4fdef598-1: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalStateException: Unable to instantiate config class class org.jdbi.v3.core.config.JdbiCaches. Is there a public no-arg constructor?
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.IllegalStateException: Unable to instantiate config class class org.jdbi.v3.core.config.JdbiCaches. Is there a public no-arg constructor?
	at org.jdbi.v3.core.config.ConfigRegistry.lambda$configFactory$4(ConfigRegistry.java:105)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.jdbi.v3.core.config.ConfigRegistry.configFactory(ConfigRegistry.java:83)
	at org.jdbi.v3.core.config.ConfigRegistry.get(ConfigRegistry.java:78)
	at org.jdbi.v3.core.config.ConfigRegistry.<init>(ConfigRegistry.java:46)
	at org.jdbi.v3.core.Jdbi.<init>(Jdbi.java:58)
	at org.jdbi.v3.core.Jdbi.create(Jdbi.java:104)
	at org.jdbi.v3.core.Jdbi.create(Jdbi.java:79)
	at com.application.test.common.db.Database.<init>(Database.java:15)
	at com.application.test.common.db.lookup.Plant.<init>(Plant.java:15)
	at com.com.application.test.app.TestRoot.getRoot(TestRoot.java:42)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 17 more
	Suppressed: java.lang.NoSuchMethodException: no such constructor: org.jdbi.v3.core.config.JdbiCaches.<init>(ConfigRegistry)void/newInvokeSpecial
		at java.lang.invoke.MemberName.makeAccessException(MemberName.java:961)
		at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
		at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
		at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
		at org.jdbi.v3.core.config.ConfigRegistry.lambda$configFactory$4(ConfigRegistry.java:86)
		... 39 more
	Caused by: java.lang.NoSuchMethodError: org.jdbi.v3.core.config.JdbiCaches.<init>(org.jdbi.v3.core.config.ConfigRegistry)
		at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:340)
		at java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:214)
		at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
		at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098)
		... 42 more
Caused by: java.lang.NoSuchMethodException: no such constructor: org.jdbi.v3.core.config.JdbiCaches.<init>()void/newInvokeSpecial
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:961)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
	at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
	at org.jdbi.v3.core.config.ConfigRegistry.lambda$configFactory$4(ConfigRegistry.java:96)
	... 39 more
Caused by: java.lang.NoSuchMethodError: org.jdbi.v3.core.config.JdbiCaches.<init>()
	at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:340)
	at java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:214)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098)
	... 42 more

2021-08-25 15:29:40,114 INFO  [io.qua.htt.access-log] (executor-thread-0) 172.17.0.1 - - 25/Aug/2021:15:29:40 +0000 "GET / HTTP/1.1" 500 2954
```

**Comment by x80486** [comment]
You should take a look at #1890 (and #1797) — then probably close this one 😉

**Comment by stevenschlansker** [comment]
Hi @henryx , since this issue was opened, Jdbi added native-image metadata to our builds and now has a CI step showing it works. Please test with the latest releases and feel free to reopen this issue if you think it's still relevant.
