### ISSUE TITLE
Oracle and optional "?" arguments having value of null: invalid column type

### ISSUE THREAD

**Issue by igortochansky** [jdbi/jdbi#1931]
when argument is optional and has value of null
:argument?.property

jdbi version: 3.21.0
oracle jdbc driver version: 21.1.0.0.0

Caused by: java.sql.SQLException: Invalid column type: 1111
	at oracle.jdbc.driver.OracleStatement.getInternalType(OracleStatement.java:4822)
	at oracle.jdbc.driver.OraclePreparedStatement.setNullCritical(OraclePreparedStatement.java:4564)
	at oracle.jdbc.driver.OraclePreparedStatement.setNull(OraclePreparedStatement.java:4548)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setNull(OraclePreparedStatementWrapper.java:941)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setNull(HikariProxyPreparedStatement.java)
	at org.jdbi.v3.core.argument.NullArgument.apply(NullArgument.java:48)
	at org.jdbi.v3.core.statement.ArgumentBinder$Prepared.lambda$prepareBinder$10(ArgumentBinder.java:225)
	at org.jdbi.v3.core.statement.ArgumentBinder.lambda$wrapExceptions$6(ArgumentBinder.java:153)

**Comment by igortochansky** [comment]
Similar to: https://github.com/jdbi/jdbi/issues/97
