### ISSUE TITLE
GetGeneratedKeys not working for kotlin dataclass without arguments

### ISSUE THREAD

**Issue by dylanwilder** [jdbi/jdbi#2012]
Get an error trying to map to a row (all columns) using just @GetGeneratedKeys.  Specifying every key works per commented code.
```kotlin
    data class Row(
        val component_id: UUID,
        val component_name: String,
        val component_type: String,
        val creator: String,
        val created_at: Timestamp,
        val config: String,
    )

    interface DAO {

        @SqlUpdate(
            """
            INSERT INTO $TableName(component_id, component_name, component_type, creator, config) 
            VALUES (:componentId, :componentName, :componentType, :creator, :config)
            """
        )
//        @GetGeneratedKeys(
//            "component_id",
//            "component_name",
//            "component_type",
//            "creator",
//            "created_at",
//            "config"
//        )
        @GetGeneratedKeys
        fun new(
            componentId: UUID = UUID.randomUUID(),
            componentName: String,
            componentType: String,
            creator: String,
            config: String
        ): Row
}
```

The error
```
 java.lang.IllegalArgumentException: Mapping constructor-injected type Row matched columns for constructor parameters [parameter #0 component_id of fun <init>(java.util.UUID, kotlin.String, kotlin.String, kotlin.String, java.sql.Timestamp, kotlin.String): com.spotify.onemodelapi.db.Components.Row, parameter #4 created_at of fun <init>(java.util.UUID, kotlin.String, kotlin.String, kotlin.String, java.sql.Timestamp, kotlin.String): com.spotify.onemodelapi.db.Components.Row], but not for [parameter #1 component_name of fun <init>(java.util.UUID, kotlin.String, kotlin.String, kotlin.String, java.sql.Timestamp, kotlin.String): com.spotify.onemodelapi.db.Components.Row, parameter #2 component_type of fun <init>(java.util.UUID, kotlin.String, kotlin.String, kotlin.String, java.sql.Timestamp, kotlin.String): com.spotify.onemodelapi.db.Components.Row, parameter #3 creator of fun <init>(java.util.UUID, kotlin.String, kotlin.String, kotlin.String, java.sql.Timestamp, kotlin.String): com.spotify.onemodelapi.db.Components.Row, parameter #5 config of fun <init>(java.util.UUID, kotlin.String, kotlin.String, kotlin.String, java.sql.Timestamp, kotlin.String): com.spotify.onemodelapi.db.Components.Row]
        at org.jdbi.v3.core.kotlin.KotlinMapper.specialize0(KotlinMapper.kt:118)
        at org.jdbi.v3.core.kotlin.KotlinMapper.specialize(KotlinMapper.kt:75)
        at org.jdbi.v3.core.result.ResultSetResultIterator.<init>(ResultSetResultIterator.java:38)
        at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:54)
        at org.jdbi.v3.core.result.ResultIterable.findFirst(ResultIterable.java:203)
        at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.mappedResult(ResultReturner.java:277)
        at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$new$0(SqlUpdateHandler.java:62)
        at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$configureReturner$3(SqlUpdateHandler.java:90)
        at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:178)
...
```

**Comment by hgschmie** [comment]
postgres? Add a "RETURNING *" to the insert statement. :-)

The error message is convoluted and annoying but correct. By default, "INSERT" only returns a single value that it could map to the first column but ran out of additional values for the other columns (which are non-null).

**Comment by hgschmie** [comment]
improved the error message to be more clear.
