### ISSUE TITLE
JDBI 3 - Handle.close() throws Failed to clear transaction status on close error

### ISSUE THREAD

**Issue by lohitpradhan** [jdbi/jdbi#2065]
We use jdbi api in our drop wizard based application which internally uses tomcat connection pool for db operations.
Below code snippet is used to delete user from our oracle database.

```
jdbi.useHandle(
 handle ->
 handle.createUpdate("DROP USER XXXXX CASCADE")
 .execute());
```

The above code throws an error -

```
Caused by: org.jdbi.v3.core.CloseException: Failed to clear transaction status on close
at org.jdbi.v3.core.Handle.close(Handle.java:183)
at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:358)
at org.jdbi.v3.core.Jdbi.useHandle(Jdbi.java:373)
at com.test.db.DBSchemaProviderImpl.deleteDBSchema(DBSchemaProviderImpl.java:57)
... 7 common frames omitted
Caused by: org.jdbi.v3.core.transaction.TransactionException: Failed to test for transaction status
at org.jdbi.v3.core.transaction.LocalTransactionHandler$BoundLocalTransactionHandler.isInTransaction(LocalTransactionHandler.java:194)
at org.jdbi.v3.core.Handle.isInTransaction(Handle.java:346)
at org.jdbi.v3.core.Handle.close(Handle.java:154)
... 10 common frames omitted
Caused by: java.sql.SQLException: Connection has already been closed.
at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:121)
at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79)
at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
at com.sun.proxy.$Proxy110.getAutoCommit(Unknown Source)
at org.jdbi.v3.core.transaction.LocalTransactionHandler$BoundLocalTransactionHandler.isInTransaction(LocalTransactionHandler.java:192)
... 12 common frames omitted
```

Please suggest a way of working with this code. Thanks

**Comment by hgschmie** [comment]
Hi @lohitpradhan,

Thank you for filing an issue with the JDBI project. We appreciate any feedback! To be able to investigate this further, please provide

- version of JDBI that you are using
- version of the tomcat pool library
- version of the oracle driver
- any settings that you have within the connection pool or the driver

It is very difficult for us to investigate any problems if we do not know what setup and versions you are using.

**Comment by lohitpradhan** [comment]
version of JDBI that you are using : v3
```
 <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-jdbi3</artifactId>
      <version>2.0.29</version>
    </dependency>
```
version of the tomcat pool library: 
 ```
<dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-db</artifactId>
      <version>2.0.29</version>
    </dependency>
```
version of the oracle driver : 
```
 <dependency>
      <artifactId>ojdbc8</artifactId>
      <groupId>com.oracle.database.jdbc</groupId>
      <version>21.3.0.0</version>
    </dependency>
```
any settings that you have within the tomcat connection pool or the driver:
    ```
    validationQueryString: "SELECT 1 from dual"
        validationQueryTimeout: 10s
        initialSize: 5
        minSize: 5
        maxSize: 10
        removeAbandoned : true
        removeAbandonedTimeout : 1m
        maxConnectionAge: 30m
        maxWaitForConnection: 300s
        checkConnectionOnBorrow: true
```

**Comment by lohitpradhan** [comment]
Thanks for this change, it really helps a lot. can you please let me know the release version which has this change ?

**Comment by lohitpradhan** [comment]
@hgschmie may i know how to uptake these changes or which version should i use ?
