### ISSUE TITLE
Reflection of lambda classes is not supported in GraalVM native image

### ISSUE THREAD

**Issue by Eng-Fouad** [jdbi/jdbi#2071]
I tried to use JDBI with Quarkus in native mode. By including all classes that are accessed via reflection to [reflection-config.json](https://gist.github.com/Eng-Fouad/7b5925481dd391fcc74487a68484b987), I was able to run it successfully.

However, I still got this exception (as warning) at runtime upon calling:

    Jdbi jdbi = Jdbi.create(agroalDataSource).installPlugin(new SqlObjectPlugin());

```
2022-07-18 09:33:32,935 [] WARNING [com.git.ben.caf.cac.LocalLoadingCache] (main) Cannot determine if CacheLoader can bulk load: java.lang.NoSuchMethodException: org.jdbi.v3.core.statement.CachingSqlParser$$Lambda$1a0f8d592d890e8f26473320a5cdb05c88cf7099.loadAll(java.lang.Iterable)
        at java.lang.Class.getMethod(DynamicHub.java:2227)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.hasLoadAll(LocalLoadingCache.java:182)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.newBulkMappingFunction(LocalLoadingCache.java:160)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.<init>(BoundedLocalCache.java:3761)
        at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:1104)
        at org.jdbi.v3.core.statement.CachingSqlParser.<init>(CachingSqlParser.java:30)
        at org.jdbi.v3.core.statement.CachingSqlParser.<init>(CachingSqlParser.java:25)
        at org.jdbi.v3.core.statement.ColonPrefixSqlParser.<init>(ColonPrefixSqlParser.java:41)
        at org.jdbi.v3.core.statement.SqlStatements.<init>(SqlStatements.java:53)
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:205)
        at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:76)
        at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
        at java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
        at org.jdbi.v3.core.config.ConfigRegistry.lambda$configFactory$3(ConfigRegistry.java:100)
        at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$function$4(Unchecked.java:76)
        at org.jdbi.v3.core.config.ConfigRegistry.get(ConfigRegistry.java:78)
        at org.jdbi.v3.core.config.ConfigRegistry.<init>(ConfigRegistry.java:47)
        at org.jdbi.v3.core.Jdbi.<init>(Jdbi.java:58)
        at org.jdbi.v3.core.Jdbi.create(Jdbi.java:109)
        at org.jdbi.v3.core.Jdbi.create(Jdbi.java:93)
```

This happened because of accessing lambda class `this::internalParse` by Reflection which was omitted from the native image by GraalVM compiler, as GraalVM does not support including lambda class in `reflection-config.json` yet: https://stackoverflow.com/a/73033351/597657

https://github.com/jdbi/jdbi/blob/ef3b9eb31557ba34c06ff62c127b2d4ca4ad836d/core/src/main/java/org/jdbi/v3/core/statement/CachingSqlParser.java#L30

https://github.com/ben-manes/caffeine/blob/37c51d5c22b8003367e179db283d427c63b5d2e6/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalLoadingCache.java#L229

Fix PR is provided: (#2070)

https://github.com/jdbi/jdbi/blob/e21e553ea26cfdf87c7a9b94f3958cc08fd8cb90/core/src/main/java/org/jdbi/v3/core/statement/CachingSqlParser.java#L30

https://github.com/jdbi/jdbi/blob/e21e553ea26cfdf87c7a9b94f3958cc08fd8cb90/core/src/main/java/org/jdbi/v3/core/statement/CachingSqlParser.java#L49-L54

**Comment by Eng-Fouad** [comment]
The solution was simple. The default method `CacheLoader.loadAll` has to be included into `reflection-config.json`:

    {"name":"com.github.benmanes.caffeine.cache.CacheLoader","methods":[{"name":"loadAll","parameterTypes":["java.lang.Iterable"]}]}
