### ISSUE TITLE
@PropagateNull(value = "...") does not work with nested beans.

### ISSUE THREAD

**Issue by hgschmie** [jdbi/jdbi#2102]
Consider code where a bean takes another bean on it's c'tor:

```
class Foo {
   private final Bar bar;
   class Foo(Bar bar) {
     this.bar = bar;
   }
}


@PropagateNull("id")
class Bar {
  private final Long id;
  class Bar(Long id) {
    this.id = id;
  }
}
  ```

and some sql query that fetches this data as a single, flat query:

```
@SqlQuery("SELECT bar.id AS bar_id FROM bar")
List<Foo> getNestedBars();
```

This should work and any `null` values in the `bar` table should be mapped onto a `Foo` that only contains a null, not an empty `Bar`. But it doesn't. The nested check will try to resolve `id` from a result set that only contains `bar_id`, resulting in a disappointing

```
org.jdbi.v3.core.result.ResultSetException: Error thrown mapping result set into return type [statement:"SELECT bar_id AS bar_id FROM bar ;", arguments:{positional:{0:0}, named:{}, finder:[]}]

	at org.jdbi.v3.core.result.ResultSetResultIterator.next(ResultSetResultIterator.java:85)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.jdbi.v3.core.result.ResultIterator.forEachRemaining(ResultIterator.java:39)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:297)
	at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.mappedResult(ResultReturner.java:275)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:61)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:187)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:27)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.lambda$invoke$0(SqlObjectInitData.java:132)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:26)
	at org.jdbi.v3.core.LazyHandleSupplier.lambda$invokeInContext$1(LazyHandleSupplier.java:79)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:26)
	at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:78)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.call(SqlObjectInitData.java:138)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.invoke(SqlObjectInitData.java:132)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$attach$2(SqlObjectFactory.java:108)
	at jdk.proxy2/jdk.proxy2.$Proxy24.selectA(Unknown Source)
	at com.example.demo.dao.DaoATest.lambda$testSelectA$1(DaoATest.java:57)
	at org.jdbi.v3.core.Jdbi.callWithExtension(Jdbi.java:491)
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:478)

Caused by: org.postgresql.util.PSQLException: The column name id was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2957)
	at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:2948)
	at org.jdbi.v3.core.mapper.reflect.internal.PojoMapper.lambda$propagateNull$9(PojoMapper.java:168)
	at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$function$4(Unchecked.java:76)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.jdbi.v3.core.mapper.reflect.internal.PojoMapper.propagateNull(PojoMapper.java:166)
	at org.jdbi.v3.core.mapper.reflect.ConstructorMapper.lambda$specialize0$8(ConstructorMapper.java:272)
	at org.jdbi.v3.core.mapper.reflect.ConstructorMapper.lambda$specialize0$8(ConstructorMapper.java:278)
	at org.jdbi.v3.core.result.ResultSetResultIterator.next(ResultSetResultIterator.java:83)
```

While the nested mapper correctly resolves the id column as `bar_id`, it does not correctly propagate the annotated `"id"` value.

**Comment by hgschmie** [comment]
Resolved by #2107
