### ISSUE TITLE
Error encountered while converting json string to List during JSON deserialization in JDBI 3

### ISSUE THREAD

**Issue by satviksach** [jdbi/jdbi#2395]
Context:
I'm facing an issue with JSON deserialization in JDBI 3 while using the jdbi3-json module with the Jackson2 plugin. My goal is to map a JSON column to a List<ColumnMetadata> field, but I'm encountering an error when trying to convert the JSON string to a List object. To provide further context, here is the schema of the table involved:

Table Schema:

    Table Name: TableConfig
    Columns:
        organizationId (int)
        tableName (string)
        columnMetadata (json)

Code Snippet - TableConfig Class:

```
public class TableConfig {
    private int organizationId;
    private String tableName;

    @Json
    private List<ColumnMetadata> columnMetadata;

    // Constructors, getters, and other methods
}

```
Code Snippet - ColumnMetadata Class:
```

public class ColumnMetadata {
    private String fieldName;
    private boolean visible;
    private Integer order;

    // Constructors, getters, and other methods
}

```
Code Snippet - DAO Get Call:

java[EDIT]
```
@SqlQuery("""
            SELECT *
            FROM OrganizationTableConfig
            WHERE OrganizationID = :organizationId AND TableName = :tableName
            """)
@RegisterBeanMapper(TableConfig.class)
    TableConfig getTableConfig(
            @Bind("organizationId") int organizationId,
            @Bind("tableName") String tableName
    );

```
Sample Error Message:
Upon attempting the JSON deserialization, I receive the following error message: "Cannot cast java.lang.String to java.util.List". This error prevents the successful conversion of the JSON string into the List<ColumnMetadata> field.

Expected Outcome:
I'm seeking assistance in resolving this issue and correctly performing the JSON deserialization for the columnMetadata field in the given TableConfig class while utilizing the jdbi3-json module. Any guidance, suggestions, or alternative approaches would be greatly appreciated.

**Comment by stevenschlansker** [comment]
Hi @satviksach , it looks like in your DAO:

```
@SqlQuery("SELECT * FROM TableConfig")
List getAllTableConfigs();
}
```

This uses the raw type `List`, so Jdbi does not know what type you want it to return. Try using a parameterized type like `List<TableConfig>`.

**Comment by natebranchapp** [comment]
Better question is: Does JDBI support converting a `JSON` SQL column type that contains an JSON array (vs. an object) to a java `List<MyJson> listOfJsonObjects` Or only JSON objects?

**Comment by natebranchapp** [comment]
I should note, we are using MySQL 8.0 and I noticed this in the documentation:

https://jdbi.org/#jdbi3-json
> The feature has been tested with Postgres json columns and varchar columns in H2 and Sqlite.

**Comment by natebranchapp** [comment]
I wasn't able to get it to work with a simple JSON object either:

```
// Config
jdbi.installPlugin(new SqlObjectPlugin())
       .installPlugin(new Jackson2Plugin());
jdbi.getConfig(Jackson2Config.class).setMapper(objectMapper);

// POJO
class TableConfig {
    @Json
    ColumnMetadata columnMetadata;
}

// JDBI DAO
public interface TableConfigDao {
    @SqlQuery("""
            SELECT *
            FROM OrganizationTableConfig
            WHERE OrganizationID = :organizationId
              AND TableName = :tableName
            """)
    @RegisterBeanMapper(TableConfig.class)
    TableConfig getTableConfig(
            @Bind("organizationId") int organizationId,
            @Bind("tableName") String tableName
    );
```

Error:
```
java.lang.ClassCastException: Cannot cast java.lang.String to com.test.tableconfig.domain.ColumnMetadata
	at java.base/java.lang.Class.cast(Class.java:3889)
	at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$biConsumer$6(Unchecked.java:96)
	at org.jdbi.v3.core.mapper.reflect.internal.BeanPropertiesFactory$BeanPojoProperties$1.set(BeanPropertiesFactory.java:93)
	at org.jdbi.v3.core.mapper.reflect.internal.PojoProperties$PojoBuilder.set(PojoProperties.java:44)
	at org.jdbi.v3.core.mapper.reflect.internal.PojoMapper$BoundPojoMapper.map(PojoMapper.java:231)
	at org.jdbi.v3.core.result.ResultSetResultIterator.next(ResultSetResultIterator.java:81)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.jdbi.v3.core.result.ResultIterator.forEachRemaining(ResultIterator.java:39)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:326)
	at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.mappedResult(ResultReturner.java:286)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:65)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:196)
	at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:27)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.lambda$invoke$0(SqlObjectInitData.java:135)
	at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:75)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.call(SqlObjectInitData.java:141)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.invoke(SqlObjectInitData.java:135)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$attach$2(SqlObjectFactory.java:108)
	at org.jdbi.v3.core.internal.OnDemandExtensions.lambda$invoke$5(OnDemandExtensions.java:99)
	at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$function$4(Unchecked.java:76)
	at org.jdbi.v3.core.internal.OnDemandExtensions.invoke(OnDemandExtensions.java:99)
	at org.jdbi.v3.core.internal.OnDemandExtensions.lambda$createProxy$2(OnDemandExtensions.java:83)
	at org.jdbi.v3.core.Jdbi.callWithExtension(Jdbi.java:502)
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:489)
	at org.jdbi.v3.core.internal.OnDemandExtensions.lambda$createProxy$3(OnDemandExtensions.java:83)
	at jdk.proxy2/jdk.proxy2.$Proxy303.getTableConfig(Unknown Source)
```

**Comment by satviksach** [comment]
We were able to make it work. The issue was around our use of Lombok in the project. Adding `lombok.copyableannotations += org.jdbi.v3.json.Json` to `lombok.config` solved it.

**Comment by stevenschlansker** [comment]
Yes, mapping a JSON array to `List<T>` should work. Sounds like this is solved, so I will close.
