### ISSUE TITLE
No argument factory Exc

### ISSUE THREAD

**Issue by gregorst** [jdbi/jdbi#2497]
Hi,

I am using AbstractArgumentFactory like this:

`public class ListArgumentFactory extends AbstractArgumentFactory<List<String>> {

    public ListArgumentFactory() {
        super(Types.VARCHAR);
    }

    @Override
    protected Argument build(List<String> value, ConfigRegistry config) {
        ...
    }
}`

and then using this class like:

`... 
getHandle().registerArgument(new ListArgumentFactory());
...`

This is not longer working for me from version 3.35.0 onwards (3.34.0 works).

Exception is: org.jdbi.v3.core.statement.UnableToCreateStatementException: no argument factory for type java.util.List<...>

Stack:
at org.jdbi.v3.core.statement.PreparedBatch.lambda$buildArgument$1(PreparedBatch.java:103) ~[jdbi3-core-3.35.0.jar:3.35.0]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at org.jdbi.v3.core.statement.PreparedBatch.lambda$buildArgument$2(PreparedBatch.java:103) ~[jdbi3-core-3.35.0.jar:3.35.0]
        at org.jdbi.v3.core.statement.ArgumentBinder$Prepared.lambda$prepareBinder$3(ArgumentBinder.java:238) ~[jdbi3-core-3.35.0.jar:3.35.0]
        at org.jdbi.v3.core.statement.ArgumentBinder.lambda$wrapCheckedConsumer$4(ArgumentBinder.java:176) ~[jdbi3-core-3.35.0.jar:3.35.0]
        at org.jdbi.v3.core.statement.ArgumentBinder$Prepared.lambda$prepareBinder$10(ArgumentBinder.java:258) ~[jdbi3-core-3.35.0.jar:3.35.0]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at org.jdbi.v3.core.statement.ArgumentBinder$Prepared.lambda$prepareBinder$11(ArgumentBinder.java:258) ~[jdbi3-core-3.35.0.jar:3.35.0]
        at org.jdbi.v3.core.statement.ArgumentBinder$Prepared.bindNamed(ArgumentBinder.java:264) ~[jdbi3-core-3.35.0.jar:3.35.0]
        at org.jdbi.v3.core.statement.ArgumentBinder.bind(ArgumentBinder.java:68) ~[jdbi3-core-3.35.0.jar:3.35.0]
        at org.jdbi.v3.core.statement.PreparedBatch.internalBatchExecute(PreparedBatch.java:246) ~[jdbi3-core-3.35.0.jar:3.35.0]
        at org.jdbi.v3.core.statement.PreparedBatch.execute(PreparedBatch.java:122) ~[jdbi3-core-3.35.0.jar:3.35.0]

What would be the problem ? 

Thanks.

**Comment by stevenschlansker** [comment]
Hi, where you declare `AbstractArgumentFactory<List>` did you mean to declare `AbstractArgumentFactory<List<String>>` or are you intentionally using a raw type?

**Comment by gregorst** [comment]
Hi,

Yes. I am actually using List<String>

**Comment by stevenschlansker** [comment]
Ok, and in the error message you report,
```
Exception is: org.jdbi.v3.core.statement.UnableToCreateStatementException: no argument factory for type java.util.List<...>
```

what is the full message, i.e. what is the `...` parameter to List?

**Comment by hgschmie** [comment]
so I tried this:

```java
    @Test
    public void testRetrieveList() {
        final Jdbi db = h2Extension.getJdbi();
        try (Handle h = db.open()) {
            h.execute("create table foo (id identity primary key, v integer array)");
            h.registerArgument(new ListArgumentFactory());
            h.execute("insert into foo (id, v) values (1, ?)", List.of(1, 2));
            h.execute("insert into foo (id, v) values (2, ?)", List.of(4, 3, 2));
            h.execute("insert into foo (id, v) values (3, ?)", List.of(5, 6));

            List<Integer> result = h.createQuery("SELECT v FROM foo WHERE id = :id")
                    .bind("id", 2)
                    .mapTo(new GenericType<List<Integer>>() {})
                    .one();

            assertThat(result).isNotNull().hasSize(3).containsExactly(4, 3, 2);
        }
    }

    public static class ListArgumentFactory extends AbstractArgumentFactory<List<Integer>> {
        public ListArgumentFactory() {
            super(Types.INTEGER);
        }

        @Override
        protected Argument build(List<Integer> value, ConfigRegistry config) {
            return (position, statement, ctx) -> statement.setObject(position, value.toArray(new Integer[0]));
        }
    }
```

which works fine on 3.41.2. If you replace the `List<Integer>` with just `List`, it still works. 

I think we would need to see more of your specific problem.

**Comment by gregorst** [comment]
@stevenschlansker My parameter to List is String: List\<String\>

@hgschmie 
full class:

`public class ListArgumentFactory extends AbstractArgumentFactory<List\<String\>> {

    public ListArgumentFactory() {
        super(Types.VARCHAR);
    }

    @Override
    protected Argument build(List<String> value, ConfigRegistry config) {
        return (position, statement, ctx) -> {
            if (value == null) {
                statement.setNull(position, Types.NULL);
            } else {
                statement.setString(position, "[" + value.stream().map(s -> "\"" + s + "\"").collect(Collectors.joining(",")) + "]");
            }
        };
    }
}`

**Comment by hgschmie** [comment]
Oh, so you are just mapping this onto a string field, not an actual array column.

**Comment by hgschmie** [comment]
this works fine for me (added to TestArgumentFactory):

```
    @Test
    public void testMapToStringArgument2497() {
        final Jdbi db = h2Extension.getJdbi();
        try (Handle h = db.open()) {
            h.registerArgument(new ListArrayStringFactory());
            h.execute("insert into something (id, name) values (1, ?)", List.of("Hello", "World"));
            h.execute("insert into something (id, name) values (2, ?)", List.of("The", "quick", "brown", "fox"));
            h.execute("insert into something (id, name) values (3, ?)", List.of("Now", "is", "the", "time"));
            h.execute("insert into something (id, name) values (4, ?)", (List<String>) null);

            String result = h.createQuery("SELECT name FROM something WHERE id = :id")
                    .bind("id", 2)
                    .mapTo(String.class)
                    .one();

            assertThat(result).isEqualTo("[\"The\",\"quick\",\"brown\",\"fox\"]");

            int count = h.createQuery("SELECT count(1) FROM something")
                    .mapTo(Integer.class)
                    .one();

            assertThat(count).isEqualTo(4);
        }
    }

    public static class ListArrayStringFactory extends AbstractArgumentFactory<List<String>> {
        public ListArrayStringFactory() {
            super(Types.VARCHAR);
        }

        @Override
        protected Argument build(List<String> value, ConfigRegistry config) {
            return (position, statement, ctx) -> {
                if (value == null) {
                    statement.setNull(position, Types.NULL);
                } else {
                    statement.setString(position, "[" + value.stream().map(s -> "\"" + s + "\"").collect(Collectors.joining(",")) + "]");
                }
            };
        }
    }
```

I am a bit at a loss now. What database are you using? Maybe that make a difference. This is with the embedded h2.

**Comment by hgschmie** [comment]
see https://github.com/hgschmie/jdbi/commit/dd14a12c031de8bbd3458b989d21398afb893941 for my test code. if you want to try it out, get the "investigate-2497" branch from that repo.

**Comment by gregorst** [comment]
Hi, 
I am using MariaDb, version 10.4. 
But strange. How could database be the problem?
Currently I am using JDBI 3.34.0 and exact same code works.
Or is something with MariaDb (MySql) and exactly JDBI 3.34+

**Comment by gregorst** [comment]
After some more digging the problem is not with List of Strings as a parameter for argument factory but object:

```java
public static class ListParameterArgumentFactory extends AbstractArgumentFactory<List<UserParameterApi.Parameter>> {
        public ListParameterArgumentFactory() {
            super(Types.VARCHAR);
        }

        @Override
        protected Argument build(List<UserParameterApi.Parameter> value, ConfigRegistry config) {
            return (position, statement, ctx) -> {
                if (value == null) {
                    statement.setNull(position, Types.NULL);
                } else {
                    try {
                        statement.setString(position, objectMapper.writeValueAsString(value));
                    } catch (JsonProcessingException e) {
                        statement.setNull(position, Types.NULL);
                    }
                }
            };
        }
    }
```

**Comment by hgschmie** [comment]
I added some code that emulates this:

```java
    @Test
    public void testMapToObjectArgument2497() {
        final Jdbi db = h2Extension.getJdbi();
        db.registerArgument(new ListObjectFactory());

        try (Handle h = db.open()) {
            h.execute("insert into something (id, name) values (1, ?)",
                List.of(Parameters.thing("Hello"), Parameters.thing("World")));
            h.execute("insert into something (id, name) values (2, ?)",
                List.of(Parameters.thing("The"), Parameters.thing("quick"), Parameters.thing("brown"), Parameters.thing("fox")));
            h.execute("insert into something (id, name) values (3, ?)",
                List.of(Parameters.thing("Now"), Parameters.thing("is"), Parameters.thing("the"), Parameters.thing("time")));
            h.execute("insert into something (id, name) values (4, ?)", (List<Thing>) null);

            String result = h.createQuery("SELECT name FROM something WHERE id = :id")
                .bind("id", 2)
                .mapTo(String.class)
                .one();

            assertThat(result).isEqualTo("[\"The\",\"quick\",\"brown\",\"fox\"]");

            int count = h.createQuery("SELECT count(1) FROM something")
                .mapTo(Integer.class)
                .one();

            assertThat(count).isEqualTo(4);
        }
    }

    public static class Parameters {
        public static Thing thing(String value) {
            return new Thing(value);
        }

        public static class Thing {
            private final String value;

            private Thing(String value) {
                this.value = value;
            }

            public String getValue() {
                return value;
            }
        }
    }

    public static class ListObjectFactory extends AbstractArgumentFactory<List<Parameters.Thing>> {
        public ListObjectFactory() {
            super(Types.VARCHAR);
        }

        @Override
        protected Argument build(List<Parameters.Thing> value, ConfigRegistry config) {
            return (position, statement, ctx) -> {
                if (value == null) {
                    statement.setNull(position, Types.NULL);
                } else {
                    statement.setString(position, "[" +
                        value.stream()
                            .map(Parameters.Thing::getValue)
                            .map(s -> "\"" + s + "\"")
                            .collect(Collectors.joining(","))
                        + "]");
                }
            };
        }
    }
```

Which works fine for me. At this point, I don't know how to continue. It seems to me that there is something specific to your code base that makes this "not work". Things I can think of:

- one of the classes (UserParameterApi, Parameter,  ListParameterArgumentFactory) is not static for a nested class or not public
- constructor is not accessible
- the argument factory is not actually registered when you thought it would get registered

Please post the exact error message that you get with the full stack trace (also "caused by ... " exceptions). Otherwise I am not sure on how to proceed.

**Comment by gregorst** [comment]
Hi, 

My classes are public static, constructor is accessible and code where I register argument is executed.
I register two different arguments on the same connection. I have removed one if this is the issue - same result.

Code where I register argument:

```java
public synchronized <T> void batchSave(List<T> list, ArgumentFactory argumentFactory) {
        db.useExtension(PersistenceDao.class, dao -> {
            if (argumentFactory != null) {
                dao.getHandle().registerArgument(argumentFactory);
            }
            dao.adminDataDao().batchSave2(list);
        });
    }
``` 

Here is full stack trace:
```
[2023-10-03 10:41:22,900] ERROR [c.k.r.a.i.UserResource] no argument factory for type java.util.List<com.konfigurator.entity.dto.api.UserParameterApi$Parameter> [statement:"insert into Admin.AdminData (data, number, pk, sk, created, modified, uid) values(:data, :number, :pk, :sk, now(), now(), :uid) on duplicate key update data = :data, number = :number, pk = :pk, sk = :sk, modified = now(), uid = :uid", arguments:{positional:{}, named:{}, finder:[]}]
org.jdbi.v3.core.statement.UnableToCreateStatementException: no argument factory for type java.util.List<com.konfigurator.entity.dto.api.UserParameterApi$Parameter> [statement:"insert into Admin.AdminData (data, number, pk, sk, created, modified, uid) values(:data, :number, :pk, :sk, now(), now(), :uid) on duplicate key update data = :data, number = :number, pk = :pk, sk = :sk, modified = now(), uid = :uid", arguments:{positional:{}, named:{}, finder:[]}]
	at org.jdbi.v3.core.statement.PreparedBatch.lambda$buildArgument$1(PreparedBatch.java:103) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at org.jdbi.v3.core.statement.PreparedBatch.lambda$buildArgument$2(PreparedBatch.java:103) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.statement.ArgumentBinder$Prepared.lambda$prepareBinder$3(ArgumentBinder.java:239) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.statement.ArgumentBinder.lambda$wrapCheckedConsumer$4(ArgumentBinder.java:177) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.statement.ArgumentBinder$Prepared.lambda$prepareBinder$10(ArgumentBinder.java:259) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.jdbi.v3.core.statement.ArgumentBinder$Prepared.lambda$prepareBinder$11(ArgumentBinder.java:259) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.statement.ArgumentBinder$Prepared.bindNamed(ArgumentBinder.java:265) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.statement.ArgumentBinder.bind(ArgumentBinder.java:69) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.statement.PreparedBatch.internalBatchExecute(PreparedBatch.java:246) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.statement.PreparedBatch.execute(PreparedBatch.java:122) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at com.konfigurator.service.dao.AdminDataDao.batchSave2(AdminDataDao.java:83) ~[KonfiguratorService-dev-SNAPSHOT.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$function$4(Unchecked.java:76) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.extension.ExtensionHandler.lambda$createForMethodHandle$4(ExtensionHandler.java:116) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.extension.ExtensionMetadata$ExtensionHandlerInvoker.lambda$invoke$0(ExtensionMetadata.java:345) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.AbstractHandleSupplier.invokeInContext(AbstractHandleSupplier.java:36) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.extension.ExtensionMetadata$ExtensionHandlerInvoker.call(ExtensionMetadata.java:363) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.extension.ExtensionMetadata$ExtensionHandlerInvoker.invoke(ExtensionMetadata.java:346) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.extension.ExtensionFactoryDelegate.lambda$attach$0(ExtensionFactoryDelegate.java:118) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.internal.OnDemandExtensions.invoke(OnDemandExtensions.java:85) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.internal.OnDemandExtensions.lambda$createProxy$2(OnDemandExtensions.java:71) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.Jdbi.callWithExtension(Jdbi.java:544) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:526) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.internal.OnDemandExtensions.lambda$createProxy$3(OnDemandExtensions.java:71) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at jdk.proxy4.$Proxy139.batchSave2(Unknown Source) ~[?:?]
	at com.konfigurator.service.admin.EnterpriseAdminService.lambda$batchSave$2(EnterpriseAdminService.java:52) ~[KonfiguratorService-dev-SNAPSHOT.jar:?]
	at org.jdbi.v3.core.Jdbi.lambda$useExtension$10(Jdbi.java:561) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.Jdbi.callWithExtension(Jdbi.java:544) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:531) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at org.jdbi.v3.core.Jdbi.useExtension(Jdbi.java:560) ~[jdbi3-core-3.41.2.jar:3.41.2]
	at com.konfigurator.service.DatabaseService.useExtension(DatabaseService.java:109) ~[KonfiguratorService-dev-SNAPSHOT.jar:?]
	at com.konfigurator.service.admin.EnterpriseAdminService.batchSave(EnterpriseAdminService.java:48) ~[KonfiguratorService-dev-SNAPSHOT.jar:?]
	at com.konfigurator.service.ApiService.createUserParameters(ApiService.java:1342) ~[KonfiguratorService-dev-SNAPSHOT.jar:?]
	at com.konfigurator.rest.api.impl.UserResource.createUserParameters(UserResource.java:42) ~[KonfiguratorCore-dev-SNAPSHOT.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:546) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:435) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:396) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:398) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:338) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) ~[resteasy-jaxrs-3.15.2.Final.jar:3.15.2.Final]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[jetty-servlet-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:292) ~[websocket-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[?:?]
	at com.konfigurator.filter.ConfiguratorRequestFilter.doFilter(ConfiguratorRequestFilter.java:56) ~[KonfiguratorCore-dev-SNAPSHOT.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[?:?]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[?:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[?:?]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[?:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191) ~[?:?]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[?:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[?:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[?:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[?:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[?:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[?:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[?:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[?:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[?:?]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by hgschmie** [comment]
(sorry, fell behind a bit on looking at issues)

That looks like a different stack trace than what you described before.

In any case, I could reproduce the problem and it looks like a bug.

**Comment by hgschmie** [comment]
Congratulations, you found an incredible obscure limitation in the interaction between the extension framework (sqlobject) and the fluent (core) API. This is what happens:

- When you create the dao (with `db.useExtension`), the framework creates what is called an "ExtensionContext" for every method on the dao object. More specifically, it creates a different extension context for `getHandle()` and one for `batchSave2`. 
- The extension context is an aggregation of the extension method description and a configuration object specifically for this method. This is necessary because any annotation on the dao object methods modifies this configuration and per-method annotations must not interfere with each other.
- when you call `dao.getHandle()`, you receive the handle which has been configured to use the extension context for the `getHandle()` method. Calling `.registerArgument()` on the handle registers the argument factory in the configuration object for this specific method *but not globally for the whole dao*.
- then calling `dao.batchSave2` uses the configuration object from its extension context which does not have the argument factory and that is what causes the error.

Ok, I did not see that coming. :-) 

I am not sure that this is fixable and I would call this a known limitation of the extension framework (and in addition of the SqlObject framework). The configuration isolation between extension methods is intentional (this is how the annotations work) and by the time one can call `dao.getHandle()`, the configuration instances have already been created. 

Rewriting the code like this makes it work:

```java
public synchronized <T> void batchSave(List<T> list, ArgumentFactory argumentFactory) {
    db.withHandle(h -> {
        if (argumentFactory != null) {
            h.registerArgument(argumentFactory);
        }

        PersistenceDao dao = h.attach(PersistenceDao.class);
        dao.adminDataDao().batchSave2(list);
        return null;
    });
}
```

Here you stay in the "fluent world" for registering the argument factory and when you switch to the sqlobject world (by calling `h.attach`, the object is created with the argument factory in its configuration, so all methods receive the configuration and calling `.batchSave2` works.

**Comment by hgschmie** [comment]
You could (but really, you shouldn't) also do this, but it is somewhat of an abuse of the API:

```java
public synchronized <T> void batchSave(List<T> list, ArgumentFactory argumentFactory) {
        db.useExtension(PersistenceDao.class, dao -> {
            Handle h = dao.getHandle();
            if (argumentFactory != null) {
                h.registerArgument(argumentFactory);
            }
            PersistenceDao dao2 = h.attach(PersistenceDao.class);
            dao2.adminDataDao().batchSave2(list);
        });
    }
```

but you are better off rewriting the code as shown above.

**Comment by gregorst** [comment]
well, I'm full of surprises :)
I'm glad you found out what's causing the error.
I'll try it right away

thanks for digging into this.

**Comment by gregorst** [comment]
it works!
but yes, it would be great if you could use dao.getHandle()
I'm ok with your suggestion.

Closing.

Thank you.

**Comment by hgschmie** [comment]
I added some clarification to the docs. This is one of those grey areas where two pieces of the code combined work against each other and fixing this is basically impossible without a major rewrite. Glad that this solves your problem. Thank you for using Jdbi
