### ISSUE TITLE
NoSuchMapperException for Vavr Option with Java 21

### ISSUE THREAD

**Issue by diversit** [jdbi/jdbi#2527]
We're running into an issue when building our application with Java 21.
All db tests fail due to a `NoSuchMapperException` for the Vavr Option type

```
org.jdbi.v3.core.mapper.NoSuchMapperException: No mapper for raw Option type
	at org.jdbi.v3.vavr.VavrOptionMapper.lambda$factory$0(VavrOptionMapper.java:43)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.jdbi.v3.vavr.VavrOptionMapper.lambda$factory$1(VavrOptionMapper.java:43)
	at org.jdbi.v3.core.mapper.QualifiedColumnMapperFactory.lambda$adapt$0(QualifiedColumnMapperFactory.java:48)
	at org.jdbi.v3.core.mapper.ColumnMappers.findFor(ColumnMappers.java:216)
	at org.jdbi.v3.core.statement.StatementContext.findColumnMapperFor(StatementContext.java:276)
	at org.jdbi.v3.core.mapper.reflect.ConstructorMapper.createSpecializedRowMapper(ConstructorMapper.java:229)
	at org.jdbi.v3.core.mapper.reflect.ConstructorMapper.specialize(ConstructorMapper.java:189)
	at org.jdbi.v3.core.result.internal.ResultSetResultIterator.<init>(ResultSetResultIterator.java:40)
```

Building with Maven:
```
Maven home: /Users/dhl/.m2/wrapper/dists/apache-maven-3.9.3-bin/326f10f4/apache-maven-3.9.3
Java version: 21.0.1, vendor: Eclipse Adoptium, runtime: /Users/dhl/.sdkman/candidates/java/21.0.1-tem
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "13.4", arch: "aarch64", family: "Mac"
```

All tests do succeed with Java 17 (Temurin 17.0.8).

The problem seems to be in the `GenericTypeReflector` in the `geantyref` dependency.
When `VavrOptionMapper` calls `GenericTypes.findGenericParameter(..)` that method falls back to `GenericTypeReflector.getTypeParameter(type, parameterizedSupertype.getTypeParameters()[n])` since the `type` argument is not a `Class`.
In `getTypeParameter(..)` the statement `AnnotatedType typeParameter = getTypeParameter(annotate(type), variable);` returns the `Option` type in Java 17 (e.g. String), but in Java 21 this is `null`.
This causes the `Optional` to be empty and therefore `VavrOptionMapper` throws the `NoSuchMapper` exception.

**Comment by pertyjons** [comment]
We have a similar problem with java 21 but with `useStream(...)` and with `java.util.Optional`, seems like the same method is used and failing:

```
org.jdbi.v3.core.mapper.NoSuchMapperException: No mapper for raw Optional type
	at org.jdbi.v3.core.mapper.OptionalMapperFactory.lambda$create$3(OptionalMapperFactory.java:76)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.jdbi.v3.core.mapper.OptionalMapperFactory.create(OptionalMapperFactory.java:76)
	at org.jdbi.v3.core.mapper.OptionalMapperFactory.lambda$build$0(OptionalMapperFactory.java:60)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.jdbi.v3.core.mapper.OptionalMapperFactory.build(OptionalMapperFactory.java:60)
	at org.jdbi.v3.core.mapper.QualifiedColumnMapperFactory.lambda$adapt$0(QualifiedColumnMapperFactory.java:48)
	at org.jdbi.v3.core.mapper.ColumnMappers.findFor(ColumnMappers.java:216)
	at org.jdbi.v3.core.statement.StatementContext.findColumnMapperFor(StatementContext.java:276)
	at org.jdbi.v3.core.mapper.reflect.ConstructorMapper.createSpecializedRowMapper(ConstructorMapper.java:229)
	at org.jdbi.v3.core.mapper.reflect.ConstructorMapper.specialize(ConstructorMapper.java:189)
	at org.jdbi.v3.core.mapper.JoinRowMapper.specialize(JoinRowMapper.java:51)
	at org.jdbi.v3.core.result.internal.ResultSetResultIterator.<init>(ResultSetResultIterator.java:40)
	at org.jdbi.v3.core.result.internal.ResultSetResultIterable.iterator(ResultSetResultIterable.java:54)
	at org.jdbi.v3.core.result.ResultIterable.lambda$map$2(ResultIterable.java:123)
	at org.jdbi.v3.core.result.ResultIterable.lambda$map$2(ResultIterable.java:123)
	at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:266)
	at org.jdbi.v3.core.result.ResultIterable.withStream(ResultIterable.java:300)
	at org.jdbi.v3.core.result.ResultIterable.useStream(ResultIterable.java:281)```

**Comment by pertyjons** [comment]
I found the actual problem and just make a note of it here if anyone else have the same problem.

We had a record with a default constructor annotated with `@JdbiConstructor` like this and the record itself had an Optional<Long> among other things:

```
@JdbiConstructor
  public TransactionVerificationEntity {}

```

Changing that to explicitly a full constructor with the same annotation solved the problem so I suppose there is some things changed in java 21.

This worked in earlier java version 20 and down to 17.

**Comment by stevenschlansker** [comment]
Is it possible to provide a small test case that shows the problem you were having? I am surprised it would change from Java 17 to 21.

**Comment by pertyjons** [comment]
Sorry, I made a try but it's to many relations to pin out the actual code generating the error. The query itself is join with four tables and a lot of relations.

If it's an actual bug I suppose it will be found and hopefully in a more clear way. We may as well have some things on our side creating this.

**Comment by wendigo** [comment]
I'm facing the same problem:

```
Caused by: java.lang.IllegalArgumentException: Could not find column mapper for type 'java.util.List' of parameter
```

JDK 21.0.1 (Temurin)

**Comment by wendigo** [comment]
I found something really interesting.

When code is compiled with JDK 21 (but `--release 17`) it fails when executed on JDK 17. When compiled with JDK 17 and executed with 17 it works fine.

**Comment by stevenschlansker** [comment]
I tried to reproduce your problems with the generic constructor for records in jdk 21, but didn't get it on the first try:

```
import java.util.Arrays;
import java.util.Optional;

public record Test(Optional<String> s, Optional<Integer> i) {
    public static void main(String... args) {
        System.out.println(Arrays.asList(Test.class.getConstructors()[0].getGenericParameterTypes()));
    }
}
```

```
[java.util.Optional<java.lang.String>, java.util.Optional<java.lang.Integer>]
```

**Comment by diversit** [comment]
Someone was able to create a simple test case. See my [StackOverflow question](https://stackoverflow.com/questions/77496020/incompatible-changes-in-generics-in-java-21#77496020). 

It is an issue with Java 21. I created a bug report with ID 9076247.

JDBI requires the `@JdbiConstructor` annotation on a record constructor. If JDBI would be able to use the record's default constructor without this annotation it should also work as the test case shows the generic types are only lost in the record's compact constructor.

The workaround is to explicitly define a canonical constructor on the record with all properties.

**Comment by stevenschlansker** [comment]
Thank you for reporting the issue to the JDK. Since this is a compiler bug, not a Jdbi bug, I will call this bug closed.

**Comment by diversit** [comment]
The java bug has been evaluated and is now visible as [JDK-8320575](https://bugs.java.com/bugdatabase/view_bug?bug_id=JDK-8320575).
