### ISSUE TITLE
@BindBean for class with Unit<?> property leads to StackOverflowError

### ISSUE THREAD

**Issue by johnarrr** [jdbi/jdbi#2582]
I am having trouble using `@BindBean` with a class that contains a property of type `Unit<?>`. In short, binding a single property works but binding the object does not.

This works
```
@SqlUpdate("INSERT INTO unit_bean_test (unit) VALUES (:unit)")
@GetGeneratedKeys(value = "id")
long insert(@Bind("unit") Unit<?> unit);
```

This generates a `StackOverflowError`
```
@SqlUpdate("INSERT INTO unit_bean_test (unit) VALUES (:unit)")
@GetGeneratedKeys(value = "id")
long insert(@BindBean UnitBean unitBean);
```

Should this be possible?

More details are below. If it helps, I tracked it to the io.leangen.geantyref.GenericTypeReflector.reduceBounded call at BeanPropertiesFactory line 164. The problem seems to be when it tries to resolve a type for `Quantity<?>`, which Unit extends.

The last 2 cycles in the stacktrace:
```
java.lang.StackOverflowError
	at io.leangen.geantyref.TypeVisitor.visitParameterizedType(TypeVisitor.java:26)
	at io.leangen.geantyref.GenericTypeReflector.transform(GenericTypeReflector.java:1131)
	at io.leangen.geantyref.GenericTypeReflector$3.visitCaptureType(GenericTypeReflector.java:1177)
	at io.leangen.geantyref.GenericTypeReflector.transform(GenericTypeReflector.java:1143)
	at io.leangen.geantyref.TypeVisitor.lambda$visitParameterizedType$0(TypeVisitor.java:27)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at io.leangen.geantyref.TypeVisitor.visitParameterizedType(TypeVisitor.java:28)
	at io.leangen.geantyref.GenericTypeReflector.transform(GenericTypeReflector.java:1131)
	at io.leangen.geantyref.GenericTypeReflector$3.visitCaptureType(GenericTypeReflector.java:1177)
	at io.leangen.geantyref.GenericTypeReflector.transform(GenericTypeReflector.java:1143)
	at io.leangen.geantyref.TypeVisitor.lambda$visitParameterizedType$0(TypeVisitor.java:27)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
```

Example class:
```
import javax.measure.Unit;

public class UnitBean {
    private long id;
    private Unit<?> unit;

    public UnitBean(Unit<?> unit) {
        this.unit = unit;
    }

    public UnitBean(long id, Unit<?> unit) {
        this.id = id;
        this.unit = unit;
    }

    public long getId() {
        return id;
    }

    public Unit<?> getUnit() {
        return  unit;
    }
}
```

**Comment by stevenschlansker** [comment]
The StackOverflowError sounds like a bug, although Jdbi does not have any knowledge of `javax.measure.Unit` out of the box - is it supported by your db driver natively, or do you have a custom argument factory?

It would be helpful to provide a self-contained executable sample to reproduce the problem, if possible.

Thanks for the report!

**Comment by hgschmie** [comment]
`Unit<?>` seems to be an interface (https://unitsofmeasurement.github.io/unit-api/apidocs/javax/measure/Unit.html), so you would need a concrete implementation for the mapper. You could write some sort of polymorphic mapper to support any unit type but I would be interested in what unit you are trying to convert and how.

**Comment by johnarrr** [comment]
Thank you for the quick followup. I'm extracting the relevant parts into a standalone project and will share that soon.

**Comment by stevenschlansker** [comment]
Ok, this does look to be a bug in geantyref. I've filed and linked an issue over there.

**Comment by hgschmie** [comment]
See https://github.com/leangen/geantyref/issues/20

**Comment by johnarrr** [comment]
Thank you!
