### ISSUE TITLE
Can not set static final field

### ISSUE THREAD

**Issue by mvysny** [jdbi/jdbi#2607]
If the select returns a column with the same name as a public static final field in the bean, JDBI will try to write the value to that column and will fail with:
```
Caused by: java.lang.IllegalAccessException: Can not set static final com.gitlab.mvysny.jdbiorm.Property field com.gitlab.mvysny.jdbiorm.NestedJoinOutcome.DEPARTMENT_NAME to java.lang.String
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at java.base/jdk.internal.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
	at java.base/java.lang.reflect.Field.set(Field.java:799)
	at org.jdbi.v3.core.mapper.reflect.FieldMapper$BoundFieldMapper.writeField(FieldMapper.java:285)
	... 57 more
```

In the example above, I have a `SELECT x as department_name from y` mapping values to a bean with a `public static final String DEPARTMENT_NAME = "foo";` field via `FieldMapper`.

Reasoning: in jdbi-orm I'm recommending the users to create a `public static final Property<> ID` fields which allows you to programmatically create Conditions such as `Person.ID.lt(25)`. However, since there is a database column named ID, JDBI's FieldMapper tries to write the value both to the instance field `id` and the static final field `ID` and fails.

I believe that JDBI should ignore static fields in general, or at least static final fields.

Meanwhile, is there a workaround/configuration which would allow me to ignore such fields please?

JDBI 3.43.0

**Comment by mvysny** [comment]
I've worked around the problem by copying the FieldMapper class to jdbi-orm and patching it to ignore static fields; that works very well. A proper solution would probably add a line to FieldMapper.createSpecializedRowMapper() and would call a new `Predicate<Field> mappedFieldFilter` in `ReflectionMappers`.

**Comment by stevenschlansker** [comment]
Thanks for reporting this. I think we should filter out static fields by default.

**Comment by stevenschlansker** [comment]
A fix for this issue (ignore all static fields) should be in the next release.

**Comment by mvysny** [comment]
Awesome, thank you so much for such a quick fix; and super-thanks for such an awesome library :+1:
