### ISSUE TITLE
Add support for suspending functions to SQL Objects

### ISSUE THREAD

**Issue by amr** [jdbi/jdbi#2690]
Hi, I'd love to propose that we add support for suspending functions to SQL objects. It's a missing piece in making SQL objects ready to adopt in Kotlin + Coroutines world.

```
interface MyDao {
  @SqlQuery("...")
  suspend fun findById(id: Long): MyObject
}
```

Since DB access is blocking, in a coroutine world, ideally that would be dispatched on a custom coroutines dispatcher. Example:

```
const val MY_DB_POOL_MAX_CONNECTIONS = 16

// Create a dispatcher of N threads where N is the number of DB connections
val dbDispatcher = Dispatchers. IO. limitedParallelism(MY_DB_POOL_MAX_CONNECTIONS)
jdbi.installPlugin(KotlinPlugin(enableCoroutineSupport = true, coroutineContext = dbDispatcher))
```

The generated proxy would pretty much work exactly the same as the non-suspend variant, except it would have to execute the DB access code it generates through the given dispatcher, which is achieved with:

```
withContext(coroutineContext) {
  // ... db access code ...
}
```

I'm interested to hear:
1. Does the above make sense? Any questions on specifics or why this is needed?
2. Can one use the extension framework to implement that or would it need modifying JDBI core?
3. If it needs modifying JDBI, are you interested in that? Should I try to submit a PR for that?

**Comment by stevenschlansker** [comment]
Hi @amr , I do not have much experience with Kotlin coroutines, but if there is community demand and support for it we're interested.

It sounds like your proposal mostly wraps around the existing extension. It should possible that you could use the `ExtensionHandlerCustomizer` hook that we provide to wrap the existing sqlobject infrastructure in your coroutine dispatcher.

Once the concept is proven out and you run it successfully for your own use case, we could consider introducing it into the Jdbi kotlin module to share with the community.

**Comment by amr** [comment]
Thanks for the feedback @stevenschlansker! The main missing thing that's maybe hard to provide externally is support for `suspend` functions, whose signature gets changed by the compiler.

This:
```
interface UserDao {
  @SQLUpdate(....)
  suspend fun insertUser(user: User): Unit
}
```

After it's compiled, becomes something like this on the byte-code level:
```
interface UserDao {
  @SQLUpdate
  fun insertUser(user: User, continuation: Continuation<*>): Object
}

// Return type Object allows the function to return either it's final value (unit here), or the special value COROUTINE_SUSPENDED
```

Because of this, JDBI becomes confused since the signature of a suspend function will always be different than what it expects:
```
UserDao.insertUser method is annotated with @SqlUpdate so should return void, boolean, or Number but is returning: java.lang.Object
org.jdbi.v3.sqlobject.UnableToCreateSqlObjectException: UserDao.insertUser method is annotated with @SqlUpdate so should return void, boolean, or Number but is returning: java.lang.Object
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.<init>(SqlUpdateHandler.java:74)
	at org.jdbi.v3.core.extension.UseAnnotationExtensionHandlerFactory.lambda$createExtensionHandler$1(UseAnnotationExtensionHandlerFactory.java:81)
```

**Comment by stevenschlansker** [comment]
So is the intention that you would invoke the dao method, Jdbi would load the results, and then call the continuation? or what is Jdbi supposed to do with the continuation parameter?

**Comment by amr** [comment]
> So is the intention that you would invoke the dao method, Jdbi would load the results, and then call the continuation? or what is Jdbi supposed to do with the continuation parameter?

Yes, in an ideal world, the underlying driver would be async, and JDBI would setup an async callback that calls the continuation once the result is available, and return [`COROUTINE_SUSPENDED`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.coroutines.intrinsics/-c-o-r-o-u-t-i-n-e_-s-u-s-p-e-n-d-e-d.html) to Kotlin coroutines scheduler letting it know the continuation will be resumed at some point in the future.

We know that blocking drivers are the norm though, so in 99% of the cases, teams will want JDBI to dispatch the blocking DB call on a separate thread, which is typically done by running the blocking operation on a dedicated coroutine dispatcher, like `Dispatchers.IO`, or a custom thread-pool that maybe matches the number of the DB pool connections (a typical setup).

JDBI would need to provide some way for developers to pass their own dispatcher so they have control over that aspect (block current thread or dispatch on a different pool or something else). Fortunately, this abstraction is already defined by Kotlin, it's called `CoroutineScope`, and JDBI would just need to accept it part of its coroutine configuration.

Without JDBI explicit support, it seems like we can still create their own classes that wrap JDBI sql objects and provide the required coroutine plumbing, but so far it's proving pretty repetitive and tedious.

**Comment by stevenschlansker** [comment]
> Yes, in an ideal world, the underlying driver would be async

That's something of a matter of opinion ;) but at least in Jdbi's world this isn't going to change anytime soon.

I agree, I think the coroutines would need to be dispatched through a dedicated (configurable?) thread pool.

We'd be happy to accept contributions that improve the core library to add dispatching support, as long as it does not impact "normal" Java use, but then the Kotlin extension could plug in and have special handling here.

**Comment by hgschmie** [comment]
I wrote some very basic coroutine support a while back (which is alpha, probably buggy and I have no idea if anyone is really using it). I read through this thread and I understand about half of it. What would help me is some code snippets aka "This is what this could look like" or even "here is a conceptual patch" to get an idea where to start. I am fine with failing unit tests as well.

I am not sure that I understand and I am reluctant to engage on work where I am not clear of the outcome. Happy to team up and help (getting some more Kotlin expertise would be great).
