### ISSUE TITLE
"@JdbiRepository" annotated repositories are not supported in AOT mode.

### ISSUE THREAD

**Issue by radzish** [jdbi/jdbi#2694]
I have a repository annotated with @JdbiRepository. All works fine in non-AOT mode.
When I am trying to build application for native mode with maven I am having error:

```
Exception in thread "main" java.lang.IllegalStateException: Error processing bean with name 'com.mycompany.MyRepository': instance supplier is not supported
        at org.springframework.beans.factory.aot.DefaultBeanRegistrationCodeFragments.getTarget(DefaultBeanRegistrationCodeFragments.java:83)
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGenerator.generateBeanDefinitionMethod(BeanDefinitionMethodGenerator.java:85)
        at org.springframework.beans.factory.aot.BeanRegistrationsAotContribution.lambda$generateRegisterBeanDefinitionsMethod$2(BeanRegistrationsAotContribution.java:90)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986)
        at org.springframework.beans.factory.aot.BeanRegistrationsAotContribution.generateRegisterBeanDefinitionsMethod(BeanRegistrationsAotContribution.java:88)
        at org.springframework.beans.factory.aot.BeanRegistrationsAotContribution.lambda$applyTo$1(BeanRegistrationsAotContribution.java:73)
        at org.springframework.aot.generate.GeneratedMethod.<init>(GeneratedMethod.java:54)
        at org.springframework.aot.generate.GeneratedMethods.add(GeneratedMethods.java:112)
        at org.springframework.aot.generate.GeneratedMethods.add(GeneratedMethods.java:89)
        at org.springframework.beans.factory.aot.BeanRegistrationsAotContribution.applyTo(BeanRegistrationsAotContribution.java:72)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
        at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
        at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
        at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
        at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
```

**Comment by stevenschlansker** [comment]
Hi @radzish , thanks for reporting this. "AOT" Spring configuration is not something that the Jdbi maintainers have any experience with.
Do you have a suggestion as to how this could be fixed? Or, is there a way for Jdbi to opt out of AOT processing?

**Comment by MiniDigger** [comment]
AOT is something a user opts into, to be able to run spring in a graal vm native image.
AOT comes with a few restrictions listed here: https://docs.spring.io/spring-framework/reference/core/aot.html
one of which is "Bean definitions with instance suppliers (lambdas or method references) cannot be transformed ahead-of-time."
jdbi repositories happen to be registered using instance suppliers (https://github.com/jdbi/jdbi/blob/master/spring5/src/main/java/org/jdbi/v3/spring5/JdbiRepositoryRegistrar.java#L67), which is why spring throws that error.

I havent digged deeper yet, but from my limited understanding spring wants you to use a static factory method instead to create the beans?

**Comment by stevenschlansker** [comment]
I have not used spring autodiscovery much, but from a brief reading of the code it does not look like these beans can be created statically up-front, since it is discovering the beans to declare at runtime. We require a reference to the under-construction bean definition registry.

We'd happily accept a PR to improve this situation with AOT, but for now I think the Jdbi Spring support only supports runtime definition.

**Comment by stevenschlansker** [comment]
Perhaps a better solution would be to create an annotation processor that generates configuration classes for `@JdbiRepository` types at compile time? But doing this is essentially a rewrite

**Comment by MiniDigger** [comment]
this isn't really my area of expertise either, just stumbled upon this ticket while toying around with the AOT stuff in spring.
maybe I can find some time and look at how other libraries handle this, surely this usecase isnt unique to jdbi and a full blown annotation processor seems kinda overkill for that. 
the way I understand the AOT stuff is that it basically runs the autodiscovery stuff at compile time and generates code that does it statically (to skip it at runtime), so having an AP in jdbi would kinda duplicate that work. we just gotta figure out why spring cant generate that code with how jdbi registers these repositories.

**Comment by hpoettker** [comment]
Spring can't generate the required code because the bean definitions created by the `JdbiRepositoryRegistrar` currently contain references to already instantiated `JdbiRepositoryFactoryBean`s. And Spring cannot reverse-engineer what the code is that would instantiate these objects.

I've opened a PR to resolve the issue: #2727
