### ISSUE TITLE
Statement parser doesn't handle non-ASCII characters well

### ISSUE THREAD

**Issue by liniu** [jdbi/jdbi#350]
org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: Exception parsing for named parameter replacement [statement:"INSERT INTO 营业日数据(餐厅编号,餐厅名称,业务日期,节假日,时段,一级报表项目,二级报表项目,是否末级,金额,标识)  VALUES('0101','福建厦门松柏餐厅','2016-04-29',null,'休闲','DI',null,'是',768.5,'0101-2016.4')", located:"INSERT INTO 营业日数据(餐厅编号,餐厅名称,业务日期,节假日,时段,一级报表项目,二级报表项目,是否末级,金额,标识)  VALUES('0101','福建厦门松柏餐厅','2016-04-29',null,'休闲','DI',null,'是',768.5,'0101-2016.4')", rewritten:"null", arguments:{ positional:{}, named:{}, finder:[]}]
    at org.skife.jdbi.v2.DBI.withHandle(DBI.java:301)
    at com.ei.db.dao.DefaultDao.executeUpdate(DefaultDao.java:584)
    at hkl.fbi.service.YyrsjService.yyrsj2(YyrsjService.java:34)
    at hkl.fbi.service.YyrsjService.yyrsj(YyrsjService.java:104)
    at hkl.fbi.service.YyrsjService.main(YyrsjService.java:116)
Caused by: org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: Exception parsing for named parameter replacement [statement:"INSERT INTO 营业日数据(餐厅编号,餐厅名称,业务日期,节假日,时段,一级报表项目,二级报表项目,是否末级,金额,标识)  VALUES('0101','福建厦门松柏餐厅','2016-04-29',null,'休闲','DI',null,'是',768.5,'0101-2016.4')", located:"INSERT INTO 营业日数据(餐厅编号,餐厅名称,业务日期,节假日,时段,一级报表项目,二级报表项目,是否末级,金额,标识)  VALUES('0101','福建厦门松柏餐厅','2016-04-29',null,'休闲','DI',null,'是',768.5,'0101-2016.4')", rewritten:"null", arguments:{ positional:{}, named:{}, finder:[]}]
    at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter.rewrite(ColonPrefixNamedParamStatementRewriter.java:69)
    at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1296)
    at org.skife.jdbi.v2.Update.execute(Update.java:56)
    at org.skife.jdbi.v2.BasicHandle.update(BasicHandle.java:297)
    at com.ei.db.dao.DefaultDao.lambda$5(DefaultDao.java:585)
    at org.skife.jdbi.v2.DBI.withHandle(DBI.java:298)
    ... 4 more
Caused by: java.lang.IllegalArgumentException: NoViableAltException('营'@[])
    at org.skife.jdbi.rewriter.colon.ColonStatementLexer.reportError(ColonStatementLexer.java:26)
    at org.skife.jdbi.org.antlr.runtime.Lexer.nextToken(Lexer.java:107)
    at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter.parseString(ColonPrefixNamedParamStatementRewriter.java:106)
    at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter.rewrite(ColonPrefixNamedParamStatementRewriter.java:65)
    ... 9 more
Caused by: NoViableAltException('营'@[])
    at org.skife.jdbi.rewriter.colon.ColonStatementLexer.mTokens(ColonStatementLexer.java:872)
    at org.skife.jdbi.org.antlr.runtime.Lexer.nextToken(Lexer.java:89)
    ... 11 more

**Comment by qualidafial** [comment]
JDBI's SQL parser grammar isn't currently equipped to handle non-ASCII characters as identifiers. However, JDBI ignores everything in double quotes. Depending on your database vendor, enquoting your table and column names might be a viable workaround. e.g.

    INSERT INTO "营业日数据"(
      "餐厅编号",
      "餐厅名称",
      "业务日期",
      "节假日",
      "时段",
      "一级报表项目",
      "二级报表项目",
      "是否末级",
      "金额,标识") 
    VALUES(
      '0101',
      '福建厦门松柏餐厅',
      '2016-04-29',
      null,
      '休闲',
      'DI',
      null,
      '是',
      768.5,
      '0101-2016.4')

**Comment by stevenschlansker** [comment]
We'd happily accept a patch to improve this, or you can provide your own `StatementRewriter` implementation that handles this correctly.

Otherwise we'll try to fix it eventually, but this likely isn't going to be a high priority at the moment (core members are busy with the upcoming jdbi3 release and this is a pretty unusual use case)

**Comment by stevenschlansker** [comment]
I think I'll leave a documentation note of this limitation and close the issue for now.  We'd still love a PR to improve it but double-quoting the identifier is a pretty reasonable workaround.
