### ISSUE TITLE
Default methods in SQL Object interfaces

### ISSUE THREAD

**Issue by ElvishJerricco** [jdbi/jdbi#351]
When using an interface for an SQL Object, you cannot write a Java 8 default method, as it will result in a `NoSuchMethodError` at runtime; presumably because JDBI does not properly inherit default methods from interfaces.

```java
public interface MyDAO {
    @SqlQuery("...")
    String getData1();

    @SqlQuery("...")
    String getData2();
    
    default String combineData() {
        return getData1() + getData2();
    }
}
```

Attempting to use this results in this exception

```
! java.lang.NoSuchMethodError: java.lang.Object.combineData()Ljava/lang/String;
! at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$70fdb5e1.CGLIB$combineData$7(<generated>) ~[jdbi-2.63.1.jar:2.63.1]
! at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$70fdb5e1$$FastClassByCGLIB$$9106dac8.invoke(<generated>) ~[jdbi-2.63.1.jar:2.63.1]
! at org.skife.jdbi.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[jdbi-2.63.1.jar:2.63.1]
! at org.skife.jdbi.v2.sqlobject.PassThroughHandler.invoke(PassThroughHandler.java:36) ~[jdbi-2.63.1.jar:2.63.1]
! at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:175) ~[jdbi-2.63.1.jar:2.63.1]
! at org.skife.jdbi.v2.sqlobject.SqlObject$1.intercept(SqlObject.java:75) ~[jdbi-2.63.1.jar:2.63.1]
! at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$70fdb5e1.combineData(<generated>) ~[jdbi-2.63.1.jar:2.63.1]
! at Example.example(Example.java:49) ~[example-serve-1.0-SNAPSHOT.jar:na]
...
```

It's easy enough to work around; just use an abstract class rather than an interface. But I see no reason JDBI shouldn't support this.

**Comment by qualidafial** [comment]
What version of JDBI are you using? We actually added support for this
recently.

**Comment by ElvishJerricco** [comment]
Oh! Of course; I should have mentioned the version. Looks like I'm on 2.55 (using dropwizard-jdbi 0.7.1). Hadn't realized that I wasn't up to date. I'll give it an update and make sure that was the problem.

**Comment by ElvishJerricco** [comment]
Yep, that was it! Sorry for the trouble. Thanks!

**Comment by qualidafial** [comment]
Not a problem. Glad I could help.
