### ISSUE TITLE
Colon statement lexer improvements break `:=`

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#432]
A new v2 test case for out params included a SQL statement that has `$$ BEGIN outparam := 100; END; $$` syntax.  This now breaks with the improved v3 lexer 😢 

```
testOutParameter(org.jdbi.v3.sqlobject.TestOutParameterAnnotation)  Time elapsed: 13.563 sec  <<< ERROR!
org.jdbi.v3.core.exception.UnableToCreateStatementException: Exception parsing for named parameter replacement [statement:"CREATE FUNCTION set100(OUT outparam INT) AS $$ BEGIN outparam \:= 100; END; $$ LANGUAGE plpgsql", rewritten:"null", arguments:{ positional:{}, named:{}, finder:[]}]
	at org.jdbi.v3.sqlobject.TestOutParameterAnnotation.lambda$setUp$0(TestOutParameterAnnotation.java:38)
	at org.jdbi.v3.sqlobject.TestOutParameterAnnotation.setUp(TestOutParameterAnnotation.java:37)
Caused by: java.lang.IllegalArgumentException: NoViableAltException(':'@[])
```

**Comment by qualidafial** [comment]
Fixed by #433
