### ISSUE TITLE
How to use Transaction inside DAO interface

### ISSUE THREAD

**Issue by DerekYangYC** [jdbi/jdbi#546]
I've read this [post ](http://manikandan-k.github.io/2015/05/10/Transactions_in_jdbi.html)but still can't find a good way to deal with it

Let say I have `DAO` like this:

``` java
@UseStringTemplate3StatementLocator("/sql/sql.sql.stg")
public interface TestDao {
    @SqlUpdate
    int action1();

    @SqlUpdate
    int action2();
}
```

And I like to make `action1` and `action2` in the same transaction in `TestDao`. How to do it?

**Comment by arteam** [comment]
Hello, @DerekYangYC. Do you have issues with the standard approach which is described in the blogpost?
```java
@Transaction
void action() {
    action1();
    action2();
}
```

**Comment by DerekYangYC** [comment]
Hi @arteam , the problem is `interface` of Java can't support concrete implementation inside the method so your codes may throw compile error.

**Comment by arteam** [comment]
Oh sorry, I didn't see you use an interface. In that case you can use default methods. They should be supported in the latest versions of JDBI2.
```java
@Transaction
default void action() {
    action1();
    action2();
}
```
That requires Java 8, though.

**Comment by stevenschlansker** [comment]
If you can't use Java 8 you can always use an abstract class in the same way.

**Comment by DerekYangYC** [comment]
I'm using Java 8 so default method is what I chose but it throws `NoSuchMethodError`:

> Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: java.lang.Object.action(Ljava/lang/String;)Ljava/util/Map;
	at org.skife.jdbi.v2.sqlobject.PassThroughTransactionHandler$1.inTransaction(PassThroughTransactionHandler.java:55) ~[jdbi-2.59.jar:2.59]
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:184) ~[jdbi-2.59.jar:2.59]
	at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:327) ~[jdbi-2.59.jar:2.59]
	at org.skife.jdbi.v2.sqlobject.PassThroughTransactionHandler.invoke(PassThroughTransactionHandler.java:42) ~[jdbi-2.59.jar:2.59]
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:175) ~[jdbi-2.59.jar:2.59]
	at org.skife.jdbi.v2.sqlobject.SqlObject$1.intercept(SqlObject.java:75) ~[jdbi-2.59.jar:2.59]
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$79ba0bef.action(<generated>) ~[jdbi-2.59.jar:2.59]
	at com.xx.xx.xx.xx.xx.xx.action(CommonResource.java:97) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.16.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:143) ~[jersey-server-2.16.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:160) ~[jersey-server-2.16.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:158) ~[jersey-server-2.16.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:97) ~[jersey-server-2.16.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.16.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.16.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.16.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:303) [jersey-server-2.16.jar:na]
	... 55 common frames omitted
Caused by: java.lang.NoSuchMethodError: java.lang.Object.action(Ljava/lang/String;)Ljava/util/Map;
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$79ba0bef.CGLIB$action$103(<generated>) ~[jdbi-2.59.jar:2.59]
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$79ba0bef$$FastClassByCGLIB$$660b35a6.invoke(<generated>) ~[jdbi-2.59.jar:2.59]
	at org.skife.jdbi.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[jdbi-2.59.jar:2.59]
	at org.skife.jdbi.v2.sqlobject.PassThroughTransactionHandler$1.inTransaction(PassThroughTransactionHandler.java:48) ~[jdbi-2.59.jar:2.59]
	... 75 common frames omitted

Any idea? @stevenschlansker @arteam

**Comment by DerekYangYC** [comment]
btw I'm using `dropwizard-jdbi:0.8.0` which uses `jdbi 2.59`

**Comment by arteam** [comment]
Unfortunately, the support of default methods were added only in jdbi 2.70. You need your Dropwizard application to a newest jdbi version or use abstract classes instead interfaces.

**Comment by DerekYangYC** [comment]
Understood. Ticket closed

**Comment by qualidafial** [comment]
@DerekYangYC You should be able to use a more recent version of JDBI using dependency management. Assuming you're using Maven:

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.jdbi</groupId>
            <artifactId>jdbi</artifactId>
            <version>2.77</version>
        </dependency>
    </dependencies>
</dependencyManagement>```

This should manage your transitive dependency to JDBI to the version you want. It's backward compatible with 2.59 so you should be fine.

**Comment by msdalp** [comment]
Sorry to bump this again.
```java
public interface CustomerDao {
   @SqlUpdate("delete from customer where id =:customerId")
    void deleteById(@Bind("id") int customerId);

    @SqlUpdate("delete from customer_mail where customer_id =:customerId")
    void deleteMails(@Bind("id") int customerId);

    @Transaction
    default void deleteCustomer(int customerId){
        deleteMails(customerId);
        deleteById(customerId);
    }
}
``` 
Considering we have this Customer interface, ``@Transaction`` is basically useless here by itself if we call the method as below right?
```java
DBManager.getDbi().onDemand(CustomerDao.class).deleteCustomer(customerId);
``` 
Reading the blog note and posts above I somehow assumed above example would work but my tests were failing without changing it to 
```java
DBManager.getDbi().inTransaction((conn, status) -> {
            CustomerDao dao = conn.attach(CustomerDao.class);
            dao.deleteCustomer(customerId);
            return null;
        });
```
I'm using jdbi-2.78 and mysql ``autoCommit="true"``. Is it the expected behavior for ``@Transaction`` which we need to call it always in ``dbi.inTraction`` or am I missing a point with previous call?

**Comment by qualidafial** [comment]
The `@Transaction` annotation should still work with on-demand. Are you observing otherwise? What does your test failure look like?

**Comment by akshayjain-tmdc** [comment]
Do we have an update for this?

> Sorry to bump this again.
> 
> ```java
> public interface CustomerDao {
>    @SqlUpdate("delete from customer where id =:customerId")
>     void deleteById(@Bind("id") int customerId);
> 
>     @SqlUpdate("delete from customer_mail where customer_id =:customerId")
>     void deleteMails(@Bind("id") int customerId);
> 
>     @Transaction
>     default void deleteCustomer(int customerId){
>         deleteMails(customerId);
>         deleteById(customerId);
>     }
> }
> ```
> 
> Considering we have this Customer interface, `@Transaction` is basically useless here by itself if we call the method as below right?
> 
> ```java
> DBManager.getDbi().onDemand(CustomerDao.class).deleteCustomer(customerId);
> ```
> 
> Reading the blog note and posts above I somehow assumed above example would work but my tests were failing without changing it to
> 
> ```java
> DBManager.getDbi().inTransaction((conn, status) -> {
>             CustomerDao dao = conn.attach(CustomerDao.class);
>             dao.deleteCustomer(customerId);
>             return null;
>         });
> ```
> 
> I'm using jdbi-2.78 and mysql `autoCommit="true"`. Is it the expected behavior for `@Transaction` which we need to call it always in `dbi.inTraction` or am I missing a point with previous call?
