### ISSUE TITLE
Colon sign in comments causes NoViableAltException

### ISSUE THREAD

**Issue by IschenkoArtem** [jdbi/jdbi#748]
```
/*
 Just some comment with : inside
*/
SELECT 1.007 AS column_name WHERE :left = :right;
```

This statement causes : 
```
Caused by: java.lang.IllegalArgumentException: NoViableAltException(':'@[])
	at org.skife.jdbi.rewriter.colon.ColonStatementLexer.reportError(ColonStatementLexer.java:26)
	at org.skife.jdbi.org.antlr.runtime.Lexer.nextToken(Lexer.java:107)
	at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter.parseString(ColonPrefixNamedParamStatementRewriter.java:106)
	at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter.rewrite(ColonPrefixNamedParamStatementRewriter.java:65)
	... 59 common frames omitted
Caused by: org.skife.jdbi.org.antlr.runtime.NoViableAltException: null
	at org.skife.jdbi.rewriter.colon.ColonStatementLexer.mTokens(ColonStatementLexer.java:852)
	at org.skife.jdbi.org.antlr.runtime.Lexer.nextToken(Lexer.java:89)
	... 61 common frames omitted
```

**Comment by qualidafial** [comment]
Tracked in #786
