### ISSUE TITLE
JDBI throws MismatchedTokenException(-1!=39) encountering a quote (') inside comment

### ISSUE THREAD

**Issue by ceefour** [jdbi/jdbi#75]
Affects: JDBI 2.49

The culprit is: `/* in warehouse's time zone */` in the query, changing it to `/* in warehouse time zone */` makes JDBI happy.

Stacktrace:

```
Caused by: org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: Exception parsing for named parameter replacement [statement:"null", located:"null", rewritten:"null", arguments:null]
	org.skife.jdbi.v2.DBI.withHandle(DBI.java:277) ~[jdbi-2.49.jar:na]
	org.skife.jdbi.v2.DBI.inTransaction(DBI.java:299) ~[jdbi-2.49.jar:na]
	id.co.bippo.inventory.perpetual.JournalPerpetualInventoryRepository.createQtyTable(JournalPerpetualInventoryRepository.java:220) ~[classes/:na]
	id.co.bippo.inventory.perpetual.JournalPerpetualInventoryRepository.createMissingTables(JournalPerpetualInventoryRepository.java:256) ~[classes/:na]
	id.co.bippo.inventory.perpetual.JournalPerpetualInventoryRepository.initTables(JournalPerpetualInventoryRepository.java:196) ~[classes/:na]
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)(NativeMethodAccessorImpl.java) ~[na:1.7.0_25]
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_25]
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_25]
	java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_25]
	org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:344) ~[spring-beans-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:295) ~[spring-beans-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:130) ~[spring-beans-3.2.3.RELEASE.jar:3.2.3.RELEASE]
	... 65 more
Caused by: org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: Exception parsing for named parameter replacement [statement:"null", located:"null", rewritten:"null", arguments:null]
	org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter.rewrite(ColonPrefixNamedParamStatementRewriter.java:60) ~[jdbi-2.49.jar:na]
	org.skife.jdbi.v2.Batch.execute(Batch.java:107) ~[jdbi-2.49.jar:na]
	org.skife.jdbi.v2.Script.execute(Script.java:72) ~[jdbi-2.49.jar:na]
	id.co.bippo.inventory.perpetual.JournalPerpetualInventoryRepository.executeScript(JournalPerpetualInventoryRepository.java:288) ~[classes/:na]
	id.co.bippo.inventory.perpetual.JournalPerpetualInventoryRepository.access$1(JournalPerpetualInventoryRepository.java:282) ~[classes/:na]
	id.co.bippo.inventory.perpetual.JournalPerpetualInventoryRepository$1.inTransaction(JournalPerpetualInventoryRepository.java:233) ~[classes/:na]
	id.co.bippo.inventory.perpetual.JournalPerpetualInventoryRepository$1.inTransaction(JournalPerpetualInventoryRepository.java:1) ~[classes/:na]
	org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:193) ~[jdbi-2.49.jar:na]
	org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:309) ~[jdbi-2.49.jar:na]
	org.skife.jdbi.v2.DBI$4.withHandle(DBI.java:302) ~[jdbi-2.49.jar:na]
	org.skife.jdbi.v2.DBI.withHandle(DBI.java:274) ~[jdbi-2.49.jar:na]
	... 76 more
Caused by: java.lang.IllegalArgumentException: MismatchedTokenException(-1!=39)
	org.skife.jdbi.rewriter.colon.ColonStatementLexer.reportError(ColonStatementLexer.java:24) ~[jdbi-2.49.jar:na]
	org.skife.jdbi.org.antlr.runtime.Lexer.nextToken(Lexer.java:98) ~[jdbi-2.49.jar:na]
	org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter.parseString(ColonPrefixNamedParamStatementRewriter.java:93) ~[jdbi-2.49.jar:na]
	org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter.rewrite(ColonPrefixNamedParamStatementRewriter.java:56) ~[jdbi-2.49.jar:na]
	... 86 more
Caused by: org.skife.jdbi.org.antlr.runtime.MismatchedTokenException
	org.skife.jdbi.org.antlr.runtime.Lexer.match(Lexer.java:188) ~[jdbi-2.49.jar:na]
	org.skife.jdbi.rewriter.colon.ColonStatementLexer.mQUOTED_TEXT(ColonStatementLexer.java:269) ~[jdbi-2.49.jar:na]
	org.skife.jdbi.rewriter.colon.ColonStatementLexer.mTokens(ColonStatementLexer.java:557) ~[jdbi-2.49.jar:na]
	org.skife.jdbi.org.antlr.runtime.Lexer.nextToken(Lexer.java:84) ~[jdbi-2.49.jar:na]
	... 88 more
```

Complete query as follows:

```
CREATE TABLE jnlinv_qty (
	qty_id bigserial primary key,
	/* Built-in dimensions */
	movement_time timestamptz NOT NULL,
	warehouse_id varchar(255) NOT NULL REFERENCES jnlinv_warehouse(warehouse_id),
	storage_bin_id varchar(255) NOT NULL REFERENCES jnlinv_storage_bin(storage_bin_id),
	product_id varchar(255) NOT NULL REFERENCES jnlinv_product(product_id),
	/* Principals */
	base_color varchar(255) NOT NULL REFERENCES jnlinv_base_color(base_color),
	base_size varchar(255) NOT NULL REFERENCES jnlinv_base_size(base_size),

	/* Measures */
	qty_on_hand numeric(24, 8) NOT NULL,
	qty_reserved numeric(24, 8) NOT NULL,
	qty_picked numeric(24, 8) NOT NULL,
	qty_available numeric(24, 8) NOT NULL,
	qty_produced numeric(24, 8) NOT NULL,
	/* Convenience for mutation report */
	qty_on_hand_delta numeric(24,8),         
	qty_on_hand_update numeric(24,8),        
	qty_reserved_delta numeric(24,8),        
	qty_picked_delta numeric(24,8),          
	/* Informational columns */
	physical_inventory_id varchar(36),
	stock_reservation_id varchar(36),
	goods_receipt_id varchar(36),
	return_to_vendor_shipment_id varchar(36),
	goods_shipment_id varchar(36),
	return_material_receipt_id varchar(36),
	movement_local_time timestamp NOT NULL, /* in warehouse's time zone */
	/* Administrative columns */
	creation_time timestamptz NOT NULL default 'now()',
	/* Key (combined dimensions) must be unique */
	CONSTRAINT jnlinv_dimensions_key UNIQUE (movement_time, warehouse_id, storage_bin_id, product_id, 
                                                                                                   base_color, 
                                                                                                   base_size)
);

CREATE INDEX idx_jnlinv_qty_movement_time_id ON jnlinv_qty (movement_time);
CREATE INDEX idx_jnlinv_qty_movement_local_time_id ON jnlinv_qty (movement_local_time);
/* Built-in dimensions */
CREATE INDEX idx_jnlinv_qty_warehouse_id ON jnlinv_qty (warehouse_id);
CREATE INDEX idx_jnlinv_qty_storage_bin_id ON jnlinv_qty (storage_bin_id);
CREATE INDEX idx_jnlinv_qty_product_id ON jnlinv_qty (product_id);
/* Principals */
CREATE INDEX idx_jnlinv_qty_base_color ON jnlinv_qty (base_color);
CREATE INDEX idx_jnlinv_qty_base_size ON jnlinv_qty (base_size);
```

**Comment by ianhattendorf** [comment]
I'm running into this with v2.78 and H2, is it possible there's a regression? Works fine if I remove the `'` from the comment. Stack trace (filtered):

```
org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: Exception parsing for named parameter replacement [statement:"CREATE TABLE SomeTable
(
DatePulled timestamp,
IsOld bit
);

/* Don't allow ... */
CREATE UNIQUE INDEX SomeIndex
ON SomeTable (DatePulled, IsOld);
", located:"CREATE TABLE SomeTable
(
DatePulled timestamp,
IsOld bit
);

/* Don't allow ... */
CREATE UNIQUE INDEX SomeIndex
ON SomeTable (DatePulled, IsOld);
", rewritten:"null", arguments:{ positional:{}, named:{}, finder:[]}]
        at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter.rewrite(ColonPrefixNamedParamStatementRewriter.java:69) ~[jdbi-2.78.jar!/:2.78]
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1296) ~[jdbi-2.78.jar!/:2.78]
        at org.skife.jdbi.v2.Update.execute(Update.java:56) ~[jdbi-2.78.jar!/:2.78]
        at org.skife.jdbi.v2.BasicHandle.update(BasicHandle.java:305) ~[jdbi-2.78.jar!/:2.78]
        at org.skife.jdbi.v2.BasicHandle.execute(BasicHandle.java:423) ~[jdbi-2.78.jar!/:2.78]
        at xxx.xxx.xxx.xxx.SomeTable_export.Database.initDb(Database.java:33) ~[classes!/:na]
        at xxx.xxx.xxx.xxx.SomeTable_export.SomeTableExportClient.run(SomeTableExportClient.java:168) ~[classes!/:na]

        at xxx.xxx.xxx.xxx.ApplicationCommandLineRunner.run(ApplicationCommandLineRunner.java:72) ~[classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
        at xxx.xxx.xxx.xxx.Application.main(Application.java:38) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_131]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [asu-starrez-client-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [asu-starrez-client-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [asu-starrez-client-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [asu-starrez-client-1.0-SNAPSHOT.jar:na]
Caused by: java.lang.IllegalArgumentException: MismatchedTokenException(-1!=39)
        at org.skife.jdbi.rewriter.colon.ColonStatementLexer.reportError(ColonStatementLexer.java:26) ~[jdbi-2.78.jar!/:2.78]
        at org.skife.jdbi.org.antlr.runtime.Lexer.nextToken(Lexer.java:103) ~[jdbi-2.78.jar!/:2.78]
        at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter.parseString(ColonPrefixNamedParamStatementRewriter.java:106) ~[jdbi-2.78.jar!/:2.78]
        at org.skife.jdbi.v2.ColonPrefixNamedParamStatementRewriter.rewrite(ColonPrefixNamedParamStatementRewriter.java:65) ~[jdbi-2.78.jar!/:2.78]
        ... 22 common frames omitted
Caused by: org.skife.jdbi.org.antlr.runtime.MismatchedTokenException: null
        at org.skife.jdbi.org.antlr.runtime.Lexer.match(Lexer.java:197) ~[jdbi-2.78.jar!/:2.78]
        at org.skife.jdbi.rewriter.colon.ColonStatementLexer.mQUOTED_TEXT(ColonStatementLexer.java:707) ~[jdbi-2.78.jar!/:2.78]
        at org.skife.jdbi.rewriter.colon.ColonStatementLexer.mTokens(ColonStatementLexer.java:906) ~[jdbi-2.78.jar!/:2.78]
        at org.skife.jdbi.org.antlr.runtime.Lexer.nextToken(Lexer.java:89) ~[jdbi-2.78.jar!/:2.78]
        ... 24 common frames omitted
```

**Comment by qualidafial** [comment]
@ianhattendorf It looks like there are two statements in your SQL. Try running this with `Script`, not `Handle.execute()`.

**Comment by ianhattendorf** [comment]
That fixed it, thanks @qualidafial.

**Comment by arteam** [comment]
That's right, `Script` uses `SqlScriptParser` which strips comments from the provided script and separates it to several SQL statements. `Handle`, on the other hand, tries to parse the incoming data as a SQL statement.
