### ISSUE TITLE
Unable generate keys for a not prepared batch if inserted list size to contain BatchChunkSize

### ISSUE THREAD

**Issue by JavaWebinar** [jdbi/jdbi#781]
@SqlBatch("INSERT INTO users (name) VALUES (:name)")
    @GetGeneratedKeys
    public abstract int[] insertBatch(@BindBean List<User> users, @BatchChunkSize int chunk);

finished with `java.lang.IllegalArgumentException: Unable generate keys for a not prepared batch` if 
last parts.size()==0 (inserted list size to contain BatchChunkSize)
```
java.lang.IllegalArgumentException: Unable generate keys for a not prepared batch

	at org.skife.jdbi.v2.PreparedBatch.internalBatchExecute(PreparedBatch.java:147)
	at org.skife.jdbi.v2.PreparedBatch.executeAndGenerateKeys(PreparedBatch.java:105)
	at org.skife.jdbi.v2.PreparedBatch.executeAndGenerateKeys(PreparedBatch.java:134)
	at org.skife.jdbi.v2.sqlobject.BatchHandler$2.value(BatchHandler.java:75)
	at org.skife.jdbi.v2.sqlobject.BatchHandler$5.inTransaction(BatchHandler.java:231)
	at org.skife.jdbi.v2.sqlobject.BatchHandler$5.inTransaction(BatchHandler.java:227)
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:183)
	at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:338)
	at org.skife.jdbi.v2.sqlobject.BatchHandler.executeBatch(BatchHandler.java:226)
	at org.skife.jdbi.v2.sqlobject.BatchHandler.invoke(BatchHandler.java:204)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:224)
	at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:133)
	at 
```
what for `PreparedBatch` line 146-148 ?

**Comment by qualidafial** [comment]
Thanks for reporting this! The stack trace was very helpful.

I've opened a PR with a fix in #783. Let's move any further discussion there.
