### ISSUE TITLE
Mapping List<Enum> to Sql Varchar-Array column

### ISSUE THREAD

**Issue by datazuul** [jdbi/jdbi#853]
we have an enum Role:

```java
public enum Role {
  ADMIN, CONTENT_MANAGER;
}
```

A user can have several Roles:

```java
public class UserImpl {
  ...
  private List<Role> roles = new ArrayList<>(0);
  @Override
  public List<Role> getRoles() {
    return this.roles;
  }

  @Override
  public void setRoles(List<Role> userRoles) {
    this.roles = userRoles;
  }
  ...
}
```
We want to save it like this to postgres schema:

```sql
create table users (
  id serial primary key,
  email varchar(255) not null unique,
  enabled boolean default true,
  firstname varchar(255),
  lastname varchar(255),
  password varchar(255),
  roles varchar(255)[]
);
```

JDBI code:

```java
public <S extends UserImpl> S save(S user) {
    UserImpl result = dbi.withHandle(h -> h.createQuery(
            "INSERT INTO users(email, enabled, firstname, lastname, password, roles) VALUES (:email, :enabled, :firstname, :lastname, :passwordHash, :roles) RETURNING *")
            .bindBean(user)
            .mapToBean(UserImpl.class)
            .findOnly());
    return (S) result;
  }
```

The code works so far (when removing the field 'roles') in above code , so that we get the saved UserImpl back filled with generated id.

But when executing the code as above, we get this Exception:

```sh
...
exception stack trace
org.jdbi.v3.core.statement.UnableToExecuteStatementException: Unable to execute, no named parameter matches 'roles'. [statement:"INSERT INTO users(email, enabled, firstname, lastname, password, roles) VALUES (:email, :enabled, :firstname, :lastname, :passwordHash, :roles) RETURNING *", rewritten:"INSERT INTO users(email, enabled, firstname, lastname, password, roles) VALUES (?, ?, ?, ?, ?, ?) RETURNING *", arguments:{ positional:{}, named:{}, finder:[{lazy bean property arguments "de.digitalcollections.cudami.model.impl.security.UserImpl@7db8e59"]}]
	at org.jdbi.v3.core.rewriter.InternalRewrittenStatement.lambda$bindNamed$0(InternalRewrittenStatement.java:77)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.jdbi.v3.core.rewriter.InternalRewrittenStatement.bindNamed(InternalRewrittenStatement.java:76)
	at org.jdbi.v3.core.rewriter.InternalRewrittenStatement.bind(InternalRewrittenStatement.java:43)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1381)
	at org.jdbi.v3.core.result.ResultProducers.lambda$getResultSet$2(ResultProducers.java:59)
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:53)
	at org.jdbi.v3.core.result.ResultIterable.findOnly(ResultIterable.java:97)
	at de.digitalcollections.cudami.server.backend.impl.jdbi.UserRepositoryImpl.lambda$save$2(UserRepositoryImpl.java:108)
```

How to properly save the List<Role> (list of enums) field as array of enum-names?
We read that enums are properly stored, but maybe a list of enums is not yet supported? If so, how to work around?

**Comment by arteam** [comment]
I believe you need to register the `Role` type as an array type, so Jdbi can map `List<Role>` to `varchar[]`.

```java
handle.registerArrayType(Role.class, "varchar")
```

Otherwise Jdbi doesn't know the exact type of the SQL array when creating it via a `connection.createArrayOf(typeName, array)` JDBC call.

**Comment by qualidafial** [comment]
Are you using v2? At this time array column support is only in v3.

**Comment by qualidafial** [comment]
Aside: I hope you're not storing passwords in plain text.

**Comment by datazuul** [comment]
We are using jdbi 3.0.0-beta1 and no we are not storing passwords in plaintext ;-). We use BCrypt.

@arteam : thank you, this works:

```java
public <S extends UserImpl> S save(S user) {
    UserImpl result = dbi.withHandle(h -> h
            .registerArrayType(Role.class, "varchar")
            .createQuery("INSERT INTO users(email, enabled, firstname, lastname, passwordHash, roles) VALUES (:email, :enabled, :firstname, :lastname, :passwordHash, :roles) RETURNING *")
            .bindBean(user)
            .mapToBean(UserImpl.class)
            .findOnly());
    return (S) result;
  }
```

Meanwhile we also found a workaround that also works (but above solution is the preferred one):

```java
public <S extends UserImpl> S save(S user) {
    UserImpl result = dbi.withHandle(h -> h.createQuery(
            "INSERT INTO users(email, enabled, firstname, lastname, passwordHash, roles) VALUES (:email, :enabled, :firstname, :lastname, :passwordHash, :roles) RETURNING *")
            .bindBean(user)
            .bind("roles", user.getRoles().stream().map(Role::name).toArray(String[]::new))
            .mapToBean(UserImpl.class)
            .findOnly());
    return (S) result;
}
```

**Comment by qualidafial** [comment]
Your first solution will be the only one that works starting in beta 2. We added an error message when a bean mapper finds a bean property for the column, but can't find a column mapper for the property type.

**Comment by qualidafial** [comment]
Closing as answered.

One note: you can call `registerArrayType()` once per array type on the global `Jdbi` instance, rather than calling it for every statement.
