### ISSUE TITLE
Parameter binding for non-select not works

### ISSUE THREAD

**Issue by wenerme** [jdbi/jdbi#870]
SQLite support program statement

```java
// This is ok
    List<TableInfoRow> rows = h
        .createQuery("PRAGMA table_info('py')")
        .map(TableInfoRow.class)
        .list();
```

```java
@RegisterMapperFactory(BeanMapperFactory.class)
  interface SQLiteDAO {

// Not works
    @SqlQuery("PRAGMA table_info(:name)")
    List<TableInfoRow> tableInfo(@Bind("name") String tableName);

    @Data
    class TableInfoRow {

      private Integer cid;
      private String name;
      private String type;
      private Integer notnull;
      private Integer pk;

    }
  }

```

```
org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "?": syntax error) [statement:"PRAGMA table_info(:name)", located:"PRAGMA table_info(:name)", rewritten:"PRAGMA table_info(?)", arguments:{ positional:{}, named:{name:'py'}, finder:[]}]

	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1307)
	at org.skife.jdbi.v2.Query.fold(Query.java:173)
	at org.skife.jdbi.v2.Query.list(Query.java:82)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:253)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:46)
	at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:41)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:224)
	at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:133)
	at play.dict.PlayScel$SQLiteDAO$$EnhancerByCGLIB$$6cc8a87d.tableInfo(<generated>)
	at play.dict.PlayScel.testSQL(PlayScel.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "?": syntax error)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
	at org.sqlite.core.DB.prepare(DB.java:227)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:235)
	at org.skife.jdbi.v2.DefaultStatementBuilder.create(DefaultStatementBuilder.java:54)
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1303)
	... 31 more
```

**Comment by qualidafial** [comment]
The stack trace is a SQLite exception, indicating a syntax error in your statement.

Are you sure `PRAGMA table_info` supports binding that parameter? Maybe it only allows a literal.

Try this:

Try your second example again, but use a `@Define` instead of `@Bind`, and use StringTemplate:

```java
@SqlQuery("PRAGMA table_info(<name>)")
@UseStringTemplate3StatementLocator
List<TableInfoRow> tableInfo(@Define("name") String tableName);
```

StringTemplate replaces the angle bracketed `<name>` token with the value of the defined attribute "name".

**Comment by stevenschlansker** [comment]
I believe the above answer is correct (`bind` only works for parameters in statements, not DDL or Pragma type features) -- closing due to inactivity.  Please feel free to reopen if you have additional information.
