### ISSUE TITLE
forwardOnly() method for Query class (v2)

### ISSUE THREAD

**Issue by dasdy** [jdbi/jdbi#874]
Using flag ResultSet.FORWARD_ONLY is helpful in a lot of situations for performance gain. Unfortunately, it can't be set after the statement is compiled (so `StatementCustomizer` can't be used). Currently this flag is used only in case if `concurrentUpdatable()` is used on a `Query` object

Such databases as SQLite don't have support for concurrency type `ResultSet.CONCUR_UPDATABLE`, which means that using `Query.concurrentUpdatable()` will lead to exception:

```java
handle.createQuery("SELECT * FOM MYTABLE")
        .concurrentUpdatable()
        .list();
```

```
Exception in thread "main" org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: java.sql.SQLException: SQLite only supports CONCUR_READ_ONLY cursors [statement:"SELECT * FOM MYTABLE", located:"SELECT * FOM MYTABLE", rewritten:"SELECT * FOM MYTABLE", arguments:{ positional:{}, named:{}, finder:[]}]
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1307)
	at org.skife.jdbi.v2.Query.fold(Query.java:173)
	at org.skife.jdbi.v2.Query.list(Query.java:82)
	at org.skife.jdbi.v2.Query.list(Query.java:75)
	at com.ConcurrentUpdatableThrow.main(ConcurrentUpdatableThrow.java:11)
Caused by: java.sql.SQLException: SQLite only supports CONCUR_READ_ONLY cursors
	at org.sqlite.core.CoreConnection.checkCursor(CoreConnection.java:355)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:46)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263)
	at org.skife.jdbi.v2.DefaultStatementBuilder.create(DefaultStatementBuilder.java:51)
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1303)
```

Could something like `Query.forwardOnly()` method be added? Building a statement from a connection would look like
```java
conn.prepareStatement(sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
```

**Comment by stevenschlansker** [comment]
Is there any reason not to just always go `FORWARD_ONLY`?

**Comment by stevenschlansker** [comment]
Note that v3 fixes this by doing this unconditionally -- databases do not seem to even support reverse result sets generally.

**Comment by stevenschlansker** [comment]
I think it's time to start closing non-critical v2 issues.  If someone opens a PR we'd accept it, but v3 fixes this!
