### ISSUE TITLE
JavaBean: Does GetGeneratedKeys work with SqlUpdate?

### ISSUE THREAD

**Issue by jknack** [jdbi/jdbi#894]
Documentation mention we can return a JavaBean with generated keys using `SqlUpdate` or `SqlBatch`: https://jdbi.github.io/#__getgeneratedkeys

But today, it doesn't work for `SqlUpdate`:

```java
@RegisterRowMapper(Pet.Mapper.class)
public interface PetRepository {
  @SqlUpdate("insert into pets (name) values (:name)")
  @GetGeneratedKeys
  Pet insert(String name);

  @SqlQuery("select * from pets")
  List<Pet> list();
}
```

The insert method resulted in exception like:

```
org.jdbi.v3.core.result.ResultSetException: Error thrown mapping result set into return type [statement:"insert into pets (name) values (:name)", rewritten:"insert into pets (name) values (:name)", parsed:"insert into pets (name) values (?)", arguments:{ positional:{0:Lala}, named:{name:Lala}, finder:[]}]
        at org.jdbi.v3.core.result.ResultSetResultIterator.next(ResultSetResultIterator.java:85)
        at org.jdbi.v3.core.result.ResultIterable.findFirst(ResultIterable.java:117)
        at org.jdbi.v3.sqlobject.statement.internal.ResultReturner$CollectedResultReturner.result(ResultReturner.java:140)
        at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$new$0(SqlUpdateHandler.java:51)
        at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$configureReturner$3(SqlUpdateHandler.java:69)
        at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:139)
        at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.invoke(SqlUpdateHandler.java:29)
        at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$12(SqlObjectFactory.java:157)
        at org.jdbi.v3.core.ConstantHandleSupplier.invokeInContext(ConstantHandleSupplier.java:52)
        at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$13(SqlObjectFactory.java:156)
        at com.sun.proxy.$Proxy44.insert(Unknown Source)
....
Caused by: org.h2.jdbc.JdbcSQLException: Column "id" not found [42122-190]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3155)
        at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3217)
        at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:669)
        at starter.jdbi.Pet$Mapper.map(Pet.java:13)
```

**Comment by stevenschlansker** [comment]
> On Sep 27, 2017, at 12:19 PM, Edgar Espina <notifications@github.com> wrote:
> 
> @SqlUpdate("insert into pets (id, name) values (:name)")

Sure looks like you've got a mismatch of inserting 2 columns with 1 value?

**Comment by jknack** [comment]
It was a typo while pasting. It doesn't work

`@SqlUpdate("insert into pets (name) values (:name)")`

(updated/edited the issue)

**Comment by stevenschlansker** [comment]
I'm confused then how you still get, `Column "id" not found [42122-190]` -- can you show the table definition?

**Comment by jknack** [comment]
Here is the table definition:

```
jdbi.useHandle(h -> {
        h.createUpdate("create table pets (id bigint auto_increment, name varchar(255))")
            .execute();

        PetRepository repo = h.attach(PetRepository.class);
        repo.insert("Lala");
        repo.insert("Mandy");
        repo.insert("Sasha");
      });
```

The mapper refers to the `id` column:

```java
 public static class Mapper implements RowMapper<Pet> {
    @Override public Pet map(final ResultSet rs, final StatementContext ctx) throws SQLException {
      return new Pet(rs.getLong("id"), rs.getString("name"));
    }
  }
```

and now I'm confused about how to do it :S

Probably missing something obvious

**Comment by FredDeschenes** [comment]
I can also reproduce this issue. It seems that returning an `Integer` (the id itself) works, but returning mapped objects (as mentioned in the [documentation](https://jdbi.github.io/#__getgeneratedkeys)) fails.

It looks like the result set only contains a single row with a single numeric column and not the entirety of the columns.

**Comment by FredDeschenes** [comment]
After looking into this more, it seems like it's just the H2 driver that doesn't support returning more than 1 column when getting generated keys (["The method getGeneratedKeys only supports one column"](https://github.com/h2database/h2database/blob/master/h2/src/main/org/h2/jdbc/JdbcConnection.java#L1171)).

Other DB drivers (ex: [PostgreSQL](https://github.com/pgjdbc/pgjdbc/blob/246b759cdc264c2732717dbd6ff9f8f472024196/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L1612)) seem to support it though.

**Comment by qualidafial** [comment]
What database vendor is this? I'm only aware of Postgres that will provide the entire row as generated keys. Try adding the column names to the annotation e.g. `@GetGeneratedKeys({"id", "name"})` and see if that helps.

**Comment by qualidafial** [comment]
Ah, I missed your earlier comment. Looks like you'll have to get the ID as the generated key and then request the full state back in a separate query.

**Comment by stevenschlansker** [comment]
Yeah, sorry, I don't think we can work around this driver weakness feasibly in jdbi.  I guess we should document this pitfall and close the ticket, unless anyone has a proposal.

**Comment by jknack** [comment]
What about doing something like:

> Get the ID as the generated key and then request the full state back in a separate query.

Jdbi needs to identify the problem and recover from it automatically... not sure

**Comment by stevenschlansker** [comment]
I think that's the right pattern to solve the problem.  I don't think jdbi should do it transparently for you - it'd be a fine extension to add on thought.

**Comment by qualidafial** [comment]
I think we should document in the APIs what we know about database support for this use case: i.e. Postgres supports it, H2 does not, a disclaimer that we don't know how other database vendors will behave, and possibly an invitation to let us know if anybody finds out the level of support from other vendors.

**Comment by stevenschlansker** [comment]
#901 added docs for this pitfall
