### ISSUE TITLE
(v2) @Transaction not honored for default interface methods?

### ISSUE THREAD

**Issue by gfecher** [jdbi/jdbi#929]
Hi,

With the following maven pom file:
```
  <dependencies>
    <dependency>
      <groupId>org.jdbi</groupId>
      <artifactId>jdbi</artifactId>
      <version>2.78</version>
    </dependency>
    <dependency>
      <groupId>org.apache.derby</groupId>
      <artifactId>derby</artifactId>
      <version>10.11.1.1</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
```

Running the following application:
```java
import org.skife.jdbi.v2.DBI;
import org.skife.jdbi.v2.Handle;
import org.skife.jdbi.v2.sqlobject.SqlQuery;
import org.skife.jdbi.v2.sqlobject.Transaction;
import org.skife.jdbi.v2.tweak.HandleCallback;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.io.Writer;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class JdbiTransactionTest {
    public interface FirstLastIdInterfaceV2Dao {
        @SqlQuery("SELECT min(id) as min_id FROM table_test")
        Integer getFirstId();

        @SqlQuery("SELECT max(id) as max_id FROM table_test")
        Integer getLastId();

        @Transaction
        default List<Integer> getFirstAndLastId() {
            System.out.println(getStackTrace(new Throwable()));
            return Stream.of(getFirstId(), getLastId()).collect(Collectors.toList());
        }
    }

    public static abstract class FirstLastIdAbstractClassV2Dao {
        @SqlQuery("SELECT min(id) as min_id FROM table_test")
        public abstract Integer getFirstId();

        @SqlQuery("SELECT max(id) as max_id FROM table_test")
        public abstract Integer getLastId();

        @Transaction
        public List<Integer> getFirstAndLastId() {
            System.out.println(getStackTrace(new Throwable()));
            return Stream.of(getFirstId(), getLastId()).collect(Collectors.toList());
        }
    }

    public static void main(String[] args) throws Exception {
        DBI dbi = new DBI("jdbc:derby:memory:testdb;create=true");

        dbi.withHandle(new HandleCallback<Void>() {
            public Void withHandle(Handle handle) throws Exception {
                handle.execute("create table table_test (id int)");
                handle.execute("insert into table_test values (1)");
                handle.execute("insert into table_test values (2)");
                return null;
            }
        });

        final FirstLastIdInterfaceV2Dao firstLastIdInterfaceV2Dao = dbi.onDemand(FirstLastIdInterfaceV2Dao.class);

        System.out.println(firstLastIdInterfaceV2Dao.getFirstAndLastId());

        final FirstLastIdAbstractClassV2Dao firstLastIdAbstractClassV2Dao =
                dbi.onDemand(FirstLastIdAbstractClassV2Dao.class);

        System.out.println(firstLastIdAbstractClassV2Dao.getFirstAndLastId());
    }

    public static String getStackTrace(Throwable aThrowable) {
        Writer result = new StringWriter();
        PrintWriter printWriter = new PrintWriter(result);
        aThrowable.printStackTrace(printWriter);
        return result.toString();
    }
}
```

I get the following output:
```
java.lang.Throwable
	at JdbiTransactionTest$FirstLastIdInterfaceV2Dao.getFirstAndLastId(JdbiTransactionTest.java:24)
	at JdbiTransactionTest.main(JdbiTransactionTest.java:57)

[1, 2]
java.lang.Throwable
	at JdbiTransactionTest$FirstLastIdAbstractClassV2Dao.getFirstAndLastId(JdbiTransactionTest.java:38)
	at JdbiTransactionTest$FirstLastIdAbstractClassV2Dao$$EnhancerByCGLIB$$fc783d72.CGLIB$getFirstAndLastId$0(<generated>)
	at JdbiTransactionTest$FirstLastIdAbstractClassV2Dao$$EnhancerByCGLIB$$fc783d72$$FastClassByCGLIB$$5ddaba04.invoke(<generated>)
	at org.skife.jdbi.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.skife.jdbi.v2.sqlobject.PassThroughTransactionHandler$1.inTransaction(PassThroughTransactionHandler.java:50)
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:183)
	at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:338)
	at org.skife.jdbi.v2.sqlobject.PassThroughTransactionHandler.invoke(PassThroughTransactionHandler.java:44)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:224)
	at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:133)
	at JdbiTransactionTest$FirstLastIdAbstractClassV2Dao$$EnhancerByCGLIB$$fc783d72.getFirstAndLastId(<generated>)
	at JdbiTransactionTest.main(JdbiTransactionTest.java:62)

[1, 2]
```

The above seems to indicate that the `@Transaction` annotation on the default interface method is not honored.

Can anyone tell me what I'm doing wrong?

Thanks,
Feso

**Comment by qualidafial** [comment]
I think you're right--this looks like a bug.

**Comment by arteam** [comment]
I believe it's a known bug, I've encountered it several times in v2. Can't find the reference issue, though.

**Comment by gfecher** [comment]
You may be referring to https://github.com/jdbi/jdbi/issues/546 that in light of this issue should probably not have been closed.

**Comment by stevenschlansker** [comment]
closing v2 issues, this works in v3
